import { CefrLevel } from "@/lib/supabase/types";

/**
 * Banque d'items du test de placement.
 *
 * Calibrage : chaque palier reprend les descripteurs du référentiel ТРКИ /
 * TORFL, le standard officiel du russe langue étrangère, aligné sur le CECR :
 *
 *   1 · A1 — Элементарный : présent, у меня есть, prépositionnel de lieu,
 *            accusatif d'objet direct, possessifs, mots interrogatifs,
 *            lexique du quotidien.
 *   2 · A2 — Базовый : passé et futur, génitif après нет / у, datif avec
 *            нравиться, opposition lieu (в + prép.) / direction (в + acc.),
 *            accord après 2-4, verbes de déplacement идти/ходить/ехать.
 *   3 · B1 — ТРКИ-1 : système casuel complet dont l'instrumental, aspect en
 *            contexte, verbes de déplacement préfixés, subordonnées
 *            (который, чтобы), conditionnel en бы, comparatif/superlatif.
 *   4 · B2 — ТРКИ-2 : participes actifs et passifs, gérondifs, passif,
 *            régime verbal (интересоваться + instr., избегать + gén.,
 *            уделять внимание + dat.), conjonctions complexes, discours
 *            indirect en ли, dérivation.
 *   5 · C1 — ТРКИ-3 : phraséologie, registre, régimes rares, nuances
 *            aspectuelles, corrélations syntaxiques (чем… тем…).
 *
 * Règles de rédaction, pour que le test MESURE au lieu de piéger :
 * - un item = une compétence, testée en contexte (phrase à trou), pas de
 *   question métalinguistique du type « quel est le genre de ce mot ? » ;
 * - une seule réponse défendable : les items dont deux options se disent
 *   réellement en russe ont été écartés (ex. «ушёл/вышел из дома») ;
 * - les distracteurs sont des erreurs plausibles à ce niveau (mauvais cas,
 *   mauvais aspect), pas du remplissage absurde ;
 * - l'explication enseigne la règle, elle ne se contente pas de donner la
 *   réponse.
 */

export type LevelSkill = "grammaire" | "lexique";

/**
 * Domaine grammatical de l'item — sert au RAPPORT du test, là où `skill` sert
 * seulement à équilibrer la composition d'un bloc.
 *
 * C'est ce découpage qui permet de dire « tu valides B1 ; il t'a manqué les
 * participes et le régime verbal » au lieu d'un simple niveau. Il recoupe
 * volontairement les modules de l'app : un domaine faible qui a son module
 * (cas, mouvement) renvoie vers un entraînement, un domaine faible qui n'en
 * a pas (aspect, participes) est une limite connue du programme.
 */
export type LevelDomain =
  | "lexique"
  | "morphologie"
  | "cas"
  | "aspect"
  | "mouvement"
  | "syntaxe"
  | "participes";

export const DOMAIN_LABEL: Record<LevelDomain, string> = {
  lexique: "Vocabulaire",
  morphologie: "Formes et accords",
  cas: "Cas et rection",
  aspect: "Aspect verbal",
  mouvement: "Verbes de mouvement",
  syntaxe: "Syntaxe",
  participes: "Participes et gérondifs",
};

/** Domaines qui ont un module d'entraînement dans l'app. */
export const DOMAIN_PRACTICE: Partial<Record<LevelDomain, { href: string; label: string }>> = {
  cas: { href: "/cases", label: "Module Cas" },
  mouvement: { href: "/motion", label: "Module Verbes de mouvement" },
  aspect: { href: "/aspect", label: "Module Aspect" },
  participes: { href: "/participles", label: "Module Participes" },
  lexique: { href: "/vocabulary", label: "Module Vocabulaire" },
};

export interface LevelQuestion {
  id: string;
  tier: number; // 1 (A1) → 5 (C1)
  skill: LevelSkill;
  domain: LevelDomain;
  prompt: string; // consigne en français
  question: string; // le contenu russe
  options: string[];
  correctIndex: number;
  explain: string;
}

// Un palier par niveau CEFR au-dessus du plancher A0 (palier 1 non validé
// → grand débutant absolu).
export const TIER_LEVELS: CefrLevel[] = ["A1", "A2", "B1", "B2", "C1"];
export const MIN_TIER = 1;
export const MAX_TIER = TIER_LEVELS.length;

export function levelForTier(tier: number): CefrLevel {
  if (tier < MIN_TIER) return "A0";
  return TIER_LEVELS[Math.min(tier, MAX_TIER) - 1];
}

export const LEVEL_QUESTIONS: LevelQuestion[] = [
  // ─── Palier 1 · A1 — Элементарный уровень ────────────────────────
  {
    id: "a1-lex-spasibo",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "спаси́бо",
    options: ["bonjour", "merci", "au revoir", "s'il te plaît"],
    correctIndex: 1,
    explain: "«спаси́бо» = merci. «пожа́луйста» = s'il te plaît / je t'en prie.",
  },
  {
    id: "a1-lex-dosvidaniya",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie cette formule ?",
    question: "До свида́ния!",
    options: ["Bonjour !", "Bonne nuit !", "Au revoir !", "Bienvenue !"],
    correctIndex: 2,
    explain: "«До свида́ния» = au revoir (littéralement « jusqu'à la revoyure »).",
  },
  {
    id: "a1-lex-khleb",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "хлеб",
    options: ["lait", "pain", "eau", "viande"],
    correctIndex: 1,
    explain: "«хлеб» = pain. «молоко́» = lait, «вода́» = eau, «мя́со» = viande.",
  },
  {
    id: "a1-lex-ponedelnik",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Quel jour de la semaine est-ce ?",
    question: "понеде́льник",
    options: ["dimanche", "lundi", "mardi", "samedi"],
    correctIndex: 1,
    explain: "«понеде́льник» = lundi, le jour qui suit «неде́ля» au sens ancien de dimanche.",
  },
  {
    id: "a1-com-kakvaszovut",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que demande-t-on ?",
    question: "Как вас зову́т?",
    options: [
      "Comment allez-vous ?",
      "Où habitez-vous ?",
      "Comment vous appelez-vous ?",
      "Quel âge avez-vous ?",
    ],
    correctIndex: 2,
    explain: "«Как вас зову́т?» = comment vous appelle-t-on ? On répond «Меня́ зову́т…».",
  },
  {
    id: "a1-com-kakdela",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie cette question ?",
    question: "Как дела́?",
    options: ["Comment ça va ?", "Qu'est-ce que c'est ?", "Où es-tu ?", "Tu fais quoi ?"],
    correctIndex: 0,
    explain: "«Как дела́?» = comment ça va ? (littéralement « comment vont les affaires »).",
  },
  {
    id: "a1-gram-govoryu",
    domain: "morphologie",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Je parle russe. »",
    question: "Я ___ по-ру́сски.",
    options: ["говори́ть", "говори́т", "говорю́", "говори́м"],
    correctIndex: 2,
    explain: "1re personne du singulier : говорю́. «говори́т» = il/elle parle, «говори́м» = nous parlons.",
  },
  {
    id: "a1-gram-prep-lieu",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « J'habite à Moscou. »",
    question: "Я живу́ ___ Москве́.",
    options: ["в", "на", "из", "с"],
    correctIndex: 0,
    explain: "Le lieu où l'on est se dit «в» + prépositionnel : в Москве́.",
  },
  {
    id: "a1-gram-possessif",
    domain: "morphologie",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « C'est ma sœur. »",
    question: "Э́то ___ сестра́.",
    options: ["мой", "моя́", "моё", "мои́"],
    correctIndex: 1,
    explain: "«сестра́» est féminin : le possessif s'accorde → моя́.",
  },
  {
    id: "a1-gram-accusatif",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Je lis un livre. »",
    question: "Я чита́ю ___.",
    options: ["кни́га", "кни́гу", "кни́ге", "кни́ги"],
    correctIndex: 1,
    explain: "Complément d'objet direct → accusatif : кни́га → кни́гу.",
  },
  {
    id: "a1-gram-est",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « J'ai un frère. »",
    question: "У меня́ ___ брат.",
    options: ["есть", "нет", "быть", "бу́ду"],
    correctIndex: 0,
    explain: "La possession se dit «у меня́ есть» + nominatif — le russe n'a pas de verbe « avoir ».",
  },
  {
    id: "a1-gram-gde",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Où habites-tu ? »",
    question: "___ ты живёшь?",
    options: ["Кто", "Что", "Где", "Когда́"],
    correctIndex: 2,
    explain: "«Где» = où. «Когда́» = quand, «Кто» = qui, «Что» = quoi.",
  },

  {
    id: "a1-lex-voda",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "вода́",
    options: ["pain", "eau", "lait", "thé"],
    correctIndex: 1,
    explain: "«вода́» = eau. «молоко́» = lait, «чай» = thé.",
  },
  {
    id: "a1-lex-segodnya",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie cet adverbe ?",
    question: "сего́дня",
    options: ["hier", "demain", "aujourd'hui", "toujours"],
    correctIndex: 2,
    explain: "«сего́дня» = aujourd'hui. «вчера́» = hier, «за́втра» = demain.",
  },
  {
    id: "a1-lex-khorosho",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "хорошо́",
    options: ["mal", "bien", "beaucoup", "peu"],
    correctIndex: 1,
    explain: "«хорошо́» = bien. «пло́хо» = mal.",
  },
  {
    id: "a1-mor-govorish",
    domain: "morphologie",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Tu parles français ? »",
    question: "Ты ___ по-францу́зски?",
    options: ["говорю́", "говори́шь", "говори́т", "говоря́т"],
    correctIndex: 1,
    explain: "2e personne du singulier : говори́шь. La terminaison -ишь marque le « tu ».",
  },
  {
    id: "a1-syn-kopula",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Comment dit-on « Il est étudiant » ?",
    question: "Il est étudiant.",
    options: ["Он есть студе́нт.", "Он студе́нт.", "Он быть студе́нт.", "Он э́то студе́нт."],
    correctIndex: 1,
    explain:
      "Au présent, le russe n'emploie pas de verbe « être » : on juxtapose simplement le sujet et l'attribut.",
  },
  {
    id: "a1-syn-chto",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Qu'est-ce que c'est ? »",
    question: "___ э́то?",
    options: ["Кто", "Что", "Где", "Как"],
    correctIndex: 1,
    explain: "«Что» interroge sur une chose, «Кто» sur une personne.",
  },
  {
    id: "a1-cas-na-stole",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Le livre est sur la table. »",
    question: "Кни́га ___ столе́.",
    options: ["в", "на", "из", "под"],
    correctIndex: 1,
    explain: "Sur une surface : «на» + prépositionnel (на столе́). «в» servirait pour l'intérieur.",
  },
  {
    id: "a1-cas-acc-inanime",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Je vois une maison. »",
    question: "Я ви́жу ___.",
    options: ["дом", "до́ма", "до́му", "до́мом"],
    correctIndex: 0,
    explain:
      "Pour un masculin INANIMÉ, l'accusatif est identique au nominatif : дом. C'est l'animé qui prend la forme du génitif (ви́жу бра́та).",
  },

  // ─── Palier 2 · A2 — Базовый уровень ─────────────────────────────
  {
    id: "a2-gram-passe",
    domain: "morphologie",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Hier, Anna est allée au cinéma. »",
    question: "Вчера́ А́нна ___ в кино́.",
    options: ["ходи́л", "ходи́ла", "ходи́ли", "ходи́ть"],
    correctIndex: 1,
    explain: "Au passé, le verbe s'accorde en genre avec le sujet : А́нна (fém.) → ходи́ла.",
  },
  {
    id: "a2-gram-futur",
    domain: "morphologie",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Demain je vais travailler. »",
    question: "За́втра я ___ рабо́тать.",
    options: ["был", "бу́ду", "бы", "быть"],
    correctIndex: 1,
    explain: "Futur imperfectif : бу́ду + infinitif.",
  },
  {
    id: "a2-gram-genitif-net",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Je n'ai pas le temps. »",
    question: "У меня́ нет ___.",
    options: ["вре́мя", "вре́мени", "вре́менем", "времена́"],
    correctIndex: 1,
    explain: "«нет» exige toujours le génitif : вре́мя → вре́мени.",
  },
  {
    id: "a2-gram-genitif-u",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Mon frère a une voiture. »",
    question: "___ есть маши́на.",
    options: ["Мой брат", "У мой брат", "У моего́ бра́та", "Моему́ бра́ту"],
    correctIndex: 2,
    explain: "«у» + génitif pour le possesseur : у моего́ бра́та.",
  },
  {
    id: "a2-gram-datif-nravitsya",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'aime cette musique. »",
    question: "___ нра́вится э́та му́зыка.",
    options: ["Я", "Меня́", "Мне", "Мной"],
    correctIndex: 2,
    explain: "«нра́виться» met celui qui aime au datif : мне нра́вится (littéralement « ça me plaît »).",
  },
  {
    id: "a2-gram-direction",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Chaque matin je vais à l'école. »",
    question: "Ка́ждое у́тро я иду́ ___.",
    options: ["в шко́ле", "в шко́лу", "из шко́лы", "шко́лой"],
    correctIndex: 1,
    explain: "Déplacement vers un lieu : в + accusatif (в шко́лу). Le lieu où l'on est prend в + prépositionnel.",
  },
  {
    id: "a2-gram-lieu",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Mon frère travaille à l'école. »",
    question: "Мой брат рабо́тает ___.",
    options: ["в шко́лу", "в шко́ле", "на шко́лу", "шко́лы"],
    correctIndex: 1,
    explain: "Lieu où l'on se trouve : в + prépositionnel (в шко́ле), sans mouvement.",
  },
  {
    id: "a2-gram-numeral",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'ai deux sœurs. »",
    question: "У меня́ две ___.",
    options: ["сестра́", "сестры́", "сестёр", "сёстрам"],
    correctIndex: 1,
    explain: "Après 2, 3 et 4 : génitif singulier → две сестры́. Après 5 et plus : génitif pluriel (пять сестёр).",
  },
  {
    id: "a2-gram-motion",
    domain: "mouvement",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « D'habitude je vais au travail en bus. »",
    question: "Обы́чно я ___ на рабо́ту на авто́бусе.",
    options: ["иду́", "хожу́", "е́ду", "е́зжу"],
    correctIndex: 3,
    explain:
      "Habitude (обы́чно) + véhicule → е́зжу. «хожу́» serait à pied, «е́ду»/«иду́» décrivent un trajet en cours.",
  },
  {
    id: "a2-gram-aspect-duree",
    domain: "aspect",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Hier j'ai écrit une lettre toute la soirée. »",
    question: "Вчера́ я весь ве́чер ___ письмо́.",
    options: ["писа́л", "написа́л", "пишу́", "напишу́"],
    correctIndex: 0,
    explain:
      "«весь ве́чер» décrit un processus qui dure → imperfectif (писа́л). Le perfectif «написа́л» insisterait sur le résultat atteint.",
  },
  {
    id: "a2-gram-comparatif",
    domain: "syntaxe",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Moscou est plus grande que Saint-Pétersbourg. »",
    question: "Москва́ ___, чем Петербу́рг.",
    options: ["больша́я", "большо́й", "бо́льше", "са́мая больша́я"],
    correctIndex: 2,
    explain: "Comparatif simple : бо́льше. La construction est «бо́льше, чем…».",
  },
  {
    id: "a2-lex-opazdyvat",
    domain: "lexique",
    tier: 2,
    skill: "lexique",
    prompt: "Que signifie ce verbe ?",
    question: "опа́здывать",
    options: ["se dépêcher", "être en retard", "attendre", "partir"],
    correctIndex: 1,
    explain: "«опа́здывать / опозда́ть» = être en retard. «спе́шить» = se dépêcher.",
  },

  {
    id: "a2-mou-metro",
    domain: "mouvement",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Chaque matin je vais au travail en métro. »",
    question: "Ка́ждое у́тро я ___ на рабо́ту на метро́.",
    options: ["иду́", "е́ду", "хожу́", "е́зжу"],
    correctIndex: 3,
    explain:
      "Habitude (ка́ждое у́тро) + véhicule → е́зжу. «е́ду» décrirait le trajet en cours, «хожу́» un déplacement à pied.",
  },
  {
    id: "a2-mou-seychas",
    domain: "mouvement",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « En ce moment, il rentre à la maison (à pied). »",
    question: "Сейча́с он ___ домо́й.",
    options: ["идёт", "хо́дит", "е́здит", "ходи́л"],
    correctIndex: 0,
    explain:
      "Un trajet en cours, dans une direction → unidirectionnel идёт. «хо́дит» dirait une habitude.",
  },
  {
    id: "a2-cas-age",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'ai vingt ans. »",
    question: "___ два́дцать лет.",
    options: ["Я", "Меня́", "Мне", "Мной"],
    correctIndex: 2,
    explain: "L'âge se dit au datif : мне два́дцать лет (littéralement « à moi vingt ans »).",
  },
  {
    id: "a2-cas-partitif",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Donne-moi un peu d'eau. »",
    question: "Дай мне немно́го ___.",
    options: ["вода́", "во́ду", "воды́", "водо́й"],
    correctIndex: 2,
    explain: "«немно́го» est une expression de quantité : elle exige le génitif — немно́го воды́.",
  },
  {
    id: "a2-cas-acc-anime",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Je vois mon frère. »",
    question: "Я ви́жу ___.",
    options: ["брат", "бра́та", "бра́ту", "бра́том"],
    correctIndex: 1,
    explain:
      "Masculin ANIMÉ : l'accusatif emprunte la forme du génitif → бра́та. Comparer avec « ви́жу дом » (inanimé).",
  },
  {
    id: "a2-asp-uzhe",
    domain: "aspect",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'ai déjà vu ce film. »",
    question: "Я уже́ ___ э́тот фильм.",
    options: ["смотре́л", "посмотре́л", "смотрю́", "бу́ду смотре́ть"],
    correctIndex: 1,
    explain:
      "«уже́» pointe un résultat atteint → perfectif посмотре́л. L'imperfectif «смотре́л» décrirait l'activité, sans dire qu'elle a abouti.",
  },
  {
    id: "a2-mor-byla",
    domain: "morphologie",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Elle était à la maison hier. »",
    question: "Вчера́ она́ ___ до́ма.",
    options: ["был", "была́", "бы́ло", "бы́ли"],
    correctIndex: 1,
    explain: "Le passé de «быть» s'accorde en genre : она́ была́.",
  },
  {
    id: "a2-lex-dorogo",
    domain: "lexique",
    tier: 2,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "до́рого",
    options: ["bon marché", "cher", "gratuit", "rapide"],
    correctIndex: 1,
    explain: "«до́рого» = cher. «дёшево» = bon marché.",
  },

  // ─── Palier 3 · B1 — ТРКИ-1 ──────────────────────────────────────
  {
    id: "b1-gram-instr-metier",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Mon père travaille comme médecin. »",
    question: "Мой оте́ц рабо́тает ___.",
    options: ["врач", "врача́", "врачо́м", "врачу́"],
    correctIndex: 2,
    explain: "«рабо́тать» + instrumental pour la profession : рабо́тает врачо́м.",
  },
  {
    id: "b1-gram-instr-avec",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Je vais au cinéma avec un ami. »",
    question: "Я иду́ в кино́ с ___.",
    options: ["друг", "дру́га", "дру́гом", "дру́гу"],
    correctIndex: 2,
    explain: "La préposition «с» (avec) exige l'instrumental : с дру́гом.",
  },
  {
    id: "b1-gram-aspect-delai",
    domain: "aspect",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'ai lu ce livre en deux jours. »",
    question: "Я ___ э́ту кни́гу за два дня.",
    options: ["чита́л", "прочита́л", "чита́ю", "бу́ду чита́ть"],
    correctIndex: 1,
    explain:
      "«за + durée» indique le temps qu'il a fallu pour ALLER AU BOUT → perfectif : прочита́л.",
  },
  {
    id: "b1-gram-chtoby",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Je suis venu pour t'aider. »",
    question: "Я пришёл, ___ тебе́ помо́чь.",
    options: ["что", "что́бы", "потому́ что", "е́сли"],
    correctIndex: 1,
    explain: "But + infinitif : что́бы. «потому́ что» donne la cause, pas le but.",
  },
  {
    id: "b1-gram-kotoryy",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « La fille que j'ai rencontrée hier est ma sœur. »",
    question: "Де́вушка, ___ я встре́тил вчера́, — моя́ сестра́.",
    options: ["кото́рая", "кото́рую", "кото́рой", "кото́рого"],
    correctIndex: 1,
    explain:
      "«кото́рый» prend le genre de son antécédent (де́вушка, fém.) et le cas de sa fonction dans la subordonnée — ici objet direct → кото́рую.",
  },
  {
    id: "b1-gram-motion-prefixe",
    domain: "mouvement",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il est entré dans la pièce et s'est assis. »",
    question: "Он ___ в ко́мнату и сел.",
    // «пришёл» écarté des distracteurs : «прийти в комнату» se dit aussi,
    // l'item n'aurait plus eu une seule réponse défendable. Les quatre
    // options opposent maintenant des préfixes de direction incompatibles.
    options: ["вошёл", "вы́шел", "перешёл", "отошёл"],
    correctIndex: 0,
    explain:
      "Le préfixe в(о)- marque l'entrée : войти́ в ко́мнату. вы- = sortir de, пере́- = traverser, от- = s'écarter.",
  },
  {
    id: "b1-gram-conditionnel",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Si j'avais le temps, je t'aiderais. »",
    question: "Е́сли бы у меня́ бы́ло вре́мя, я ___ тебе́.",
    options: ["помогу́", "помо́г бы", "помога́л", "помо́чь"],
    correctIndex: 1,
    explain: "L'irréel se construit avec «бы» + passé dans LES DEUX propositions : е́сли бы… помо́г бы.",
  },
  {
    id: "b1-gram-genitif-pluriel",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il y a beaucoup d'étudiants dans notre ville. »",
    question: "В на́шем го́роде мно́го ___.",
    options: ["студе́нт", "студе́нты", "студе́нтов", "студе́нтам"],
    correctIndex: 2,
    explain: "«мно́го» exige le génitif pluriel : студе́нтов.",
  },
  {
    id: "b1-gram-datif-verbe",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'aide souvent ma mère. »",
    question: "Я ча́сто помога́ю ___.",
    options: ["ма́му", "ма́ме", "ма́мой", "ма́мы"],
    correctIndex: 1,
    explain:
      "«помога́ть» se construit avec le datif, là où le français a un objet direct : помога́ю ма́ме.",
  },
  {
    id: "b1-gram-reflexif",
    domain: "morphologie",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Le matin je me réveille à sept heures. »",
    question: "У́тром я ___ в семь часо́в.",
    options: ["просыпа́ю", "просыпа́юсь", "просыпа́ется", "просну́ть"],
    correctIndex: 1,
    explain: "Verbe pronominal en -ся, 1re personne : просыпа́юсь.",
  },
  {
    id: "b1-gram-superlatif",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « C'est le film le plus intéressant de l'année. »",
    question: "Э́то ___ интере́сный фильм го́да.",
    options: ["бо́лее", "са́мый", "о́чень", "тако́й"],
    correctIndex: 1,
    explain: "Superlatif : са́мый + adjectif. «бо́лее» sert au comparatif (plus…que).",
  },
  {
    id: "b1-lex-vnezapno",
    domain: "lexique",
    tier: 3,
    skill: "lexique",
    prompt: "Que signifie cet adverbe ?",
    question: "внеза́пно",
    options: ["lentement", "soudain", "souvent", "à peine"],
    correctIndex: 1,
    explain: "«внеза́пно» = soudainement, tout à coup.",
  },

  {
    id: "b1-mou-vyshel",
    domain: "mouvement",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il est sorti de la pièce et a fermé la porte. »",
    question: "Он ___ из ко́мнаты и закры́л дверь.",
    options: ["вошёл", "вы́шел", "перешёл", "подошёл"],
    correctIndex: 1,
    explain:
      "« из » impose le préfixe вы- (sortir de l'intérieur). в(о)- serait l'entrée, под- l'approche.",
  },
  {
    id: "b1-mou-podoshla",
    domain: "mouvement",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Elle s'est approchée de la fenêtre. »",
    question: "Она́ подошла́ ___ окну́.",
    options: ["к", "до", "у", "на"],
    correctIndex: 0,
    explain: "Le préfixe под- appelle « к » + datif : подойти́ к окну́.",
  },
  {
    id: "b1-cas-instr-moyen",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'écris au stylo. »",
    question: "Я пишу́ ___.",
    options: ["ру́чка", "ру́чку", "ру́чкой", "ру́чке"],
    correctIndex: 2,
    explain:
      "L'instrument se met à l'instrumental, sans préposition : пишу́ ру́чкой. C'est ce sens qui donne son nom au cas.",
  },
  {
    id: "b1-cas-prep-rossii",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'habite en Russie. »",
    question: "Я живу́ в ___.",
    options: ["Росси́я", "Росси́ю", "Росси́и", "Росси́ей"],
    correctIndex: 2,
    explain:
      "Lieu où l'on est : в + prépositionnel. Un radical en -и (Росси́я) donne -ии → в Росси́и.",
  },
  {
    id: "b1-asp-napishu",
    domain: "aspect",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Demain j'écrirai la lettre et je l'enverrai. »",
    question: "За́втра я ___ письмо́ и отпра́влю его́.",
    options: ["напишу́", "бу́ду писа́ть", "пишу́", "писа́л"],
    correctIndex: 0,
    explain:
      "Deux actions qui s'enchaînent, chacune menée à son terme → perfectif напишу́. « бу́ду писа́ть » décrirait une activité sans fin marquée.",
  },
  {
    id: "b1-syn-chto-indirect",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il a dit qu'il viendrait demain. »",
    question: "Он сказа́л, ___ придёт за́втра.",
    options: ["что", "что́бы", "е́сли", "ли"],
    correctIndex: 0,
    explain:
      "Discours indirect déclaratif : « что ». « что́бы » introduirait un but, « ли » une question.",
  },
  {
    id: "b1-syn-luchshe",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il parle russe mieux que moi. »",
    question: "Он говори́т по-ру́сски ___, чем я.",
    options: ["хорошо́", "лу́чше", "хоро́ший", "са́мый хоро́ший"],
    correctIndex: 1,
    explain: "Comparatif irrégulier de « хорошо́ » : лу́чше. La construction est « лу́чше, чем… ».",
  },
  {
    id: "b1-lex-vnimatelno",
    domain: "lexique",
    tier: 3,
    skill: "lexique",
    prompt: "Que signifie cet adverbe ?",
    question: "внима́тельно",
    options: ["rapidement", "attentivement", "rarement", "bruyamment"],
    correctIndex: 1,
    explain: "« внима́тельно » = attentivement, de « внима́ние » (attention).",
  },

  // ─── Palier 4 · B2 — ТРКИ-2 ──────────────────────────────────────
  {
    id: "b2-gram-participe-actif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « L'étudiant qui lit à la bibliothèque est mon ami. »",
    question: "Студе́нт, ___ в библиоте́ке, — мой друг.",
    options: ["чита́ет", "чита́ющий", "чита́емый", "чита́я"],
    correctIndex: 1,
    explain:
      "Participe présent actif : чита́ющий (celui qui lit). «чита́емый» est passif, «чита́я» est un gérondif.",
  },
  {
    id: "b2-gram-participe-passif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Le livre écrit par Tolstoï est devenu un classique. »",
    question: "Кни́га, ___ То́лстым, ста́ла кла́ссикой.",
    options: ["написа́л", "написа́вший", "напи́санная", "написа́в"],
    correctIndex: 2,
    explain:
      "Participe passé passif, accordé avec кни́га (fém.) : напи́санная. L'agent se met à l'instrumental (То́лстым).",
  },
  {
    id: "b2-gram-gerondif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « En rentrant chez moi, j'ai croisé un vieil ami. »",
    question: "___ домо́й, я встре́тил ста́рого дру́га.",
    options: ["Возвраща́юсь", "Возвраща́ясь", "Возвраща́лся", "Возвраще́ние"],
    correctIndex: 1,
    explain:
      "Gérondif imperfectif : возвраща́ясь — l'action accompagne celle du verbe principal, même sujet.",
  },
  {
    id: "b2-gram-regime-interesovatsya",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il s'intéresse depuis longtemps à l'histoire. »",
    question: "Он давно́ интересу́ется ___.",
    options: ["исто́рию", "исто́рии", "исто́рией", "об исто́рии"],
    correctIndex: 2,
    explain: "«интересова́ться» se construit avec l'instrumental : интересу́ется исто́рией.",
  },
  {
    id: "b2-gram-regime-izbegat",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il évite les conflits. »",
    question: "Он избега́ет ___.",
    options: ["конфли́кты", "конфли́ктов", "конфли́ктам", "конфли́ктами"],
    correctIndex: 1,
    explain: "«избега́ть» exige le génitif : избега́ет конфли́ктов.",
  },
  {
    id: "b2-gram-regime-udelyat",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il accorde beaucoup d'attention aux détails. »",
    question: "Он уделя́ет мно́го внима́ния ___.",
    options: ["дета́ли", "дета́лей", "дета́лям", "дета́лями"],
    correctIndex: 2,
    explain: "«уделя́ть внима́ние» + datif : уделя́ет внима́ние дета́лям.",
  },
  {
    id: "b2-gram-passif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Cette maison a été construite au siècle dernier. »",
    question: "Э́тот дом ___ в про́шлом ве́ке.",
    options: ["стро́ил", "постро́ил", "был постро́ен", "стро́ится"],
    correctIndex: 2,
    explain:
      "Passif au passé : был + participe passé passif court (был постро́ен). «стро́ится» est un présent passif.",
  },
  {
    id: "b2-gram-nesmotrya",
    domain: "syntaxe",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Bien qu'il fût tard, nous avons continué. »",
    question: "___ на то что бы́ло по́здно, мы продо́лжили рабо́ту.",
    options: ["Несмотря́", "Благодаря́", "Вопреки́", "Из-за"],
    correctIndex: 0,
    explain:
      "Conjonction complexe «несмотря́ на то что» = bien que. «благодаря́» = grâce à, «из-за» = à cause de.",
  },
  {
    id: "b2-gram-li",
    domain: "syntaxe",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il a demandé si je viendrais demain. »",
    question: "Он спроси́л, приду́ ___ я за́втра.",
    options: ["что", "е́сли", "ли", "что́бы"],
    correctIndex: 2,
    explain:
      "Interrogation indirecte totale : particule «ли» placée après le mot sur lequel porte la question. «е́сли» ne sert qu'à l'hypothèse.",
  },
  {
    id: "b2-gram-derivation",
    domain: "lexique",
    tier: 4,
    skill: "grammaire",
    prompt: "Quel mot désigne la PERSONNE qui exerce l'action de « преподава́ть » (enseigner) ?",
    question: "преподава́ть → ?",
    options: ["преподава́ние", "преподава́тель", "преподава́тельский", "пре́поданный"],
    correctIndex: 1,
    explain:
      "Suffixe -тель = agent : преподава́тель (enseignant). «преподава́ние» est l'action, «-ский» un adjectif.",
  },
  {
    id: "b2-lex-sokrashchat",
    domain: "lexique",
    tier: 4,
    skill: "lexique",
    prompt: "Que signifie ce verbe ?",
    question: "сокраща́ть",
    options: ["augmenter", "réduire", "reporter", "remplacer"],
    correctIndex: 1,
    explain: "«сокраща́ть / сократи́ть» = réduire, raccourcir (d'où «сокраще́ние» : réduction, abréviation).",
  },
  {
    id: "b2-lex-uverennyy",
    domain: "lexique",
    tier: 4,
    skill: "lexique",
    prompt: "Que signifie cet adjectif ?",
    question: "уве́ренный",
    options: ["inquiet", "sûr, assuré", "surpris", "prudent"],
    correctIndex: 1,
    explain: "«уве́ренный» = sûr de soi, assuré ; «быть уве́ренным в чём-то» = être sûr de quelque chose.",
  },

  {
    id: "b2-par-gerondif-perf",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Ayant terminé son travail, il est rentré. »",
    question: "___ рабо́ту, он пошёл домо́й.",
    options: ["Зака́нчивая", "Зако́нчив", "Зако́нчил", "Зака́нчивать"],
    correctIndex: 1,
    explain:
      "Gérondif PERFECTIF en -в : l'action est achevée avant celle du verbe principal. « Зака́нчивая » (imperfectif) la dirait simultanée.",
  },
  {
    id: "b2-par-participe-passe-actif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « L'homme qui nous a aidés hier est médecin. »",
    question: "Челове́к, ___ нам вчера́, — врач.",
    options: ["помога́ющий", "помога́вший", "помога́я", "помога́емый"],
    correctIndex: 1,
    explain:
      "Participe PASSÉ actif en -вший : l'action est révolue (вчера́). « помога́ющий » serait au présent.",
  },
  {
    id: "b2-par-court-passif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « La porte est fermée. »",
    question: "Дверь ___.",
    options: ["закры́та", "закры́тая", "закрыва́ет", "закрыва́ется"],
    correctIndex: 0,
    explain:
      "Participe passif COURT, employé comme attribut : дверь закры́та. La forme longue « закры́тая » serait épithète (закры́тая дверь).",
  },
  {
    id: "b2-cas-zanimatsya",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il fait du sport. »",
    question: "Он занима́ется ___.",
    options: ["спорт", "спо́рта", "спо́ртом", "спо́рту"],
    correctIndex: 2,
    explain: "« занима́ться » se construit avec l'instrumental : занима́ется спо́ртом.",
  },
  {
    id: "b2-cas-gorditsya",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Je suis fier de mon fils. »",
    question: "Я горжу́сь ___.",
    options: ["сын", "сы́на", "сы́ну", "сы́ном"],
    correctIndex: 3,
    explain: "« горди́ться » + instrumental : горжу́сь сы́ном.",
  },
  {
    id: "b2-asp-imperatif-negatif",
    domain: "aspect",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Ne ferme pas la porte ! »",
    question: "Не ___ дверь!",
    options: ["закро́й", "закрыва́й", "закры́ть", "закры́л"],
    correctIndex: 1,
    explain:
      "À l'impératif NÉGATIF, le russe emploie l'imperfectif : не закрыва́й. Le perfectif « не закро́й » serait une mise en garde contre un accident, pas une interdiction.",
  },
  {
    id: "b2-syn-tak-kak",
    domain: "syntaxe",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Comme il était en retard, nous avons commencé sans lui. »",
    question: "___ он опозда́л, мы на́чали без него́.",
    options: ["Так как", "Что́бы", "Хотя́", "Е́сли"],
    correctIndex: 0,
    explain: "« Так как » introduit la cause. « Хотя́ » marquerait la concession, « Е́сли » l'hypothèse.",
  },
  {
    id: "b2-lex-osushchestvit",
    domain: "lexique",
    tier: 4,
    skill: "lexique",
    prompt: "Que signifie ce verbe ?",
    question: "осуществи́ть",
    options: ["annuler", "réaliser, mettre en œuvre", "envisager", "retarder"],
    correctIndex: 1,
    explain: "« осуществи́ть » = réaliser, concrétiser (осуществи́ть план : réaliser un plan).",
  },

  // ─── Palier 5 · C1 — ТРКИ-3 ──────────────────────────────────────
  {
    id: "c1-lex-shlyapa",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "де́ло в шля́пе",
    options: ["c'est un désastre", "c'est dans la poche", "on verra bien", "c'est très compliqué"],
    correctIndex: 1,
    explain: "«де́ло в шля́пе» = l'affaire est réglée, c'est dans la poche.",
  },
  {
    id: "c1-lex-baklushi",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "бить баклу́ши",
    options: ["travailler dur", "se disputer", "ne rien faire, paresser", "dire la vérité"],
    correctIndex: 2,
    explain: "«бить баклу́ши» = se tourner les pouces, ne rien faire.",
  },
  {
    id: "c1-lex-lomat-golovu",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "лома́ть го́лову",
    options: ["se creuser la tête", "perdre la mémoire", "se mettre en colère", "changer d'avis"],
    correctIndex: 0,
    explain: "«лома́ть го́лову над чем-то» = se casser la tête sur quelque chose.",
  },
  {
    id: "c1-gram-izza",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « À cause de la pluie, nous sommes restés à la maison. »",
    question: "___ дождя́ мы оста́лись до́ма.",
    options: ["Благодаря́", "Из-за", "Вопреки́", "Согла́сно"],
    correctIndex: 1,
    explain:
      "«из-за» + génitif introduit une cause NÉGATIVE ; «благодаря́» + datif une cause favorable (grâce à).",
  },
  {
    id: "c1-gram-svidetelstvovat",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Cela témoigne de problèmes sérieux. »",
    question: "Э́то свиде́тельствует ___ серьёзных пробле́мах.",
    options: ["о", "про", "за", "на"],
    correctIndex: 0,
    explain: "«свиде́тельствовать о чём-то» + prépositionnel. «про» existe mais reste familier et régit l'accusatif.",
  },
  {
    id: "c1-gram-prenebregat",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Il néglige les règles. »",
    question: "Он пренебрега́ет ___.",
    options: ["пра́вила", "пра́вил", "пра́вилам", "пра́вилами"],
    correctIndex: 3,
    explain: "«пренебрега́ть» exige l'instrumental : пренебрега́ет пра́вилами.",
  },
  {
    id: "c1-gram-chem-tem",
    domain: "syntaxe",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Plus il travaillait, plus il se fatiguait. »",
    question: "Чем бо́льше он рабо́тал, ___ сильне́е он устава́л.",
    options: ["так", "тем", "что", "как"],
    correctIndex: 1,
    explain: "Corrélation de proportion : «чем… тем…» (plus… plus…).",
  },
  {
    id: "c1-gram-aspect-vspomnit",
    domain: "aspect",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Je n'arrive absolument pas à me rappeler son numéro. »",
    question: "Я ника́к не могу́ ___ его́ но́мер телефо́на.",
    options: ["вспомина́ть", "вспо́мнить", "по́мнить", "запомина́ть"],
    correctIndex: 1,
    explain:
      "«ника́к не могу́» vise un résultat qu'on n'atteint pas → perfectif вспо́мнить. «по́мнить» = garder en mémoire, état continu.",
  },
  {
    id: "c1-gram-aspect-pytatsya",
    domain: "aspect",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « J'ai longtemps essayé de le joindre. »",
    question: "Я до́лго ___ ему́ дозвони́ться.",
    options: ["пыта́лся", "попыта́лся", "попро́бую", "стал"],
    correctIndex: 0,
    explain: "«до́лго» décrit une tentative qui dure → imperfectif пыта́лся. Le perfectif «попыта́лся» serait ponctuel.",
  },
  {
    id: "c1-lex-registre",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Quel équivalent de « сейча́с » appartient au registre écrit et soutenu ?",
    question: "сейча́с → ?",
    options: ["щас", "в настоя́щее вре́мя", "пото́м", "давно́"],
    correctIndex: 1,
    explain:
      "«в настоя́щее вре́мя» est la formule administrative/écrite. «щас» est une forme orale relâchée, «пото́м» = ensuite.",
  },
  {
    id: "c1-lex-predvzyatyy",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cet adjectif ?",
    question: "предвзя́тый",
    options: ["prévoyant", "partial, biaisé", "prévisible", "prétentieux"],
    correctIndex: 1,
    explain: "«предвзя́тый» = partial, préconçu (предвзя́тое мне́ние : une opinion biaisée).",
  },
  {
    id: "c1-lex-obuslovlen",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette forme ?",
    question: "обусло́влен",
    options: ["conditionné, déterminé par", "obligatoire", "conclu", "supposé"],
    correctIndex: 0,
    explain: "«обусло́влен чем-то» = déterminé/conditionné par quelque chose — registre écrit et analytique.",
  },
  {
    id: "c1-lex-spustya-rukava",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "спустя́ рукава́",
    options: ["avec application", "à la va-vite, négligemment", "en cachette", "à contrecœur"],
    correctIndex: 1,
    explain:
      "« рабо́тать спустя́ рукава́ » = travailler par-dessus la jambe. L'image : les manches qu'on n'a pas retroussées.",
  },
  {
    id: "c1-lex-vodit-za-nos",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "води́ть за нос",
    options: ["mener en bateau", "prendre en charge", "suivre de près", "flatter"],
    correctIndex: 0,
    explain: "« води́ть кого́-то за нос » = tromper quelqu'un, le mener en bateau.",
  },
  {
    id: "c1-lex-tem-ne-menee",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette locution ?",
    question: "тем не ме́нее",
    options: ["d'autant plus", "néanmoins", "en particulier", "par conséquent"],
    correctIndex: 1,
    explain: "« тем не ме́нее » = néanmoins, toutefois — registre écrit et argumentatif.",
  },
  {
    id: "c1-lex-daby",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Quel est l'équivalent neutre et courant de « да́бы » ?",
    question: "да́бы → ?",
    options: ["что́бы", "потому́ что", "хотя́", "е́сли"],
    correctIndex: 0,
    explain:
      "« да́бы » est un archaïsme littéraire pour « что́бы » (afin que). Le reconnaître relève du registre, pas du sens.",
  },
  {
    id: "c1-syn-chto-by-ni",
    domain: "syntaxe",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Quoi qu'il dise, je ne le crois pas. »",
    question: "___ бы он ни говори́л, я ему́ не ве́рю.",
    options: ["Что", "Как", "Кто", "Где"],
    correctIndex: 0,
    explain:
      "Concessive indéfinie : mot interrogatif + « бы… ни » → « что бы он ни говори́л » = quoi qu'il dise.",
  },
  {
    id: "c1-syn-ne-tolko",
    domain: "syntaxe",
    tier: 5,
    skill: "grammaire",
    prompt:
      "Complète : « Non seulement il est arrivé en retard, mais il a aussi oublié ses papiers. »",
    question: "Он не то́лько опозда́л, ___ и забы́л докуме́нты.",
    options: ["а", "но", "и́ли", "да"],
    correctIndex: 1,
    explain: "Corrélation figée : « не то́лько… но и… ».",
  },
  {
    id: "c1-cas-protivorechit",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Cela contredit les faits. »",
    question: "Э́то противоре́чит ___.",
    options: ["фа́кты", "фа́ктов", "фа́ктам", "фа́ктами"],
    correctIndex: 2,
    explain: "« противоре́чить » se construit avec le datif : противоре́чит фа́ктам.",
  },
  {
    id: "c1-asp-poglyadyval",
    domain: "aspect",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Il ne cessait de jeter des coups d'œil par la fenêtre. »",
    question: "Он то и де́ло ___ в окно́.",
    options: ["посмотре́л", "погля́дывал", "взгляну́л", "гляде́ть"],
    correctIndex: 1,
    explain:
      "« то и де́ло » marque la répétition : imperfectif à valeur itérative et atténuée, погля́дывал. Les perfectifs « посмотре́л » et « взгляну́л » seraient ponctuels.",
  },
];

export function questionsForTier(tier: number): LevelQuestion[] {
  return LEVEL_QUESTIONS.filter((q) => q.tier === tier);
}

export function getQuestion(id: string): LevelQuestion | undefined {
  return LEVEL_QUESTIONS.find((q) => q.id === id);
}
