import { CefrLevel } from "@/lib/supabase/types";

/**
 * Banque d'items du test de placement.
 *
 * Calibrage : chaque palier reprend les descripteurs du référentiel ТРКИ /
 * TORFL, le standard officiel du russe langue étrangère, aligné sur le CECR :
 *
 *   1 · A1 — Элементарный : présent, у меня есть, prépositionnel de lieu,
 *            accusatif d'objet direct, possessifs, mots interrogatifs,
 *            lexique du quotidien.
 *   2 · A2 — Базовый : passé et futur, génitif après нет / у, datif avec
 *            нравиться, opposition lieu (в + prép.) / direction (в + acc.),
 *            accord après 2-4, verbes de déplacement идти/ходить/ехать.
 *   3 · B1 — ТРКИ-1 : système casuel complet dont l'instrumental, aspect en
 *            contexte, verbes de déplacement préfixés, subordonnées
 *            (который, чтобы), conditionnel en бы, comparatif/superlatif.
 *   4 · B2 — ТРКИ-2 : participes actifs et passifs, gérondifs, passif,
 *            régime verbal (интересоваться + instr., избегать + gén.,
 *            уделять внимание + dat.), conjonctions complexes, discours
 *            indirect en ли, dérivation.
 *   5 · C1 — ТРКИ-3 : phraséologie, registre, régimes rares, nuances
 *            aspectuelles, corrélations syntaxiques (чем… тем…).
 *
 * Règles de rédaction, pour que le test MESURE au lieu de piéger :
 * - un item = une compétence, testée en contexte (phrase à trou), pas de
 *   question métalinguistique du type « quel est le genre de ce mot ? » ;
 * - une seule réponse défendable : les items dont deux options se disent
 *   réellement en russe ont été écartés (ex. «ушёл/вышел из дома») ;
 * - les distracteurs sont des erreurs plausibles à ce niveau (mauvais cas,
 *   mauvais aspect), pas du remplissage absurde ;
 * - l'explication enseigne la règle, elle ne se contente pas de donner la
 *   réponse.
 */

export type LevelSkill = "grammaire" | "lexique";

/**
 * Domaine grammatical de l'item — sert au RAPPORT du test, là où `skill` sert
 * seulement à équilibrer la composition d'un bloc.
 *
 * C'est ce découpage qui permet de dire « tu valides B1 ; il t'a manqué les
 * participes et le régime verbal » au lieu d'un simple niveau. Il recoupe
 * volontairement les modules de l'app : un domaine faible qui a son module
 * (cas, mouvement) renvoie vers un entraînement, un domaine faible qui n'en
 * a pas (aspect, participes) est une limite connue du programme.
 */
export type LevelDomain =
  | "lexique"
  | "morphologie"
  | "cas"
  | "aspect"
  | "mouvement"
  | "syntaxe"
  | "participes";

export const DOMAIN_LABEL: Record<LevelDomain, string> = {
  lexique: "Vocabulaire",
  morphologie: "Formes et accords",
  cas: "Cas et rection",
  aspect: "Aspect verbal",
  mouvement: "Verbes de mouvement",
  syntaxe: "Syntaxe",
  participes: "Participes et gérondifs",
};

/** Domaines qui ont un module d'entraînement dans l'app. */
export const DOMAIN_PRACTICE: Partial<Record<LevelDomain, { href: string; label: string }>> = {
  cas: { href: "/cases", label: "Module Cas" },
  mouvement: { href: "/motion", label: "Module Verbes de mouvement" },
  aspect: { href: "/aspect", label: "Module Aspect" },
  participes: { href: "/participles", label: "Module Participes" },
  lexique: { href: "/vocabulary", label: "Module Vocabulaire" },
};

export interface LevelQuestion {
  id: string;
  tier: number; // 1 (A1) → 5 (C1)
  skill: LevelSkill;
  domain: LevelDomain;
  prompt: string; // consigne en français
  question: string; // le contenu russe
  options: string[];
  correctIndex: number;
  explain: string;
}

// Un palier par niveau CEFR au-dessus du plancher A0 (palier 1 non validé
// → grand débutant absolu).
export const TIER_LEVELS: CefrLevel[] = ["A1", "A2", "B1", "B2", "C1"];
export const MIN_TIER = 1;
export const MAX_TIER = TIER_LEVELS.length;

export function levelForTier(tier: number): CefrLevel {
  if (tier < MIN_TIER) return "A0";
  return TIER_LEVELS[Math.min(tier, MAX_TIER) - 1];
}

export const LEVEL_QUESTIONS: LevelQuestion[] = [
  // ─── Palier 1 · A1 — Элементарный уровень ────────────────────────
  {
    id: "a1-lex-spasibo",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "спасибо",
    options: ["bonjour", "merci", "au revoir", "s'il te plaît"],
    correctIndex: 1,
    explain: "«спасибо» = merci. «пожалуйста» = s'il te plaît / je t'en prie.",
  },
  {
    id: "a1-lex-dosvidaniya",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie cette formule ?",
    question: "До свидания!",
    options: ["Bonjour !", "Bonne nuit !", "Au revoir !", "Bienvenue !"],
    correctIndex: 2,
    explain: "«До свидания» = au revoir (littéralement « jusqu'à la revoyure »).",
  },
  {
    id: "a1-lex-khleb",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "хлеб",
    options: ["lait", "pain", "eau", "viande"],
    correctIndex: 1,
    explain: "«хлеб» = pain. «молоко» = lait, «вода» = eau, «мясо» = viande.",
  },
  {
    id: "a1-lex-ponedelnik",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Quel jour de la semaine est-ce ?",
    question: "понедельник",
    options: ["dimanche", "lundi", "mardi", "samedi"],
    correctIndex: 1,
    explain: "«понедельник» = lundi, le jour qui suit «неделя» au sens ancien de dimanche.",
  },
  {
    id: "a1-com-kakvaszovut",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que demande-t-on ?",
    question: "Как вас зовут?",
    options: [
      "Comment allez-vous ?",
      "Où habitez-vous ?",
      "Comment vous appelez-vous ?",
      "Quel âge avez-vous ?",
    ],
    correctIndex: 2,
    explain: "«Как вас зовут?» = comment vous appelle-t-on ? On répond «Меня зовут…».",
  },
  {
    id: "a1-com-kakdela",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie cette question ?",
    question: "Как дела?",
    options: ["Comment ça va ?", "Qu'est-ce que c'est ?", "Où es-tu ?", "Tu fais quoi ?"],
    correctIndex: 0,
    explain: "«Как дела?» = comment ça va ? (littéralement « comment vont les affaires »).",
  },
  {
    id: "a1-gram-govoryu",
    domain: "morphologie",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Je parle russe. »",
    question: "Я ___ по-русски.",
    options: ["говорить", "говорит", "говорю", "говорим"],
    correctIndex: 2,
    explain: "1re personne du singulier : говорю. «говорит» = il/elle parle, «говорим» = nous parlons.",
  },
  {
    id: "a1-gram-prep-lieu",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « J'habite à Moscou. »",
    question: "Я живу ___ Москве.",
    options: ["в", "на", "из", "с"],
    correctIndex: 0,
    explain: "Le lieu où l'on est se dit «в» + prépositionnel : в Москве.",
  },
  {
    id: "a1-gram-possessif",
    domain: "morphologie",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « C'est ma sœur. »",
    question: "Это ___ сестра.",
    options: ["мой", "моя", "моё", "мои"],
    correctIndex: 1,
    explain: "«сестра» est féminin : le possessif s'accorde → моя.",
  },
  {
    id: "a1-gram-accusatif",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Je lis un livre. »",
    question: "Я читаю ___.",
    options: ["книга", "книгу", "книге", "книги"],
    correctIndex: 1,
    explain: "Complément d'objet direct → accusatif : книга → книгу.",
  },
  {
    id: "a1-gram-est",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « J'ai un frère. »",
    question: "У меня ___ брат.",
    options: ["есть", "нет", "быть", "буду"],
    correctIndex: 0,
    explain: "La possession se dit «у меня есть» + nominatif — le russe n'a pas de verbe « avoir ».",
  },
  {
    id: "a1-gram-gde",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Où habites-tu ? »",
    question: "___ ты живёшь?",
    options: ["Кто", "Что", "Где", "Когда"],
    correctIndex: 2,
    explain: "«Где» = où. «Когда» = quand, «Кто» = qui, «Что» = quoi.",
  },

  {
    id: "a1-lex-voda",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "вода",
    options: ["pain", "eau", "lait", "thé"],
    correctIndex: 1,
    explain: "«вода» = eau. «молоко» = lait, «чай» = thé.",
  },
  {
    id: "a1-lex-segodnya",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie cet adverbe ?",
    question: "сегодня",
    options: ["hier", "demain", "aujourd'hui", "toujours"],
    correctIndex: 2,
    explain: "«сегодня» = aujourd'hui. «вчера» = hier, «завтра» = demain.",
  },
  {
    id: "a1-lex-khorosho",
    domain: "lexique",
    tier: 1,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "хорошо",
    options: ["mal", "bien", "beaucoup", "peu"],
    correctIndex: 1,
    explain: "«хорошо» = bien. «плохо» = mal.",
  },
  {
    id: "a1-mor-govorish",
    domain: "morphologie",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Tu parles français ? »",
    question: "Ты ___ по-французски?",
    options: ["говорю", "говоришь", "говорит", "говорят"],
    correctIndex: 1,
    explain: "2e personne du singulier : говоришь. La terminaison -ишь marque le « tu ».",
  },
  {
    id: "a1-syn-kopula",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Comment dit-on « Il est étudiant » ?",
    question: "Il est étudiant.",
    options: ["Он есть студент.", "Он студент.", "Он быть студент.", "Он это студент."],
    correctIndex: 1,
    explain:
      "Au présent, le russe n'emploie pas de verbe « être » : on juxtapose simplement le sujet et l'attribut.",
  },
  {
    id: "a1-syn-chto",
    domain: "syntaxe",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Qu'est-ce que c'est ? »",
    question: "___ это?",
    options: ["Кто", "Что", "Где", "Как"],
    correctIndex: 1,
    explain: "«Что» interroge sur une chose, «Кто» sur une personne.",
  },
  {
    id: "a1-cas-na-stole",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Le livre est sur la table. »",
    question: "Книга ___ столе.",
    options: ["в", "на", "из", "под"],
    correctIndex: 1,
    explain: "Sur une surface : «на» + prépositionnel (на столе). «в» servirait pour l'intérieur.",
  },
  {
    id: "a1-cas-acc-inanime",
    domain: "cas",
    tier: 1,
    skill: "grammaire",
    prompt: "Complète : « Je vois une maison. »",
    question: "Я вижу ___.",
    options: ["дом", "дома", "дому", "домом"],
    correctIndex: 0,
    explain:
      "Pour un masculin INANIMÉ, l'accusatif est identique au nominatif : дом. C'est l'animé qui prend la forme du génitif (вижу брата).",
  },

  // ─── Palier 2 · A2 — Базовый уровень ─────────────────────────────
  {
    id: "a2-gram-passe",
    domain: "morphologie",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Hier, Anna est allée au cinéma. »",
    question: "Вчера Анна ___ в кино.",
    options: ["ходил", "ходила", "ходили", "ходить"],
    correctIndex: 1,
    explain: "Au passé, le verbe s'accorde en genre avec le sujet : Анна (fém.) → ходила.",
  },
  {
    id: "a2-gram-futur",
    domain: "morphologie",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Demain je vais travailler. »",
    question: "Завтра я ___ работать.",
    options: ["был", "буду", "бы", "быть"],
    correctIndex: 1,
    explain: "Futur imperfectif : буду + infinitif.",
  },
  {
    id: "a2-gram-genitif-net",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Je n'ai pas le temps. »",
    question: "У меня нет ___.",
    options: ["время", "времени", "временем", "времена"],
    correctIndex: 1,
    explain: "«нет» exige toujours le génitif : время → времени.",
  },
  {
    id: "a2-gram-genitif-u",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Mon frère a une voiture. »",
    question: "___ есть машина.",
    options: ["Мой брат", "У мой брат", "У моего брата", "Моему брату"],
    correctIndex: 2,
    explain: "«у» + génitif pour le possesseur : у моего брата.",
  },
  {
    id: "a2-gram-datif-nravitsya",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'aime cette musique. »",
    question: "___ нравится эта музыка.",
    options: ["Я", "Меня", "Мне", "Мной"],
    correctIndex: 2,
    explain: "«нравиться» met celui qui aime au datif : мне нравится (littéralement « ça me plaît »).",
  },
  {
    id: "a2-gram-direction",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Chaque matin je vais à l'école. »",
    question: "Каждое утро я иду ___.",
    options: ["в школе", "в школу", "из школы", "школой"],
    correctIndex: 1,
    explain: "Déplacement vers un lieu : в + accusatif (в школу). Le lieu où l'on est prend в + prépositionnel.",
  },
  {
    id: "a2-gram-lieu",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Mon frère travaille à l'école. »",
    question: "Мой брат работает ___.",
    options: ["в школу", "в школе", "на школу", "школы"],
    correctIndex: 1,
    explain: "Lieu où l'on se trouve : в + prépositionnel (в школе), sans mouvement.",
  },
  {
    id: "a2-gram-numeral",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'ai deux sœurs. »",
    question: "У меня две ___.",
    options: ["сестра", "сестры", "сестёр", "сёстрам"],
    correctIndex: 1,
    explain: "Après 2, 3 et 4 : génitif singulier → две сестры. Après 5 et plus : génitif pluriel (пять сестёр).",
  },
  {
    id: "a2-gram-motion",
    domain: "mouvement",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « D'habitude je vais au travail en bus. »",
    question: "Обычно я ___ на работу на автобусе.",
    options: ["иду", "хожу", "еду", "езжу"],
    correctIndex: 3,
    explain:
      "Habitude (обычно) + véhicule → езжу. «хожу» serait à pied, «еду»/«иду» décrivent un trajet en cours.",
  },
  {
    id: "a2-gram-aspect-duree",
    domain: "aspect",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Hier j'ai écrit une lettre toute la soirée. »",
    question: "Вчера я весь вечер ___ письмо.",
    options: ["писал", "написал", "пишу", "напишу"],
    correctIndex: 0,
    explain:
      "«весь вечер» décrit un processus qui dure → imperfectif (писал). Le perfectif «написал» insisterait sur le résultat atteint.",
  },
  {
    id: "a2-gram-comparatif",
    domain: "syntaxe",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Moscou est plus grande que Saint-Pétersbourg. »",
    question: "Москва ___, чем Петербург.",
    options: ["большая", "большой", "больше", "самая большая"],
    correctIndex: 2,
    explain: "Comparatif simple : больше. La construction est «больше, чем…».",
  },
  {
    id: "a2-lex-opazdyvat",
    domain: "lexique",
    tier: 2,
    skill: "lexique",
    prompt: "Que signifie ce verbe ?",
    question: "опаздывать",
    options: ["se dépêcher", "être en retard", "attendre", "partir"],
    correctIndex: 1,
    explain: "«опаздывать / опоздать» = être en retard. «спешить» = se dépêcher.",
  },

  {
    id: "a2-mou-metro",
    domain: "mouvement",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Chaque matin je vais au travail en métro. »",
    question: "Каждое утро я ___ на работу на метро.",
    options: ["иду", "еду", "хожу", "езжу"],
    correctIndex: 3,
    explain:
      "Habitude (каждое утро) + véhicule → езжу. «еду» décrirait le trajet en cours, «хожу» un déplacement à pied.",
  },
  {
    id: "a2-mou-seychas",
    domain: "mouvement",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « En ce moment, il rentre à la maison (à pied). »",
    question: "Сейчас он ___ домой.",
    options: ["идёт", "ходит", "ездит", "ходил"],
    correctIndex: 0,
    explain:
      "Un trajet en cours, dans une direction → unidirectionnel идёт. «ходит» dirait une habitude.",
  },
  {
    id: "a2-cas-age",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'ai vingt ans. »",
    question: "___ двадцать лет.",
    options: ["Я", "Меня", "Мне", "Мной"],
    correctIndex: 2,
    explain: "L'âge se dit au datif : мне двадцать лет (littéralement « à moi vingt ans »).",
  },
  {
    id: "a2-cas-partitif",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Donne-moi un peu d'eau. »",
    question: "Дай мне немного ___.",
    options: ["вода", "воду", "воды", "водой"],
    correctIndex: 2,
    explain: "«немного» est une expression de quantité : elle exige le génitif — немного воды.",
  },
  {
    id: "a2-cas-acc-anime",
    domain: "cas",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Je vois mon frère. »",
    question: "Я вижу ___.",
    options: ["брат", "брата", "брату", "братом"],
    correctIndex: 1,
    explain:
      "Masculin ANIMÉ : l'accusatif emprunte la forme du génitif → брата. Comparer avec « вижу дом » (inanimé).",
  },
  {
    id: "a2-asp-uzhe",
    domain: "aspect",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « J'ai déjà vu ce film. »",
    question: "Я уже ___ этот фильм.",
    options: ["смотрел", "посмотрел", "смотрю", "буду смотреть"],
    correctIndex: 1,
    explain:
      "«уже» pointe un résultat atteint → perfectif посмотрел. L'imperfectif «смотрел» décrirait l'activité, sans dire qu'elle a abouti.",
  },
  {
    id: "a2-mor-byla",
    domain: "morphologie",
    tier: 2,
    skill: "grammaire",
    prompt: "Complète : « Elle était à la maison hier. »",
    question: "Вчера она ___ дома.",
    options: ["был", "была", "было", "были"],
    correctIndex: 1,
    explain: "Le passé de «быть» s'accorde en genre : она была.",
  },
  {
    id: "a2-lex-dorogo",
    domain: "lexique",
    tier: 2,
    skill: "lexique",
    prompt: "Que signifie ce mot ?",
    question: "дорого",
    options: ["bon marché", "cher", "gratuit", "rapide"],
    correctIndex: 1,
    explain: "«дорого» = cher. «дёшево» = bon marché.",
  },

  // ─── Palier 3 · B1 — ТРКИ-1 ──────────────────────────────────────
  {
    id: "b1-gram-instr-metier",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Mon père travaille comme médecin. »",
    question: "Мой отец работает ___.",
    options: ["врач", "врача", "врачом", "врачу"],
    correctIndex: 2,
    explain: "«работать» + instrumental pour la profession : работает врачом.",
  },
  {
    id: "b1-gram-instr-avec",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Je vais au cinéma avec un ami. »",
    question: "Я иду в кино с ___.",
    options: ["друг", "друга", "другом", "другу"],
    correctIndex: 2,
    explain: "La préposition «с» (avec) exige l'instrumental : с другом.",
  },
  {
    id: "b1-gram-aspect-delai",
    domain: "aspect",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'ai lu ce livre en deux jours. »",
    question: "Я ___ эту книгу за два дня.",
    options: ["читал", "прочитал", "читаю", "буду читать"],
    correctIndex: 1,
    explain:
      "«за + durée» indique le temps qu'il a fallu pour ALLER AU BOUT → perfectif : прочитал.",
  },
  {
    id: "b1-gram-chtoby",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Je suis venu pour t'aider. »",
    question: "Я пришёл, ___ тебе помочь.",
    options: ["что", "чтобы", "потому что", "если"],
    correctIndex: 1,
    explain: "But + infinitif : чтобы. «потому что» donne la cause, pas le but.",
  },
  {
    id: "b1-gram-kotoryy",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « La fille que j'ai rencontrée hier est ma sœur. »",
    question: "Девушка, ___ я встретил вчера, — моя сестра.",
    options: ["которая", "которую", "которой", "которого"],
    correctIndex: 1,
    explain:
      "«который» prend le genre de son antécédent (девушка, fém.) et le cas de sa fonction dans la subordonnée — ici objet direct → которую.",
  },
  {
    id: "b1-gram-motion-prefixe",
    domain: "mouvement",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il est entré dans la pièce et s'est assis. »",
    question: "Он ___ в комнату и сел.",
    // «пришёл» écarté des distracteurs : «прийти в комнату» se dit aussi,
    // l'item n'aurait plus eu une seule réponse défendable. Les quatre
    // options opposent maintenant des préfixes de direction incompatibles.
    options: ["вошёл", "вышел", "перешёл", "отошёл"],
    correctIndex: 0,
    explain:
      "Le préfixe в(о)- marque l'entrée : войти в комнату. вы- = sortir de, пере- = traverser, от- = s'écarter.",
  },
  {
    id: "b1-gram-conditionnel",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Si j'avais le temps, je t'aiderais. »",
    question: "Если бы у меня было время, я ___ тебе.",
    options: ["помогу", "помог бы", "помогал", "помочь"],
    correctIndex: 1,
    explain: "L'irréel se construit avec «бы» + passé dans LES DEUX propositions : если бы… помог бы.",
  },
  {
    id: "b1-gram-genitif-pluriel",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il y a beaucoup d'étudiants dans notre ville. »",
    question: "В нашем городе много ___.",
    options: ["студент", "студенты", "студентов", "студентам"],
    correctIndex: 2,
    explain: "«много» exige le génitif pluriel : студентов.",
  },
  {
    id: "b1-gram-datif-verbe",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'aide souvent ma mère. »",
    question: "Я часто помогаю ___.",
    options: ["маму", "маме", "мамой", "мамы"],
    correctIndex: 1,
    explain:
      "«помогать» se construit avec le datif, là où le français a un objet direct : помогаю маме.",
  },
  {
    id: "b1-gram-reflexif",
    domain: "morphologie",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Le matin je me réveille à sept heures. »",
    question: "Утром я ___ в семь часов.",
    options: ["просыпаю", "просыпаюсь", "просыпается", "проснуть"],
    correctIndex: 1,
    explain: "Verbe pronominal en -ся, 1re personne : просыпаюсь.",
  },
  {
    id: "b1-gram-superlatif",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « C'est le film le plus intéressant de l'année. »",
    question: "Это ___ интересный фильм года.",
    options: ["более", "самый", "очень", "такой"],
    correctIndex: 1,
    explain: "Superlatif : самый + adjectif. «более» sert au comparatif (plus…que).",
  },
  {
    id: "b1-lex-vnezapno",
    domain: "lexique",
    tier: 3,
    skill: "lexique",
    prompt: "Que signifie cet adverbe ?",
    question: "внезапно",
    options: ["lentement", "soudain", "souvent", "à peine"],
    correctIndex: 1,
    explain: "«внезапно» = soudainement, tout à coup.",
  },

  {
    id: "b1-mou-vyshel",
    domain: "mouvement",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il est sorti de la pièce et a fermé la porte. »",
    question: "Он ___ из комнаты и закрыл дверь.",
    options: ["вошёл", "вышел", "перешёл", "подошёл"],
    correctIndex: 1,
    explain:
      "« из » impose le préfixe вы- (sortir de l'intérieur). в(о)- serait l'entrée, под- l'approche.",
  },
  {
    id: "b1-mou-podoshla",
    domain: "mouvement",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Elle s'est approchée de la fenêtre. »",
    question: "Она подошла ___ окну.",
    options: ["к", "до", "у", "на"],
    correctIndex: 0,
    explain: "Le préfixe под- appelle « к » + datif : подойти к окну.",
  },
  {
    id: "b1-cas-instr-moyen",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'écris au stylo. »",
    question: "Я пишу ___.",
    options: ["ручка", "ручку", "ручкой", "ручке"],
    correctIndex: 2,
    explain:
      "L'instrument se met à l'instrumental, sans préposition : пишу ручкой. C'est ce sens qui donne son nom au cas.",
  },
  {
    id: "b1-cas-prep-rossii",
    domain: "cas",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « J'habite en Russie. »",
    question: "Я живу в ___.",
    options: ["Россия", "Россию", "России", "Россией"],
    correctIndex: 2,
    explain:
      "Lieu où l'on est : в + prépositionnel. Un radical en -и (Россия) donne -ии → в России.",
  },
  {
    id: "b1-asp-napishu",
    domain: "aspect",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Demain j'écrirai la lettre et je l'enverrai. »",
    question: "Завтра я ___ письмо и отправлю его.",
    options: ["напишу", "буду писать", "пишу", "писал"],
    correctIndex: 0,
    explain:
      "Deux actions qui s'enchaînent, chacune menée à son terme → perfectif напишу. « буду писать » décrirait une activité sans fin marquée.",
  },
  {
    id: "b1-syn-chto-indirect",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il a dit qu'il viendrait demain. »",
    question: "Он сказал, ___ придёт завтра.",
    options: ["что", "чтобы", "если", "ли"],
    correctIndex: 0,
    explain:
      "Discours indirect déclaratif : « что ». « чтобы » introduirait un but, « ли » une question.",
  },
  {
    id: "b1-syn-luchshe",
    domain: "syntaxe",
    tier: 3,
    skill: "grammaire",
    prompt: "Complète : « Il parle russe mieux que moi. »",
    question: "Он говорит по-русски ___, чем я.",
    options: ["хорошо", "лучше", "хороший", "самый хороший"],
    correctIndex: 1,
    explain: "Comparatif irrégulier de « хорошо » : лучше. La construction est « лучше, чем… ».",
  },
  {
    id: "b1-lex-vnimatelno",
    domain: "lexique",
    tier: 3,
    skill: "lexique",
    prompt: "Que signifie cet adverbe ?",
    question: "внимательно",
    options: ["rapidement", "attentivement", "rarement", "bruyamment"],
    correctIndex: 1,
    explain: "« внимательно » = attentivement, de « внимание » (attention).",
  },

  // ─── Palier 4 · B2 — ТРКИ-2 ──────────────────────────────────────
  {
    id: "b2-gram-participe-actif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « L'étudiant qui lit à la bibliothèque est mon ami. »",
    question: "Студент, ___ в библиотеке, — мой друг.",
    options: ["читает", "читающий", "читаемый", "читая"],
    correctIndex: 1,
    explain:
      "Participe présent actif : читающий (celui qui lit). «читаемый» est passif, «читая» est un gérondif.",
  },
  {
    id: "b2-gram-participe-passif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Le livre écrit par Tolstoï est devenu un classique. »",
    question: "Книга, ___ Толстым, стала классикой.",
    options: ["написал", "написавший", "написанная", "написав"],
    correctIndex: 2,
    explain:
      "Participe passé passif, accordé avec книга (fém.) : написанная. L'agent se met à l'instrumental (Толстым).",
  },
  {
    id: "b2-gram-gerondif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « En rentrant chez moi, j'ai croisé un vieil ami. »",
    question: "___ домой, я встретил старого друга.",
    options: ["Возвращаюсь", "Возвращаясь", "Возвращался", "Возвращение"],
    correctIndex: 1,
    explain:
      "Gérondif imperfectif : возвращаясь — l'action accompagne celle du verbe principal, même sujet.",
  },
  {
    id: "b2-gram-regime-interesovatsya",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il s'intéresse depuis longtemps à l'histoire. »",
    question: "Он давно интересуется ___.",
    options: ["историю", "истории", "историей", "об истории"],
    correctIndex: 2,
    explain: "«интересоваться» se construit avec l'instrumental : интересуется историей.",
  },
  {
    id: "b2-gram-regime-izbegat",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il évite les conflits. »",
    question: "Он избегает ___.",
    options: ["конфликты", "конфликтов", "конфликтам", "конфликтами"],
    correctIndex: 1,
    explain: "«избегать» exige le génitif : избегает конфликтов.",
  },
  {
    id: "b2-gram-regime-udelyat",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il accorde beaucoup d'attention aux détails. »",
    question: "Он уделяет много внимания ___.",
    options: ["детали", "деталей", "деталям", "деталями"],
    correctIndex: 2,
    explain: "«уделять внимание» + datif : уделяет внимание деталям.",
  },
  {
    id: "b2-gram-passif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Cette maison a été construite au siècle dernier. »",
    question: "Этот дом ___ в прошлом веке.",
    options: ["строил", "построил", "был построен", "строится"],
    correctIndex: 2,
    explain:
      "Passif au passé : был + participe passé passif court (был построен). «строится» est un présent passif.",
  },
  {
    id: "b2-gram-nesmotrya",
    domain: "syntaxe",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Bien qu'il fût tard, nous avons continué. »",
    question: "___ на то что было поздно, мы продолжили работу.",
    options: ["Несмотря", "Благодаря", "Вопреки", "Из-за"],
    correctIndex: 0,
    explain:
      "Conjonction complexe «несмотря на то что» = bien que. «благодаря» = grâce à, «из-за» = à cause de.",
  },
  {
    id: "b2-gram-li",
    domain: "syntaxe",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il a demandé si je viendrais demain. »",
    question: "Он спросил, приду ___ я завтра.",
    options: ["что", "если", "ли", "чтобы"],
    correctIndex: 2,
    explain:
      "Interrogation indirecte totale : particule «ли» placée après le mot sur lequel porte la question. «если» ne sert qu'à l'hypothèse.",
  },
  {
    id: "b2-gram-derivation",
    domain: "lexique",
    tier: 4,
    skill: "grammaire",
    prompt: "Quel mot désigne la PERSONNE qui exerce l'action de « преподавать » (enseigner) ?",
    question: "преподавать → ?",
    options: ["преподавание", "преподаватель", "преподавательский", "преподанный"],
    correctIndex: 1,
    explain:
      "Suffixe -тель = agent : преподаватель (enseignant). «преподавание» est l'action, «-ский» un adjectif.",
  },
  {
    id: "b2-lex-sokrashchat",
    domain: "lexique",
    tier: 4,
    skill: "lexique",
    prompt: "Que signifie ce verbe ?",
    question: "сокращать",
    options: ["augmenter", "réduire", "reporter", "remplacer"],
    correctIndex: 1,
    explain: "«сокращать / сократить» = réduire, raccourcir (d'où «сокращение» : réduction, abréviation).",
  },
  {
    id: "b2-lex-uverennyy",
    domain: "lexique",
    tier: 4,
    skill: "lexique",
    prompt: "Que signifie cet adjectif ?",
    question: "уверенный",
    options: ["inquiet", "sûr, assuré", "surpris", "prudent"],
    correctIndex: 1,
    explain: "«уверенный» = sûr de soi, assuré ; «быть уверенным в чём-то» = être sûr de quelque chose.",
  },

  {
    id: "b2-par-gerondif-perf",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Ayant terminé son travail, il est rentré. »",
    question: "___ работу, он пошёл домой.",
    options: ["Заканчивая", "Закончив", "Закончил", "Заканчивать"],
    correctIndex: 1,
    explain:
      "Gérondif PERFECTIF en -в : l'action est achevée avant celle du verbe principal. « Заканчивая » (imperfectif) la dirait simultanée.",
  },
  {
    id: "b2-par-participe-passe-actif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « L'homme qui nous a aidés hier est médecin. »",
    question: "Человек, ___ нам вчера, — врач.",
    options: ["помогающий", "помогавший", "помогая", "помогаемый"],
    correctIndex: 1,
    explain:
      "Participe PASSÉ actif en -вший : l'action est révolue (вчера). « помогающий » serait au présent.",
  },
  {
    id: "b2-par-court-passif",
    domain: "participes",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « La porte est fermée. »",
    question: "Дверь ___.",
    options: ["закрыта", "закрытая", "закрывает", "закрывается"],
    correctIndex: 0,
    explain:
      "Participe passif COURT, employé comme attribut : дверь закрыта. La forme longue « закрытая » serait épithète (закрытая дверь).",
  },
  {
    id: "b2-cas-zanimatsya",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Il fait du sport. »",
    question: "Он занимается ___.",
    options: ["спорт", "спорта", "спортом", "спорту"],
    correctIndex: 2,
    explain: "« заниматься » se construit avec l'instrumental : занимается спортом.",
  },
  {
    id: "b2-cas-gorditsya",
    domain: "cas",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Je suis fier de mon fils. »",
    question: "Я горжусь ___.",
    options: ["сын", "сына", "сыну", "сыном"],
    correctIndex: 3,
    explain: "« гордиться » + instrumental : горжусь сыном.",
  },
  {
    id: "b2-asp-imperatif-negatif",
    domain: "aspect",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Ne ferme pas la porte ! »",
    question: "Не ___ дверь!",
    options: ["закрой", "закрывай", "закрыть", "закрыл"],
    correctIndex: 1,
    explain:
      "À l'impératif NÉGATIF, le russe emploie l'imperfectif : не закрывай. Le perfectif « не закрой » serait une mise en garde contre un accident, pas une interdiction.",
  },
  {
    id: "b2-syn-tak-kak",
    domain: "syntaxe",
    tier: 4,
    skill: "grammaire",
    prompt: "Complète : « Comme il était en retard, nous avons commencé sans lui. »",
    question: "___ он опоздал, мы начали без него.",
    options: ["Так как", "Чтобы", "Хотя", "Если"],
    correctIndex: 0,
    explain: "« Так как » introduit la cause. « Хотя » marquerait la concession, « Если » l'hypothèse.",
  },
  {
    id: "b2-lex-osushchestvit",
    domain: "lexique",
    tier: 4,
    skill: "lexique",
    prompt: "Que signifie ce verbe ?",
    question: "осуществить",
    options: ["annuler", "réaliser, mettre en œuvre", "envisager", "retarder"],
    correctIndex: 1,
    explain: "« осуществить » = réaliser, concrétiser (осуществить план : réaliser un plan).",
  },

  // ─── Palier 5 · C1 — ТРКИ-3 ──────────────────────────────────────
  {
    id: "c1-lex-shlyapa",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "дело в шляпе",
    options: ["c'est un désastre", "c'est dans la poche", "on verra bien", "c'est très compliqué"],
    correctIndex: 1,
    explain: "«дело в шляпе» = l'affaire est réglée, c'est dans la poche.",
  },
  {
    id: "c1-lex-baklushi",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "бить баклуши",
    options: ["travailler dur", "se disputer", "ne rien faire, paresser", "dire la vérité"],
    correctIndex: 2,
    explain: "«бить баклуши» = se tourner les pouces, ne rien faire.",
  },
  {
    id: "c1-lex-lomat-golovu",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "ломать голову",
    options: ["se creuser la tête", "perdre la mémoire", "se mettre en colère", "changer d'avis"],
    correctIndex: 0,
    explain: "«ломать голову над чем-то» = se casser la tête sur quelque chose.",
  },
  {
    id: "c1-gram-izza",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « À cause de la pluie, nous sommes restés à la maison. »",
    question: "___ дождя мы остались дома.",
    options: ["Благодаря", "Из-за", "Вопреки", "Согласно"],
    correctIndex: 1,
    explain:
      "«из-за» + génitif introduit une cause NÉGATIVE ; «благодаря» + datif une cause favorable (grâce à).",
  },
  {
    id: "c1-gram-svidetelstvovat",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Cela témoigne de problèmes sérieux. »",
    question: "Это свидетельствует ___ серьёзных проблемах.",
    options: ["о", "про", "за", "на"],
    correctIndex: 0,
    explain: "«свидетельствовать о чём-то» + prépositionnel. «про» existe mais reste familier et régit l'accusatif.",
  },
  {
    id: "c1-gram-prenebregat",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Il néglige les règles. »",
    question: "Он пренебрегает ___.",
    options: ["правила", "правил", "правилам", "правилами"],
    correctIndex: 3,
    explain: "«пренебрегать» exige l'instrumental : пренебрегает правилами.",
  },
  {
    id: "c1-gram-chem-tem",
    domain: "syntaxe",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Plus il travaillait, plus il se fatiguait. »",
    question: "Чем больше он работал, ___ сильнее он уставал.",
    options: ["так", "тем", "что", "как"],
    correctIndex: 1,
    explain: "Corrélation de proportion : «чем… тем…» (plus… plus…).",
  },
  {
    id: "c1-gram-aspect-vspomnit",
    domain: "aspect",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Je n'arrive absolument pas à me rappeler son numéro. »",
    question: "Я никак не могу ___ его номер телефона.",
    options: ["вспоминать", "вспомнить", "помнить", "запоминать"],
    correctIndex: 1,
    explain:
      "«никак не могу» vise un résultat qu'on n'atteint pas → perfectif вспомнить. «помнить» = garder en mémoire, état continu.",
  },
  {
    id: "c1-gram-aspect-pytatsya",
    domain: "aspect",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « J'ai longtemps essayé de le joindre. »",
    question: "Я долго ___ ему дозвониться.",
    options: ["пытался", "попытался", "попробую", "стал"],
    correctIndex: 0,
    explain: "«долго» décrit une tentative qui dure → imperfectif пытался. Le perfectif «попытался» serait ponctuel.",
  },
  {
    id: "c1-lex-registre",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Quel équivalent de « сейчас » appartient au registre écrit et soutenu ?",
    question: "сейчас → ?",
    options: ["щас", "в настоящее время", "потом", "давно"],
    correctIndex: 1,
    explain:
      "«в настоящее время» est la formule administrative/écrite. «щас» est une forme orale relâchée, «потом» = ensuite.",
  },
  {
    id: "c1-lex-predvzyatyy",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cet adjectif ?",
    question: "предвзятый",
    options: ["prévoyant", "partial, biaisé", "prévisible", "prétentieux"],
    correctIndex: 1,
    explain: "«предвзятый» = partial, préconçu (предвзятое мнение : une opinion biaisée).",
  },
  {
    id: "c1-lex-obuslovlen",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette forme ?",
    question: "обусловлен",
    options: ["conditionné, déterminé par", "obligatoire", "conclu", "supposé"],
    correctIndex: 0,
    explain: "«обусловлен чем-то» = déterminé/conditionné par quelque chose — registre écrit et analytique.",
  },
  {
    id: "c1-lex-spustya-rukava",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "спустя рукава",
    options: ["avec application", "à la va-vite, négligemment", "en cachette", "à contrecœur"],
    correctIndex: 1,
    explain:
      "« работать спустя рукава » = travailler par-dessus la jambe. L'image : les manches qu'on n'a pas retroussées.",
  },
  {
    id: "c1-lex-vodit-za-nos",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette expression figée ?",
    question: "водить за нос",
    options: ["mener en bateau", "prendre en charge", "suivre de près", "flatter"],
    correctIndex: 0,
    explain: "« водить кого-то за нос » = tromper quelqu'un, le mener en bateau.",
  },
  {
    id: "c1-lex-tem-ne-menee",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Que signifie cette locution ?",
    question: "тем не менее",
    options: ["d'autant plus", "néanmoins", "en particulier", "par conséquent"],
    correctIndex: 1,
    explain: "« тем не менее » = néanmoins, toutefois — registre écrit et argumentatif.",
  },
  {
    id: "c1-lex-daby",
    domain: "lexique",
    tier: 5,
    skill: "lexique",
    prompt: "Quel est l'équivalent neutre et courant de « дабы » ?",
    question: "дабы → ?",
    options: ["чтобы", "потому что", "хотя", "если"],
    correctIndex: 0,
    explain:
      "« дабы » est un archaïsme littéraire pour « чтобы » (afin que). Le reconnaître relève du registre, pas du sens.",
  },
  {
    id: "c1-syn-chto-by-ni",
    domain: "syntaxe",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Quoi qu'il dise, je ne le crois pas. »",
    question: "___ бы он ни говорил, я ему не верю.",
    options: ["Что", "Как", "Кто", "Где"],
    correctIndex: 0,
    explain:
      "Concessive indéfinie : mot interrogatif + « бы… ни » → « что бы он ни говорил » = quoi qu'il dise.",
  },
  {
    id: "c1-syn-ne-tolko",
    domain: "syntaxe",
    tier: 5,
    skill: "grammaire",
    prompt:
      "Complète : « Non seulement il est arrivé en retard, mais il a aussi oublié ses papiers. »",
    question: "Он не только опоздал, ___ и забыл документы.",
    options: ["а", "но", "или", "да"],
    correctIndex: 1,
    explain: "Corrélation figée : « не только… но и… ».",
  },
  {
    id: "c1-cas-protivorechit",
    domain: "cas",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Cela contredit les faits. »",
    question: "Это противоречит ___.",
    options: ["факты", "фактов", "фактам", "фактами"],
    correctIndex: 2,
    explain: "« противоречить » se construit avec le datif : противоречит фактам.",
  },
  {
    id: "c1-asp-poglyadyval",
    domain: "aspect",
    tier: 5,
    skill: "grammaire",
    prompt: "Complète : « Il ne cessait de jeter des coups d'œil par la fenêtre. »",
    question: "Он то и дело ___ в окно.",
    options: ["посмотрел", "поглядывал", "взглянул", "глядеть"],
    correctIndex: 1,
    explain:
      "« то и дело » marque la répétition : imperfectif à valeur itérative et atténuée, поглядывал. Les perfectifs « посмотрел » et « взглянул » seraient ponctuels.",
  },
];

export function questionsForTier(tier: number): LevelQuestion[] {
  return LEVEL_QUESTIONS.filter((q) => q.tier === tier);
}

export function getQuestion(id: string): LevelQuestion | undefined {
  return LEVEL_QUESTIONS.find((q) => q.id === id);
}
