// GÉNÉRÉ PAR scripts/build-lexicon.mjs — NE PAS ÉDITER À LA MAIN.
//
// Index d'autocomplétion : le mot russe accentué, sa traduction, sa nature.
// Voir lib/vocabulary/autocomplete.ts pour la recherche.

/** n = nom, v = verbe, adj = adjectif, adv = adverbe ou mot de liaison. */
export type LexKind = "n" | "v" | "adj" | "adv";

/**
 * [mot accentué, traduction, nature] — et un 4e élément `1` quand l'entrée
 * vient d'une banque RELUE À LA MAIN.
 *
 * Tuple plutôt qu'objet : 1750 entrées, les noms de champs
 * pèseraient plus que les données.
 *
 * POURQUOI DISTINGUER. Le vocabulaire produit par un modèle ne se trompe
 * pas au hasard : il se trompe de façon PLAUSIBLE. La construction écarte
 * les déformations d'un mot connu, mais elle ne peut rien contre une
 * traduction inventée pour un mot qu'aucune banque ne contient. L'apprenant
 * doit donc pouvoir voir, dans la liste, ce qui a été vérifié et ce qui est
 * une proposition.
 */
export type LexEntry = readonly [string, string, LexKind] | readonly [string, string, LexKind, 1];

export const LEXICON: readonly LexEntry[] = [
  ["абва́к", "alphabet", "n"],
  ["абрико́с", "abricot", "n"],
  ["а́вгуст", "août", "n"],
  ["а́веню", "avenue", "n"],
  ["авто́бус", "bus", "n", 1],
  ["автомоби́ль", "automobile", "n", 1],
  ["а́втор", "auteur", "n", 1],
  ["адвока́т", "avocat", "n", 1],
  ["а́дрес", "adresse", "n", 1],
  ["акка́ун", "compte", "n"],
  ["актри́са", "actrice", "n", 1],
  ["альбо́м", "album", "n", 1],
  ["ана́лиз", "analyse", "n", 1],
  ["а́нгел", "ange", "n", 1],
  ["англи́йский", "anglais", "adj"],
  ["апельси́н", "orange", "n"],
  ["апре́ль", "avril", "n"],
  ["аптека́", "pharmacie", "n"],
  ["а́рмия", "armée", "n", 1],
  ["артери́я", "artère", "n"],
  ["артист", "acteur", "n"],
  ["атла́с", "satin", "n"],
  ["аэропо́рт", "aéroport", "n", 1],
  ["бабочка", "papillon", "n"],
  ["ба́бушка", "grand-mère", "n", 1],
  ["балко́н", "balcon", "n"],
  ["бана́н", "banane", "n"],
  ["ба́нк", "banque", "n"],
  ["ба́нка", "bocal", "n", 1],
  ["бараба́н", "tambour", "n"],
  ["бассе́йн", "piscine", "n", 1],
  ["батаре́я", "batterie", "n"],
  ["бег", "course", "n"],
  ["бедро́", "cuisse", "n"],
  ["бежа́ть", "courir", "v", 1],
  ["безопасный", "sûr", "adj"],
  ["белка", "écureuil", "n"],
  ["бе́лый", "blanc", "adj"],
  ["береце́т", "béret", "n"],
  ["беспоко́иться", "s'inquiéter", "v"],
  ["беспоко́йство", "inquiétude", "n"],
  ["бесполезный", "inutile", "adj"],
  ["Библи́я", "Bible", "n"],
  ["биле́т", "billet", "n", 1],
  ["бинт", "bandage", "n"],
  ["благодари́ть", "remercier", "v"],
  ["благода́рность", "gratitude", "n"],
  ["бле́днеть", "pâlir", "v"],
  ["бледный", "pâle", "adj"],
  ["блёклый", "terne", "adj"],
  ["блестя́щий", "brillant", "adj"],
  ["ближа́йший", "prochain", "adj"],
  ["близко́", "près", "adv"],
  ["блу́зка", "blouse", "n"],
  ["блю́до", "plat", "n", 1],
  ["Бог", "Dieu", "n"],
  ["бока́л", "verre (à pied)", "n", 1],
  ["боле́зненный", "douloureux", "adj"],
  ["боле́знь", "maladie", "n", 1],
  ["боль", "douleur", "n", 1],
  ["больни́ца", "hôpital", "n", 1],
  ["больничный", "arrêt maladie", "n"],
  ["большой", "grand", "adj", 1],
  ["боля́ть", "faire mal", "v"],
  ["бор́щ", "bortsch", "n"],
  ["босс", "patron", "n"],
  ["боя́ться", "craindre", "v"],
  ["бра́вый", "brave", "adj"],
  ["брани́ть", "injurier", "v"],
  ["брасле́т", "bracelet", "n", 1],
  ["брат", "frère", "n", 1],
  ["брать", "prendre", "v", 1],
  ["брони́рование", "réservation", "n"],
  ["брони́ровать", "réserver", "v"],
  ["брюки", "pantalon", "n"],
  ["бу́дить", "réveiller", "v"],
  ["буду́щий", "futur", "adj"],
  ["бума́га", "papier", "n", 1],
  ["буста́льтер", "soutien-gorge", "n"],
  ["бухга́лтер", "comptable", "n"],
  ["быстро́", "vite", "adv"],
  ["быстрый", "rapide", "adj"],
  ["быть", "être (futur)", "v", 1],
  ["бюро́", "bureau", "n"],
  ["ва́гон", "wagon", "n"],
  ["ванна́", "baignoire", "n"],
  ["ванная", "salle de bain", "n"],
  ["варе́нье", "confiture", "n"],
  ["вари́ть", "cuire", "v"],
  ["ва́тый", "ouaté", "adj"],
  ["ваш", "votre", "adj"],
  ["вверх", "haut", "adv"],
  ["вводи́ть", "entrer", "v"],
  ["ве́дьма", "sorcière", "n", 1],
  ["вежли́вость", "politesse", "n"],
  ["вежливый", "poli", "adj"],
  ["век", "siècle", "n", 1],
  ["велеть", "commander", "v"],
  ["вели́кий", "grand", "adj"],
  ["вели́чество", "majesté", "n"],
  ["велосипе́д", "vélo", "n", 1],
  ["вельве́т", "velours côtelé", "n"],
  ["вена́", "veine", "n"],
  ["вера́", "foi", "n"],
  ["ве́рно", "exactement", "adv"],
  ["верность", "fidélité", "n"],
  ["верну́ться", "retourner", "v"],
  ["верный", "fidèle", "adj"],
  ["ве́роятность", "probabilité", "n"],
  ["верте́ться", "tourner", "v"],
  ["веру́ю", "croire", "v"],
  ["вес", "poids", "n"],
  ["весёлый", "gai", "adj"],
  ["ве́ский", "lourd", "adj"],
  ["весна́", "printemps", "n", 1],
  ["весьма́", "fort", "adv"],
  ["ветер", "vent", "n"],
  ["ве́чер", "soir", "n", 1],
  ["вечери́нка", "soirée", "n", 1],
  ["ве́черность", "vespéral", "adj"],
  ["взволнова́нный", "agité", "adj"],
  ["вздыха́ть", "soupirer", "v"],
  ["взять", "prendre", "v", 1],
  ["вид", "aspect", "n", 1],
  ["ви́деокарта", "carte graphique", "n"],
  ["ви́деть", "voir", "v", 1],
  ["ви́за", "visa", "n"],
  ["ви́зит", "visite", "n"],
  ["ви́ктория", "victoire", "n"],
  ["вила́", "fourchette", "n"],
  ["ви́на", "culpabilité", "n"],
  ["вино́", "vin", "n", 1],
  ["ви́ноград", "raisin", "n"],
  ["вкус", "goût", "n", 1],
  ["вкусный", "délicieux", "adj", 1],
  ["влада́ние", "domination", "n"],
  ["владе́лец", "propriétaire", "n", 1],
  ["влажный", "humide", "adj"],
  ["власть", "pouvoir", "n", 1],
  ["вли́яние", "influence", "n"],
  ["вме́сте", "ensemble", "adv"],
  ["вниз", "bas", "adv"],
  ["вниз́у", "en bas", "adv"],
  ["внима́ние", "attention", "n", 1],
  ["внук", "petit-fils", "n"],
  ["внутри́", "dedans", "adv"],
  ["вну́чка", "petite-fille", "n"],
  ["вогну́тый", "concave", "adj"],
  ["вода́", "eau", "n", 1],
  ["води́тель", "conducteur", "n", 1],
  ["во́дка", "vodka", "n", 1],
  ["вое́нный", "militaire", "adj"],
  ["возвраща́ться", "revenir", "v"],
  ["возмо́жность", "possibilité", "n", 1],
  ["возмуща́ться", "s'indigner", "v"],
  ["вознагради́ть", "récompenser", "v"],
  ["возража́ть", "s'opposer", "v"],
  ["во́зраст", "âge", "n", 1],
  ["воин", "guerrier", "n"],
  ["война́", "guerre", "n", 1],
  ["войти́", "entrer", "v"],
  ["вокза́л", "gare", "n", 1],
  ["волк", "loup", "n", 1],
  ["волнение", "émotion", "n"],
  ["волнова́ться", "s'émouvoir", "v"],
  ["во́лос", "cheveu", "n", 1],
  ["волосы́", "cheveux", "n"],
  ["вообража́ть", "imaginer", "v"],
  ["вопро́с", "question", "n", 1],
  ["вор", "voleur", "n", 1],
  ["воро́бей", "moineau", "n"],
  ["воро́на", "corbeau", "n"],
  ["восемна́дцать", "dix-huit", "adj"],
  ["восемь", "huit", "adj"],
  ["воскресе́нье", "dimanche", "n", 1],
  ["восхища́ться", "admirer", "v"],
  ["восхище́ние", "admiration", "n"],
  ["восьмьдеся́т", "quatre-vingts", "adj"],
  ["впереди́", "devant", "adv"],
  ["враг", "ennemi", "n", 1],
  ["враждебный", "hostile", "adj"],
  ["враниль", "nuit", "n"],
  ["врач", "médecin", "n", 1],
  ["вра́щаться", "tourner", "v"],
  ["вре́мя", "temps", "n", 1],
  ["всё", "tout", "adv"],
  ["всегда́", "toujours", "adv"],
  ["всего́", "total", "adv"],
  ["вскоре́", "bientôt", "adv"],
  ["вспомина́ть", "se souvenir", "v"],
  ["вставать", "se lever", "v", 1],
  ["вставля́ть", "coller", "v"],
  ["встать", "se lever", "v", 1],
  ["встретить", "rencontrer", "v", 1],
  ["встре́ча", "rencontre", "n", 1],
  ["встречать", "rencontrer", "v", 1],
  ["вто́рник", "mardi", "n", 1],
  ["второ́й", "second", "adj"],
  ["вход", "entrée", "n", 1],
  ["входи́ть", "entrer", "v"],
  ["вчера́", "hier", "adv"],
  ["вы́бирать", "sélectionner", "v"],
  ["вы́бор", "choix", "n", 1],
  ["выезд", "départ", "n"],
  ["вы́здороветь", "guérir", "v"],
  ["вы́йти", "sortir", "v"],
  ["выпить", "boire", "v", 1],
  ["вы́пуклый", "convexe", "adj"],
  ["вырезать", "couper", "v"],
  ["высокий", "haut", "adj"],
  ["вы́ступ", "speech", "n"],
  ["выучить", "apprendre (par cœur)", "v", 1],
  ["вы́ход", "sortie", "n", 1],
  ["выходи́ть", "sortir", "v"],
  ["гада́ть", "deviner", "v"],
  ["газе́та", "journal", "n", 1],
  ["гали́ть", "railler", "v"],
  ["га́лстук", "cravate", "n", 1],
  ["где́-то", "quelque part", "adv"],
  ["ге́ний", "génie", "n", 1],
  ["геро́й", "héros", "n", 1],
  ["гибкий", "flexible", "adj"],
  ["гита́ра", "guitare", "n"],
  ["глава́", "chapitre", "n", 1],
  ["гладкий", "lisse", "adj"],
  ["глаз", "œil", "n", 1],
  ["гла́сный", "voyelle", "n"],
  ["глубо́кий", "profond", "adj"],
  ["глу́пый", "bête", "adj"],
  ["гнев", "colère", "n", 1],
  ["гневаться", "se fâcher", "v"],
  ["говори́ть", "parler, dire", "v", 1],
  ["год", "an", "n"],
  ["голова́", "tête", "n", 1],
  ["го́лос", "voix", "n", 1],
  ["голубо́й", "bleu ciel", "adj"],
  ["гора́", "montagne", "n", 1],
  ["гордость", "fierté", "n"],
  ["гордый", "fier", "adj"],
  ["горе́", "chagrin", "n"],
  ["го́род", "ville", "n", 1],
  ["го́рький", "amer", "adj"],
  ["горя́чий", "chaud", "adj"],
  ["господи́н", "monsieur", "n", 1],
  ["гостиная", "salon", "n"],
  ["гости́ница", "hôtel", "n", 1],
  ["гость", "invité", "n", 1],
  ["госуда́рственный", "public", "adj"],
  ["госуда́рство", "État", "n"],
  ["гото́вить", "préparer, cuisiner", "v", 1],
  ["гра́вийный", "graveleux", "adj"],
  ["гра́дус", "degré", "n"],
  ["гра́мм", "gramme", "n"],
  ["грамма́тика", "grammaire", "n"],
  ["грани́ца", "frontière", "n"],
  ["гра́фик", "horaire", "n"],
  ["графи́ка", "graphique", "n"],
  ["грея́ть", "chauffer", "v"],
  ["гроза́", "orage", "n"],
  ["гром", "tonnerre", "n"],
  ["гро́мко", "fort", "adv"],
  ["грубый", "rude", "adj"],
  ["гру́дь", "poitrine", "n"],
  ["грузови́к", "camion", "n", 1],
  ["груста́ть", "s'attrister", "v"],
  ["грусти́ть", "s'attrister", "v"],
  ["грустный", "triste", "adj"],
  ["грусть", "tristesse", "n"],
  ["груша", "poire", "n"],
  ["грязный", "sale", "adj"],
  ["губа́", "lèvre", "n"],
  ["губерна́тор", "gouverneur", "n", 1],
  ["гуля́ть", "se promener", "v", 1],
  ["гусь", "oie", "n"],
  ["да", "oui", "adv"],
  ["дава́ть", "donner", "v", 1],
  ["далеко́", "loin", "adv"],
  ["да́льше", "plus loin", "adv"],
  ["да́ма", "dame", "n", 1],
  ["да́нные", "données", "n"],
  ["дари́ть", "offrir", "v"],
  ["дать", "donner", "v", 1],
  ["два", "deux", "adj"],
  ["два́дцать", "vingt", "adj"],
  ["двена́дцать", "douze", "adj"],
  ["дверь", "porte", "n", 1],
  ["двига́ть", "bouger", "v"],
  ["движе́ние", "mouvement", "n"],
  ["дви́нуть", "bouger", "v"],
  ["двор", "cour", "n", 1],
  ["дворя́нин", "noble", "n"],
  ["де́вочка", "fillette", "n", 1],
  ["де́вушка", "jeune fille", "n", 1],
  ["девяносто́", "quatre-vingt-dix", "adj"],
  ["девятна́дцать", "dix-neuf", "adj"],
  ["девять", "neuf", "adj"],
  ["де́душка", "grand-père", "n", 1],
  ["де́жка", "jupe", "n"],
  ["дейтви́тельно", "vraiment", "adv"],
  ["дека́брь", "décembre", "n"],
  ["де́лать", "faire", "v", 1],
  ["де́латься", "être fait", "v"],
  ["де́ликатный", "délicat", "adj"],
  ["де́ло", "affaire", "n", 1],
  ["день", "jour", "n", 1],
  ["де́ньги", "argent", "n"],
  ["де́рево", "arbre", "n", 1],
  ["держа́ть", "tenir", "v", 1],
  ["десе́рт", "dessert", "n", 1],
  ["де́сятилетие", "décennie", "n"],
  ["де́сять", "dix", "adj"],
  ["де́ти", "enfants", "n"],
  ["дива́н", "canapé", "n", 1],
  ["дире́ктор", "directeur", "n", 1],
  ["длинный", "long", "adj"],
  ["длить́ся", "durer", "v"],
  ["дневни́к", "journal intime", "n", 1],
  ["до́брота", "bonté", "n"],
  ["добрый", "bon", "adj"],
  ["доверя́ть", "faire confiance", "v"],
  ["догово́р", "contrat", "n", 1],
  ["дождь", "pluie", "n", 1],
  ["дозво́л", "permission", "n"],
  ["дока́зывать", "prouver", "v"],
  ["докуме́нт", "document", "n", 1],
  ["дол́жно", "devoir", "v"],
  ["должность", "poste", "n"],
  ["дом", "maison", "n", 1],
  ["домашний", "domestique, familial", "adj", 1],
  ["доро́га", "route", "n", 1],
  ["дорогой", "cher, précieux", "adj", 1],
  ["до́ска", "tableau", "n"],
  ["достато́чно", "assez", "adv"],
  ["дочь", "fille (de qqn)", "n", 1],
  ["дре́вний", "antique", "adj"],
  ["дрожа́ть", "trembler", "v"],
  ["друг", "ami", "n", 1],
  ["дружелю́бный", "amical", "adj"],
  ["ду́мать", "penser", "v", 1],
  ["духо́вка", "four", "n"],
  ["ду́ш", "douche", "n"],
  ["душа́", "âme", "n", 1],
  ["дя́дя", "oncle", "n"],
  ["его́", "son, le sien", "n", 1],
  ["её", "son", "adj"],
  ["ежик", "hérisson", "n"],
  ["есть", "manger", "v", 1],
  ["е́хать", "aller (en véhicule)", "v", 1],
  ["жалеть", "regretter", "v"],
  ["жа́лованье", "traitement", "n"],
  ["жа́ловаться", "se plaindre", "v"],
  ["жалость", "pitié", "n"],
  ["жаль", "dommage", "adv"],
  ["жари́ть", "frire", "v"],
  ["жа́рко", "chaud", "adj"],
  ["жать", "moissonner", "v"],
  ["ждать", "attendre", "v", 1],
  ["же", "or", "adv"],
  ["жела́ть", "souhaiter", "v"],
  ["жёлтый", "jaune", "adj"],
  ["желу́док", "estomac", "n"],
  ["жена́", "épouse", "n", 1],
  ["жени́х", "fiancé", "n", 1],
  ["же́нщина", "femme", "n", 1],
  ["жёсткий", "dur", "adj"],
  ["жестокий", "cruel", "adj"],
  ["живопи́сь", "peinture", "n"],
  ["живо́т", "ventre", "n", 1],
  ["живо́тное", "animal", "n", 1],
  ["жидкий", "liquide", "adj"],
  ["жизнь", "vie", "n", 1],
  ["жить", "vivre, habiter", "v", 1],
  ["журна́л", "magazine", "n", 1],
  ["забавный", "amusant", "adj"],
  ["заболе́ть", "tomber malade", "v"],
  ["забывать", "oublier", "v", 1],
  ["забыть", "oublier", "v", 1],
  ["завидова́ть", "envier", "v"],
  ["зависть", "envie", "n"],
  ["за́вод", "usine", "n"],
  ["за́втра", "demain", "adv"],
  ["за́втрак", "petit-déjeuner", "n", 1],
  ["завтракать", "prendre le petit-déjeuner", "v", 1],
  ["загружа́ть", "charger", "v"],
  ["зада́ние", "mission", "n", 1],
  ["зада́ча", "tâche", "n", 1],
  ["заезд", "arrivée", "n"],
  ["зака́зать", "commander", "v"],
  ["заканчивать", "terminer", "v", 1],
  ["зако́н", "loi", "n", 1],
  ["закончить", "terminer", "v", 1],
  ["закрывать", "fermer", "v", 1],
  ["закрыть", "fermer", "v", 1],
  ["за́ли", "salle", "n"],
  ["за́лка", "fermeture éclair", "n"],
  ["замёрзнуть", "geler", "v"],
  ["замеча́ть", "remarquer", "v"],
  ["за́мок", "château", "n", 1],
  ["занаве́с", "rideau", "n"],
  ["занаве́ски", "rideaux", "n"],
  ["занаве́сь", "rideau", "n"],
  ["занима́ться", "s'occuper", "v"],
  ["заня́тие", "occupation", "n"],
  ["занято́й", "occupé", "adj"],
  ["занято́сть", "occupation", "n"],
  ["за́пах", "odeur", "n", 1],
  ["записа́ть", "noter", "v"],
  ["за́пись", "note", "n", 1],
  ["заплати́ть", "payer", "v"],
  ["запо́н", "tablier", "n"],
  ["запре́т", "interdiction", "n"],
  ["запя́стье", "poignet", "n"],
  ["зарпла́та", "salaire", "n"],
  ["зарядка", "chargeur", "n"],
  ["засту́пник", "intercesseur", "n"],
  ["зате́м", "ensuite", "adv"],
  ["зачёт", "validation", "n"],
  ["заяц", "lièvre", "n"],
  ["звезда́", "étoile", "n", 1],
  ["звони́ть", "téléphoner", "v", 1],
  ["звоно́к", "sonnette", "n"],
  ["звук", "son", "n", 1],
  ["зда́ние", "bâtiment", "n", 1],
  ["здесь", "ici", "adv"],
  ["здоро́вый", "sain", "adj"],
  ["здоро́вье", "santé", "n", 1],
  ["здра́вствуйте", "bonjour", "v"],
  ["зелёный", "vert", "adj"],
  ["земля́", "terre", "n", 1],
  ["зе́ркало", "miroir", "n", 1],
  ["зима́", "hiver", "n", 1],
  ["злиться", "se fâcher", "v"],
  ["злой", "méchant", "adj"],
  ["змея́", "serpent", "n", 1],
  ["знание", "connaissance", "n"],
  ["знать", "savoir, connaître", "v", 1],
  ["значе́ние", "signification", "n", 1],
  ["значо́к", "symbole", "n"],
  ["зонт", "parapluie", "n", 1],
  ["зуб", "dent", "n"],
  ["игра́", "jeu", "n", 1],
  ["игра́ть", "jouer", "v", 1],
  ["игро́к", "joueur", "n", 1],
  ["иде́я", "idée", "n", 1],
  ["иди́", "aller", "v"],
  ["идти́", "aller (à pied)", "v", 1],
  ["извине́ние", "excuses", "n"],
  ["извини́те", "excusez-moi", "v"],
  ["изви́ниться", "s'excuser", "v"],
  ["извиня́ться", "s'excuser", "v"],
  ["изображение", "image", "n"],
  ["изумля́ться", "s'étonner", "v"],
  ["изучать", "étudier (à fond)", "v", 1],
  ["изучить", "étudier (à fond)", "v", 1],
  ["иконка", "icône", "n"],
  ["име́ть", "avoir", "v"],
  ["импера́тор", "empereur", "n"],
  ["импорт", "importer", "v"],
  ["и́мя", "prénom", "n", 1],
  ["инжене́р", "ingénieur", "n"],
  ["иногда́", "parfois", "adv"],
  ["инструме́нт", "instrument", "n"],
  ["интервью́", "entretien", "n"],
  ["интере́с", "intérêt", "n", 1],
  ["интересный", "intéressant", "adj", 1],
  ["интересова́ть", "intéresser", "v"],
  ["интерне́т", "internet", "n"],
  ["информа́ция", "information", "n", 1],
  ["ирга́ть", "jouer", "v"],
  ["иска́ть", "chercher", "v", 1],
  ["и́скла", "excepté", "adv"],
  ["исключе́ние", "exception", "n"],
  ["иску́сство", "art", "n", 1],
  ["испове́даться", "se confesser", "v"],
  ["испо́лненный", "rempli", "adj"],
  ["испра́вить", "corriger", "v"],
  ["исправле́ние", "correction", "n"],
  ["испуга́нный", "effrayé", "adj"],
  ["испуга́ться", "s'effrayer", "v"],
  ["испыта́ть", "éprouver", "v"],
  ["иссле́дование", "recherche", "n", 1],
  ["истина́", "vérité", "n"],
  ["исто́рия", "histoire", "n", 1],
  ["их", "leur", "adj"],
  ["июль", "juillet", "n"],
  ["июнь", "juin", "n"],
  ["кабель", "câble", "n"],
  ["кабине́т", "bureau (pièce)", "n", 1],
  ["каждый", "chaque", "adj"],
  ["кальсо́ны", "caleçon", "n"],
  ["каме́нистый", "pierreux", "adj"],
  ["ка́мень", "pierre", "n", 1],
  ["капита́н", "capitaine", "n", 1],
  ["капу́ста", "chou", "n"],
  ["каранда́ш", "crayon", "n"],
  ["ка́рта", "carte", "n", 1],
  ["карти́на", "tableau", "n", 1],
  ["картофе́ль", "pomme de terre", "n"],
  ["ка́рточка", "carte", "n"],
  ["ка́рьер", "carrière", "n"],
  ["карье́ра", "carrière", "n"],
  ["касса́", "caisse", "n"],
  ["кассир", "caissier", "n"],
  ["кастрю́ля", "casserole", "n"],
  ["ка́тание", "patinage", "n"],
  ["ката́ться", "rouler", "v"],
  ["кафе́", "café", "n"],
  ["каша́", "bouillie", "n"],
  ["кашель", "toux", "n"],
  ["квадра́тный", "carré", "adj"],
  ["ква́лифицированный", "qualifié", "adj"],
  ["кварти́ра", "appartement", "n", 1],
  ["кедры́", "chaussure de toile", "n"],
  ["кепка", "casquette", "n"],
  ["килогра́мм", "kilogramme", "n"],
  ["кило́метр", "kilomètre", "n"],
  ["кино́", "cinéma", "n"],
  ["кира́пи́ч", "brique", "n"],
  ["кисли́й", "aigre", "adj"],
  ["кисть", "main", "n"],
  ["кишка́", "intestin", "n"],
  ["клавиату́ра", "clavier", "n"],
  ["кла́вишь", "clé", "n"],
  ["класс", "classe", "n"],
  ["кла́сс-ро́ом", "salle de classe", "n"],
  ["класть", "poser (à plat)", "v", 1],
  ["клие́нт", "client", "n", 1],
  ["кли́кать", "cliquer", "v"],
  ["кло́ниться", "se pencher", "v"],
  ["клуб", "club", "n", 1],
  ["ключ", "clé", "n", 1],
  ["кни́га", "livre", "n", 1],
  ["кно́пка", "bouton", "n"],
  ["кня́зь", "prince", "n"],
  ["ковёр", "tapis", "n"],
  ["коврик", "petit tapis", "n"],
  ["когда́-то", "autrefois", "adv"],
  ["ко́жа", "peau", "n", 1],
  ["ко́жер", "gant", "n"],
  ["коза", "chèvre", "n"],
  ["коле́но", "genou", "n"],
  ["коли́чество", "quantité", "n", 1],
  ["колле́га", "collègue", "n"],
  ["кольцо́", "bague", "n", 1],
  ["кома́нда", "équipe", "n", 1],
  ["команди́р", "commandant", "n", 1],
  ["ко́мната", "pièce", "n", 1],
  ["комо́д", "commode", "n"],
  ["компа́ния", "entreprise", "n", 1],
  ["компью́тер", "ordinateur", "n", 1],
  ["конде́ктор", "receveur", "n"],
  ["коне́ц", "fin", "n", 1],
  ["контра́кт", "contrat", "n"],
  ["контро́льная", "contrôle", "n"],
  ["конфере́нция", "conférence", "n"],
  ["конце́рт", "concert", "n", 1],
  ["конча́ть", "finir", "v"],
  ["кончи́ть", "finir", "v"],
  ["конь", "cheval", "n"],
  ["копи́ровать", "copier", "v"],
  ["кора́бль", "navire", "n", 1],
  ["корень", "racine", "n"],
  ["коридо́р", "couloir", "n"],
  ["коричне́вый", "marron", "adj"],
  ["ко́робка", "boîte", "n"],
  ["корова", "vache", "n"],
  ["короле́ва", "reine", "n", 1],
  ["коро́ль", "roi", "n", 1],
  ["короткий", "court", "adj"],
  ["ко́смос", "espace", "n", 1],
  ["кость", "os", "n", 1],
  ["костю́м", "costume", "n", 1],
  ["кот", "chat", "n", 1],
  ["ко́фе", "café", "n"],
  ["кофта", "cardigan", "n"],
  ["ко́шка", "chatte", "n", 1],
  ["край", "bord", "n", 1],
  ["кра́мер", "magasin", "n"],
  ["краса́", "beauté", "n"],
  ["красивый", "beau / belle", "adj", 1],
  ["кра́ска", "couleur", "n"],
  ["краски́", "peintures", "n"],
  ["краснеть", "rougir", "v"],
  ["кра́сный", "rouge", "adj"],
  ["кре́сло", "fauteuil", "n", 1],
  ["кресь́янин", "paysan", "n"],
  ["кривой", "courbe", "adj"],
  ["кризис", "crise", "n"],
  ["критика́", "critique", "n"],
  ["кричать", "crier", "v"],
  ["крова́ть", "lit", "n", 1],
  ["кровля́", "couverture", "n"],
  ["кровь", "sang", "n", 1],
  ["кро́лик", "lapin", "n", 1],
  ["кромка́", "bord", "n"],
  ["кро́ткий", "doux", "adj"],
  ["кротко́й", "doux", "adj"],
  ["кроха́", "miettes", "n"],
  ["круглый", "rond", "adj"],
  ["кру́гом", "tout autour", "adv"],
  ["кру́жево", "dentelle", "n"],
  ["крутить", "tourner", "v"],
  ["кру́титься", "tourner", "v"],
  ["кры́са", "rat", "n", 1],
  ["кры́ша", "toit", "n", 1],
  ["кто́-то", "quelqu'un", "adv"],
  ["кузе́н", "cousin", "n", 1],
  ["кузи́на", "cousine", "n"],
  ["купе́ц", "marchand", "n"],
  ["купи́ть", "acheter", "v", 1],
  ["ку́пюра", "billet", "n"],
  ["кура́тка", "veste", "n"],
  ["курица", "poule", "n"],
  ["курс", "cours", "n", 1],
  ["ку́рсор", "curseur", "n"],
  ["куртка", "blouson", "n"],
  ["кусо́к", "morceau", "n", 1],
  ["ку́хня", "cuisine", "n", 1],
  ["лавка", "boutique", "n"],
  ["лага́ть", "grimper", "v"],
  ["ла́дно", "d'accord", "adv"],
  ["ла́мпа", "lampe", "n", 1],
  ["ласко́вость", "tendresse", "n"],
  ["ласко́вый", "tendre", "adj"],
  ["леге́нда", "légende", "n", 1],
  ["лёгкий", "léger", "adj"],
  ["ле́гко", "facilement", "adv"],
  ["лёгкое", "poumon", "n"],
  ["легкомы́сленный", "léger", "adj"],
  ["лед", "glace", "n"],
  ["ледя́ной", "glacé", "adj"],
  ["лежа́ть", "être couché", "v", 1],
  ["ле́зть", "grimper", "v"],
  ["лека́рство", "médicament", "n", 1],
  ["лекция", "conférence", "n"],
  ["лён", "lin", "n"],
  ["ле́ний", "paresseux", "adj"],
  ["лес", "forêt", "n", 1],
  ["лесни́к", "forestier", "n"],
  ["лести́ть", "flatter", "v"],
  ["лестница", "escalier", "n"],
  ["ле́то", "été", "n", 1],
  ["ле́чить", "soigner", "v"],
  ["лечь", "se coucher", "v", 1],
  ["лимо́н", "citron", "n"],
  ["лиса", "renard", "n"],
  ["лист", "feuille", "n"],
  ["лит́р", "litre", "n"],
  ["лифт", "ascenseur", "n", 1],
  ["лихорадка́", "fièvre", "n"],
  ["лицо́", "visage", "n", 1],
  ["лоб", "front", "n"],
  ["ло́гин", "identifiant", "n"],
  ["ло́дка", "barque", "n", 1],
  ["ложиться", "se coucher", "v", 1],
  ["ложка́", "cuillère", "n"],
  ["ложный", "faux", "adj"],
  ["ложь", "mensonge", "n", 1],
  ["локоть", "coude", "n"],
  ["лось", "élan", "n"],
  ["ло́шадь", "cheval", "n", 1],
  ["лук", "oignon", "n", 1],
  ["луна́", "lune", "n", 1],
  ["люб", "amour", "n"],
  ["люба́", "amour", "n"],
  ["любе́зность", "courtoisie", "n"],
  ["любезный", "courtois", "adj"],
  ["люби́мый", "préféré", "adj"],
  ["люби́ть", "aimer", "v", 1],
  ["любо́вь", "amour", "n", 1],
  ["люди́", "gens", "n"],
  ["люк", "trappe", "n", 1],
  ["люстра́", "lustre", "n"],
  ["лягушка", "grenouille", "n"],
  ["магази́н", "magasin", "n", 1],
  ["май", "mai", "n"],
  ["майка", "débardeur", "n"],
  ["макаро́ны", "pâtes", "n"],
  ["маленький", "petit", "adj", 1],
  ["ма́ло", "peu", "adj"],
  ["малы́ш", "bébé", "n", 1],
  ["ма́льчик", "garçon", "n", 1],
  ["ма́ма", "maman", "n", 1],
  ["март", "mars", "n"],
  ["маршру́т", "itinéraire", "n"],
  ["ма́сло", "beurre", "n", 1],
  ["мастер", "maître", "n"],
  ["матовый", "mat", "adj"],
  ["матч", "match", "n", 1],
  ["мать", "mère", "n", 1],
  ["маши́на", "voiture", "n", 1],
  ["мёд", "miel", "n"],
  ["медве́дь", "ours", "n", 1],
  ["ме́дленно", "lentement", "adv"],
  ["медленный", "lent", "adj"],
  ["медсестра́", "infirmière", "n", 1],
  ["мел", "craie", "n", 1],
  ["ме́лкий", "peu profond", "adj"],
  ["мель", "haut-fond", "n", 1],
  ["ме́неджер", "gérant", "n", 1],
  ["ме́ню", "menu", "n"],
  ["мера́", "mesure", "n"],
  ["ме́сто", "endroit", "n", 1],
  ["ме́сяц", "mois", "n", 1],
  ["ме́тод", "méthode", "n", 1],
  ["ме́тр", "mètre", "n"],
  ["метро́", "métro", "n", 1],
  ["мечта́", "rêve (souhait)", "n", 1],
  ["мечта́ть", "rêver", "v"],
  ["милый", "cher", "adj"],
  ["мини́стр", "ministre", "n", 1],
  ["ми́нус", "moins", "adv"],
  ["мину́та", "minute", "n", 1],
  ["ми́р", "paix", "n"],
  ["мири́ться", "se réconcilier", "v"],
  ["мирный", "paisible", "adj"],
  ["ми́щь", "puissance", "n"],
  ["мне́ни", "à mon avis", "adv"],
  ["мне́ние", "avis", "n"],
  ["мно́го", "beaucoup", "adj"],
  ["могу́щественный", "puissant", "adj"],
  ["мо́жно", "puis-je", "adv"],
  ["мозг", "cerveau", "n", 1],
  ["мои́", "mon", "adj"],
  ["мо́йка", "évier", "n"],
  ["мокрый", "mouillé", "adj"],
  ["мо́литва", "prière", "n"],
  ["молния́", "éclair", "n"],
  ["молодой", "jeune", "adj", 1],
  ["молоко́", "lait", "n", 1],
  ["моме́нт", "moment", "n", 1],
  ["монета́", "pièce", "n"],
  ["мони́тор", "moniteur", "n"],
  ["мо́ре", "mer", "n", 1],
  ["морко́вь", "carotte", "n"],
  ["мост", "pont", "n", 1],
  ["мотоци́кл", "moto", "n", 1],
  ["мочь", "pouvoir", "v", 1],
  ["мощь", "puissance", "n"],
  ["мрачный", "morose", "adj"],
  ["му́дрый", "sage", "adj"],
  ["муж", "mari", "n", 1],
  ["мужество́", "courage", "n"],
  ["мужчи́на", "homme", "n", 1],
  ["музе́й", "musée", "n", 1],
  ["му́зыка", "musique", "n", 1],
  ["музыка́нт", "musicien", "n"],
  ["мука́", "farine", "n", 1],
  ["муравей", "fourmi", "n"],
  ["мутный", "trouble", "adj"],
  ["мучиться", "se torturer", "v"],
  ["мы́слить", "penser", "v"],
  ["мысль", "pensée", "n", 1],
  ["мы́шца", "muscle", "n"],
  ["мы́шь", "souris", "n"],
  ["мягкий", "doux", "adj"],
  ["мя́со", "viande", "n", 1],
  ["мять", "froisser", "n", 1],
  ["мяч", "ballon", "n", 1],
  ["наблюда́ть", "observer", "v"],
  ["навы́к", "compétence", "n"],
  ["наги́баться", "se plier", "v"],
  ["наги́ть", "se plier", "v"],
  ["награда́", "récompense", "n"],
  ["наде́жда", "espoir", "n", 1],
  ["надея́ться", "espérer", "v"],
  ["назва́ние", "nom (d'une chose)", "n", 1],
  ["наказа́ние", "punition", "n"],
  ["наказа́ть", "punir", "v"],
  ["налево́", "à gauche", "adv"],
  ["налива́ть", "verser", "v"],
  ["налог", "impôt", "n"],
  ["написать", "écrire", "v", 1],
  ["напи́ток", "boisson", "n", 1],
  ["напра́во", "à droite", "adv"],
  ["напротив", "en face", "adv"],
  ["наро́д", "peuple", "n", 1],
  ["наслажда́ться", "jouir", "v"],
  ["насморк", "rhume", "n"],
  ["настрое́ние", "humeur", "n", 1],
  ["натя́гивать", "étirer", "v"],
  ["нау́ка", "science", "n", 1],
  ["нача́ло", "début", "n", 1],
  ["нача́льник", "chef", "n", 1],
  ["нача́ть", "commencer", "v", 1],
  ["начинать", "commencer", "v", 1],
  ["наш", "notre", "adj"],
  ["не́бо", "ciel", "n", 1],
  ["неверный", "infidèle", "adj"],
  ["неве́ста", "fiancée", "n", 1],
  ["неде́ля", "semaine", "n", 1],
  ["недоумева́ть", "être perplexe", "v"],
  ["нельзя́", "ne pas pouvoir", "adv"],
  ["немецки́й", "allemand", "adj"],
  ["ненави́деть", "haïr", "v"],
  ["не́нависть", "haine", "n"],
  ["необходи́мость", "nécessité", "n"],
  ["непра́вильный", "incorrect", "adj"],
  ["нервный", "nerveux", "adj"],
  ["неровный", "inégal", "adj"],
  ["нёс", "il portait", "n", 1],
  ["несколько́", "plusieurs", "adj"],
  ["несогласие", "désaccord", "n"],
  ["несправедливый", "injuste", "adj"],
  ["не́сти", "porter", "v"],
  ["несчастны́й", "malheureux", "adj"],
  ["несча́стье", "malheur", "n"],
  ["нет", "non", "adv"],
  ["неуда́ча", "échec", "n"],
  ["нечестный", "malhonnête", "adj"],
  ["низкий", "bas", "adj"],
  ["никогда́", "jamais", "adv"],
  ["ничего́", "rien", "adv"],
  ["но́", "mais", "adv"],
  ["ново́е", "nouveau", "adj"],
  ["но́вость", "nouvelle", "n", 1],
  ["новый", "nouveau", "adj", 1],
  ["нога́", "jambe", "n", 1],
  ["нога́вица", "bas", "n"],
  ["ногти́", "ongle", "n"],
  ["нож", "couteau", "n", 1],
  ["ножници́", "ciseaux", "n"],
  ["но́мер", "numéro", "n", 1],
  ["норта́л", "portail", "n"],
  ["нос", "nez", "n", 1],
  ["но́сить", "porter", "v"],
  ["носки", "chaussette", "n"],
  ["носок", "chaussette", "n"],
  ["ночь", "nuit", "n", 1],
  ["ноября́", "novembre", "n"],
  ["нра́ва", "mœurs", "n"],
  ["нра́виться", "plaire", "v"],
  ["нра́вственность", "moralité", "n"],
  ["ну́жно", "falloir", "adv"],
  ["обе́д", "déjeuner", "n", 1],
  ["обе́дать", "déjeuner", "v"],
  ["обида́ть", "offenser", "v"],
  ["обижа́ться", "se vexer", "v"],
  ["облако", "nuage", "n"],
  ["облкла́дываю", "tapisserie", "n"],
  ["обожа́ть", "adorer", "v"],
  ["обраду́ется", "se réjouir", "v"],
  ["о́браз", "image", "n", 1],
  ["образова́ние", "formation", "n", 1],
  ["обраща́ть", "tourner", "v"],
  ["о́бщество", "société", "n", 1],
  ["объявле́ние", "annonce", "n", 1],
  ["объяснить", "expliquer", "v", 1],
  ["объяснять", "expliquer", "v", 1],
  ["о́бычай", "coutume", "n"],
  ["обязанности", "devoirs", "n"],
  ["обя́зательно", "absolument", "adv"],
  ["о́вощ", "légume", "n"],
  ["овца", "mouton", "n"],
  ["ого́нь", "feu", "n", 1],
  ["огуре́ц", "concombre", "n"],
  ["одева́ться", "s'habiller", "v"],
  ["оде́жда", "vêtement", "n", 1],
  ["одеяло́", "couverture", "n"],
  ["один", "un", "adj"],
  ["оди́ннадцать", "onze", "adj"],
  ["однако́", "cependant", "adv"],
  ["одобре́ние", "approbation", "n"],
  ["озадачивать", "déconcerter", "v"],
  ["о́зеро", "lac", "n", 1],
  ["океа́н", "océan", "n", 1],
  ["окно́", "fenêtre", "n", 1],
  ["октя́брь", "octobre", "n"],
  ["олень", "cerf", "n"],
  ["опазда́ть", "être en retard", "v"],
  ["опаса́ться", "redouter", "v"],
  ["опасный", "dangereux", "adj"],
  ["опера́тор", "opérateur", "n", 1],
  ["опера́ция", "opération", "n", 1],
  ["описа́ть", "décrire", "v"],
  ["о́плата", "paiement", "n"],
  ["опуска́ть", "baisser", "v"],
  ["опусти́ть", "baisser", "v"],
  ["о́пыт", "expérience", "n", 1],
  ["опы́тный", "expérimenté", "adj"],
  ["оранжевый", "orange", "adj"],
  ["орел", "aigle", "n"],
  ["оркестр", "orchestre", "n"],
  ["орфогра́фия", "orthographe", "n"],
  ["о́сень", "automne", "n", 1],
  ["осо́бенно", "surtout", "adv"],
  ["остава́ться", "rester", "v"],
  ["оставля́ть", "laisser", "v"],
  ["остана́вливаться", "s'arrêter", "v"],
  ["остано́виться", "s'arrêter", "v"],
  ["остано́вка", "arrêt", "n", 1],
  ["о́стров", "île", "n", 1],
  ["острый", "pointu", "adj"],
  ["остуди́ть", "refroidir", "v"],
  ["отве́т", "réponse", "n", 1],
  ["отве́тить", "répondre", "v", 1],
  ["отвеча́ть", "répondre", "v", 1],
  ["отде́л", "service", "n", 1],
  ["отдельно́", "séparément", "adv"],
  ["о́тдых", "repos", "n", 1],
  ["отдыха́ть", "se reposer", "v", 1],
  ["оте́ль", "hôtel", "n"],
  ["оте́ц", "père", "n", 1],
  ["отказа́ть", "refuser", "v"],
  ["открывать", "ouvrir", "v", 1],
  ["открыть", "ouvrir", "v", 1],
  ["отличный", "excellent", "adj"],
  ["отме́тка", "note", "n"],
  ["отойти́", "s'éloigner", "v"],
  ["отправи́ть", "envoyer", "v"],
  ["о́тпуск", "congé", "n", 1],
  ["отрица́ть", "nier", "v"],
  ["отходи́ть", "s'éloigner", "v"],
  ["отча́иваться", "désespérer", "v"],
  ["отча́яние", "désespoir", "n"],
  ["отчёт", "rapport", "n", 1],
  ["о́фис", "bureau", "n", 1],
  ["офице́р", "officier", "n", 1],
  ["охо́та", "chasse", "n"],
  ["охо́титься", "chasser", "v"],
  ["охо́тник", "chasseur", "n", 1],
  ["охра́нник", "gardien", "n", 1],
  ["оце́нка", "note", "n"],
  ["о́чень", "très", "adv"],
  ["о́ченьпы́", "très", "adv"],
  ["оши́бка", "erreur", "n", 1],
  ["ощуща́ть", "percevoir", "v"],
  ["пада́ние", "chute", "n"],
  ["па́дать", "tomber", "v"],
  ["паке́т", "sachet", "n", 1],
  ["па́лец", "doigt", "n", 1],
  ["пальто́", "manteau", "n"],
  ["па́мять", "mémoire", "n"],
  ["па́нель", "panneau", "n"],
  ["па́па", "papa", "n", 1],
  ["папка", "dossier", "n"],
  ["па́рень", "gars", "n", 1],
  ["парк", "parc", "n", 1],
  ["парко́вка", "parking", "n"],
  ["пароль", "mot de passe", "n"],
  ["па́спорт", "passeport", "n", 1],
  ["па́триарх", "patriarche", "n"],
  ["пахать", "labourer", "v"],
  ["пацие́нт", "patient", "n", 1],
  ["певе́ц", "chanteur", "n"],
  ["перво́й", "premier", "adj"],
  ["пе́рвый", "premier", "adj"],
  ["пе́ревод", "traduction", "n"],
  ["перейти́", "traverser", "v"],
  ["перекрё́сток", "carrefour", "n"],
  ["перемена́", "changement", "n"],
  ["перене́сти", "transporter", "v"],
  ["переноси́ть", "transporter", "v"],
  ["переп́она", "sandale", "n"],
  ["переп́оны", "sandales", "n"],
  ["переходи́ть", "traverser", "v"],
  ["пе́рец", "poivre", "n"],
  ["пе́ро", "stylo", "n"],
  ["перча́тка", "mitaine", "n"],
  ["пе́сня", "chanson", "n", 1],
  ["песок", "sable", "n"],
  ["песча́ный", "sableux", "adj"],
  ["петух", "coq", "n"],
  ["петь", "chanter", "v", 1],
  ["печа́ль", "tristesse", "n"],
  ["печальный", "mélancolique", "adj"],
  ["печата́ть", "imprimer", "v"],
  ["пе́чень", "foie", "n"],
  ["пече́нье", "biscuit", "n", 1],
  ["пече́ть", "cuire au four", "v"],
  ["пиани́но", "piano", "n"],
  ["пи́во", "bière", "n", 1],
  ["пиджа́к", "veste", "n", 1],
  ["пижа́ма", "pyjama", "n"],
  ["пило́т", "pilote", "n", 1],
  ["пиро́г", "tarte", "n", 1],
  ["писа́тель", "écrivain", "n", 1],
  ["писа́ть", "écrire", "v", 1],
  ["письмо́", "lettre", "n", 1],
  ["пить", "boire", "v", 1],
  ["пла́вание", "natation", "n"],
  ["пла́кать", "pleurer", "v", 1],
  ["план", "plan", "n", 1],
  ["плане́та", "planète", "n", 1],
  ["пла́стырь", "pansement", "n"],
  ["плати́ть", "payer", "v", 1],
  ["пла́тформа", "quai", "n"],
  ["пла́тье", "robe", "n", 1],
  ["пла́чу", "je pleure", "n", 1],
  ["плащ", "imperméable", "n"],
  ["плечо́", "épaule", "n", 1],
  ["плита́", "cuisinière", "n"],
  ["плоский", "plat", "adj"],
  ["плотный", "dense", "adj"],
  ["плохо́", "mal", "adv"],
  ["плохой", "mauvais", "adj", 1],
  ["пло́щадь", "place", "n", 1],
  ["плюс", "plus", "adv"],
  ["побе́да", "victoire", "n", 1],
  ["повёрнуть", "tourner", "v"],
  ["повесть", "récit", "n"],
  ["поворачива́ть", "tourner", "v"],
  ["повторить", "répéter", "v", 1],
  ["повторять", "répéter", "v", 1],
  ["пого́да", "météo", "n", 1],
  ["по́граница", "frontière", "n"],
  ["пода́рок", "cadeau", "n", 1],
  ["подборо́док", "menton", "n"],
  ["подва́л", "cave", "n", 1],
  ["подде́рживать", "soutenir", "v"],
  ["подма́стерье", "apprenti", "n"],
  ["поднима́ть", "lever", "v"],
  ["подня́ть", "lever", "v"],
  ["подойти́", "approcher", "v"],
  ["по́дпись", "signature", "n", 1],
  ["подру́га", "amie", "n", 1],
  ["подсла́дить", "sucrer", "v"],
  ["подстила́ть", "couvrir", "v"],
  ["подтя́жки", "bretelle", "n"],
  ["поду́мать", "réfléchir", "v"],
  ["подуша́ка", "oreiller", "n"],
  ["подходи́ть", "approcher", "v"],
  ["подъе́зд", "entrée d'immeuble", "n", 1],
  ["подыма́ть", "lever", "v"],
  ["по́езд", "train", "n", 1],
  ["пое́здка", "trajet", "n", 1],
  ["пожа́луйста", "s'il vous plaît", "n", 1],
  ["позавтракать", "prendre le petit-déjeuner", "v", 1],
  ["позвонить", "téléphoner", "v", 1],
  ["по́здний", "tardif", "adj"],
  ["по́здно", "tard", "adv"],
  ["пойма́", "compréhension", "n"],
  ["поки́нуть", "quitter", "v"],
  ["покупать", "acheter", "v", 1],
  ["поку́пка", "achat", "n"],
  ["пол", "sol", "n", 1],
  ["поласказа́ть", "goûter", "v"],
  ["полдень", "midi", "n"],
  ["по́ле", "champ", "n", 1],
  ["поле́зный", "utile", "adj"],
  ["ползве́рбь", "ramper", "v"],
  ["по́лзти", "ramper", "v"],
  ["поликли́ника", "clinique", "n"],
  ["поли́тика", "politique", "n"],
  ["поли́ция", "police", "n", 1],
  ["полка́", "étagère", "n"],
  ["полный", "plein", "adj"],
  ["поло́вина", "moitié", "n"],
  ["поло́жение", "position", "n"],
  ["положить", "poser (à plat)", "v", 1],
  ["поло́ночь", "minuit", "n"],
  ["полоте́нце", "serviette", "n", 1],
  ["получать", "recevoir", "v", 1],
  ["получить", "recevoir", "v", 1],
  ["пома́гать", "aider", "v"],
  ["помидо́р", "tomate", "n"],
  ["по́мнить", "se souvenir", "v", 1],
  ["помога́ть", "aider", "v"],
  ["помочь", "aider", "v"],
  ["помо́щник", "assistant", "n", 1],
  ["понеде́льник", "lundi", "n", 1],
  ["понима́ть", "comprendre", "v", 1],
  ["поня́ть", "comprendre", "v", 1],
  ["по́п", "pope", "n"],
  ["попа́сть", "arriver", "v"],
  ["пораже́ние", "défaite", "n", 1],
  ["поре́зать", "couper", "v"],
  ["посети́ть", "visiter", "v"],
  ["посеща́ть", "visiter", "v"],
  ["посмотреть", "regarder", "v", 1],
  ["посола́ть", "saler", "v"],
  ["посте́ль", "literie", "n", 1],
  ["построить", "construire", "v", 1],
  ["посу́да", "vaisselle", "n"],
  ["потоло́к", "plafond", "n"],
  ["потом", "puis", "adv"],
  ["потому́", "parce que", "adv"],
  ["почва", "sol", "n"],
  ["почёт", "honneur", "n"],
  ["почка́", "rein", "n"],
  ["по́чта", "poste", "n"],
  ["почти́", "presque", "adv"],
  ["поэ́т", "poète", "n", 1],
  ["поэто́му", "c'est pourquoi", "adv"],
  ["пояс", "ceinture", "n"],
  ["пра́вда", "vérité", "n", 1],
  ["прави́ла", "règles", "n"],
  ["пра́вило", "règle", "n", 1],
  ["прави́льность", "justesse", "n"],
  ["прави́льный", "correct", "adj"],
  ["прави́тельство", "gouvernement", "n", 1],
  ["пра́во", "droit", "n", 1],
  ["право́слав", "orthodoxe", "adj"],
  ["правосу́дие", "justice", "n"],
  ["пра́здник", "fête", "n", 1],
  ["преда́ние", "légende", "n"],
  ["предполага́ть", "supposer", "v"],
  ["предпочита́ть", "préférer", "v"],
  ["пред́приятие", "entreprise", "n"],
  ["председа́тель", "président (d'assemblée)", "n", 1],
  ["представле́ние", "spectacle", "n"],
  ["президе́нт", "président", "n", 1],
  ["презира́ть", "mépriser", "v"],
  ["презре́ние", "mépris", "n"],
  ["премия́", "prime", "n"],
  ["преподава́тель", "professeur", "n"],
  ["преступле́ние", "crime", "n", 1],
  ["престу́пник", "criminel", "n", 1],
  ["прибыва́ть", "arriver", "v"],
  ["при́бытие", "arrivée", "n"],
  ["приве́т", "salut", "n"],
  ["приви́легии", "privilèges", "n"],
  ["при́гласить", "inviter", "v"],
  ["приготовить", "préparer", "v", 1],
  ["прие́хать", "arriver", "v"],
  ["признава́ться", "avouer", "v"],
  ["призна́ть", "reconnaître", "v"],
  ["при́зрак", "fantôme", "n", 1],
  ["прийти́", "venir", "v"],
  ["приказа́ть", "ordonner", "v"],
  ["прилежный", "diligent", "adj"],
  ["при́ложение", "application", "n"],
  ["приме́р", "exemple", "n", 1],
  ["при́мерно", "environ", "adv"],
  ["примире́ние", "réconciliation", "n"],
  ["прина́ть", "arrêter", "v"],
  ["приноси́ть", "apporter", "v"],
  ["принте́р", "imprimante", "n"],
  ["принц", "prince", "n", 1],
  ["принце́сса", "princesse", "n", 1],
  ["принци́п", "principe", "n"],
  ["приня́ть", "accepter", "v"],
  ["приро́да", "nature", "n", 1],
  ["пристраститься", "s'accoutumer", "v"],
  ["приходи́ть", "arriver", "v"],
  ["причи́на", "raison", "n", 1],
  ["прия́тель", "copain", "n", 1],
  ["прия́тный", "agréable", "adj"],
  ["пробле́ма", "problème", "n", 1],
  ["проверя́ть", "vérifier", "v"],
  ["програ́мма", "programme", "n", 1],
  ["програ́ммист", "programmeur", "n"],
  ["про́гресс", "progrès", "n"],
  ["продава́ть", "vendre", "v"],
  ["прода́вец", "vendeur", "n"],
  ["про́дажа", "vente", "n"],
  ["прода́ть", "vendre", "v"],
  ["проду́кты", "aliments", "n"],
  ["проезжа́ть", "passer", "v"],
  ["прое́кт", "projet", "n", 1],
  ["про́зрачный", "transparent", "adj"],
  ["произве́сти", "produire", "v"],
  ["произво́дить", "produire", "v"],
  ["произво́дство", "production", "n"],
  ["произноше́ние", "prononciation", "n"],
  ["прокуро́р", "procureur", "n", 1],
  ["просвеща́ть", "instruire", "v"],
  ["проси́ть", "demander", "v", 1],
  ["проска́кивать", "franchir", "v"],
  ["прости́раться", "s'étendre", "v"],
  ["прости́те", "pardon", "v"],
  ["прости́ть", "pardonner", "v"],
  ["просто́", "simplement", "adv"],
  ["простой", "simple", "adj"],
  ["простыня́", "drap", "n"],
  ["просыпа́ться", "se réveiller", "v"],
  ["професиона́льный", "professionnel", "adj"],
  ["профе́ссия", "profession", "n"],
  ["про́хладный", "frais", "adj"],
  ["про́ход", "passage", "n"],
  ["проце́ссор", "processeur", "n"],
  ["прочитать", "lire", "v", 1],
  ["проч́ный", "solide", "adj"],
  ["про́шлый", "passé", "adj"],
  ["прощ", "pardon", "n"],
  ["проща́ть", "pardonner", "v"],
  ["прыга́ть", "sauter", "v"],
  ["прыгну́ть", "sauter", "v"],
  ["прямо́", "tout droit", "adv"],
  ["прямой", "droit", "adj"],
  ["пти́ца", "oiseau", "n", 1],
  ["пу́говица", "bouton", "n"],
  ["пунктуа́ция", "ponctuation", "n"],
  ["пустой", "vide", "adj"],
  ["путеше́ствие", "voyage", "n", 1],
  ["путеше́ствовать", "voyager", "v"],
  ["путь", "chemin", "n", 1],
  ["пчела́", "abeille", "n"],
  ["пьеса́", "pièce", "n"],
  ["пята́", "talon", "n"],
  ["пятна́дцать", "quinze", "adj"],
  ["пя́тница", "vendredi", "n"],
  ["пять", "cinq", "adj"],
  ["пятьдеся́т", "cinquante", "adj"],
  ["раб", "esclave", "n"],
  ["рабо́та", "travail", "n", 1],
  ["рабо́тать", "travailler", "v", 1],
  ["рабо́чий", "ouvrier", "n"],
  ["рабство", "esclavage", "n"],
  ["равноду́шие", "indifférence", "n"],
  ["равномерный", "uniforme", "adj"],
  ["раво́", "égal", "adv"],
  ["ра́доваться", "se réjouir", "v"],
  ["радостный", "joyeux", "adj"],
  ["ра́дость", "joie", "n", 1],
  ["ра́дый", "joyeux", "adj"],
  ["разбега́ться", "s'élancer", "v"],
  ["разви́тие", "développement", "n"],
  ["разгово́р", "conversation", "n", 1],
  ["раздева́ться", "se déshabiller", "v"],
  ["раздел", "rayon", "n"],
  ["раздража́ть", "irriter", "v"],
  ["раздражи́тельный", "irritable", "adj"],
  ["разме́р", "taille", "n", 1],
  ["разочарова́ние", "déception", "n"],
  ["разочаро́ваться", "être déçu", "v"],
  ["разреженный", "raréfié", "adj"],
  ["разъём", "connecteur", "n"],
  ["райо́н", "quartier", "n", 1],
  ["ракетка́", "raquette", "n"],
  ["рама́", "cadre", "n"],
  ["ра́на", "blessure", "n", 1],
  ["ра́нний", "précoce", "adj"],
  ["ра́но", "tôt", "adv"],
  ["раскида́ться", "s'étendre", "v"],
  ["расписа́ние", "horaire", "n"],
  ["расска́з", "récit", "n", 1],
  ["расска́зывать", "raconter", "v"],
  ["расстоя́ние", "distance", "n"],
  ["рассужде́ние", "raisonnement", "n"],
  ["расти́", "croître", "v"],
  ["расти́р", "schisme", "n"],
  ["расчёска", "peigne", "n"],
  ["ребёнок", "enfant", "n", 1],
  ["ревно́сть", "jalousie", "n"],
  ["реги́стрироваться", "s'enregistrer", "v"],
  ["ре́дко", "rarement", "adv"],
  ["режиссёр", "réalisateur", "n", 1],
  ["резать", "couper", "v"],
  ["результа́т", "résultat", "n", 1],
  ["резюме́", "CV", "n"],
  ["рейс", "vol", "n", 1],
  ["река́", "rivière", "n", 1],
  ["ре́лигия", "religion", "n"],
  ["рельс", "rail", "n"],
  ["ремень", "courroie", "n"],
  ["ремонт", "réparation", "n"],
  ["ремонти́ровать", "réparer", "v"],
  ["ре́ста", "reste", "n"],
  ["рестора́н", "restaurant", "n", 1],
  ["ре́форма", "réforme", "n"],
  ["реце́пт", "recette", "n", 1],
  ["речь", "discours", "n", 1],
  ["решать", "résoudre, décider", "v", 1],
  ["реше́ние", "décision", "n", 1],
  ["решить", "résoudre, décider", "v", 1],
  ["рис", "riz", "n", 1],
  ["рисова́ть", "dessiner", "v"],
  ["рису́нок", "dessin", "n"],
  ["ровный", "régulier", "adj"],
  ["роди́на", "patrie", "n"],
  ["роди́тели", "parents", "n"],
  ["роди́тель", "parent", "n"],
  ["роза", "rose", "n"],
  ["розовый", "rose", "adj"],
  ["роль", "rôle", "n", 1],
  ["рома́н", "roman", "n", 1],
  ["росстела́ть", "étendre", "v"],
  ["рост", "croissance", "n", 1],
  ["рот", "bouche", "n", 1],
  ["рубаха́", "chemise", "n"],
  ["рубаши́на", "chemise", "n"],
  ["руба́шка", "chemise", "n", 1],
  ["рубль", "rouble", "n"],
  ["ругать", "gronder", "v"],
  ["ругаться", "jurer", "v"],
  ["рудно́сть", "grossièreté", "n"],
  ["рука́", "main", "n", 1],
  ["русский", "russe", "adj", 1],
  ["ру́чка", "stylo", "n"],
  ["ры́ба", "poisson", "n", 1],
  ["рыба́к", "pêcheur", "n"],
  ["рыда́ть", "pleurer", "v"],
  ["ры́нок", "marché", "n", 1],
  ["рюкза́к", "sac à dos", "n"],
  ["ря́дом", "à côté", "adv"],
  ["сад", "jardin", "n", 1],
  ["садиться", "s'asseoir", "v", 1],
  ["сайт", "site", "n"],
  ["сала́т", "salade", "n", 1],
  ["самолёт", "avion", "n", 1],
  ["сантиме́тр", "centimètre", "n"],
  ["сапог", "botte", "n"],
  ["сараю́", "maison", "v"],
  ["са́хар", "sucre", "n", 1],
  ["сва́дьба", "mariage (cérémonie)", "n", 1],
  ["сварить", "cuire", "v"],
  ["свежий", "frais", "adj"],
  ["сверху́", "en haut", "adv"],
  ["светлокожный", "blond", "adj"],
  ["светлый", "clair", "adj"],
  ["свеча́", "bougie", "n"],
  ["свиде́тель", "témoin", "n", 1],
  ["свинья́", "cochon", "n", 1],
  ["сви́т", "lumière", "n"],
  ["сви́тер", "pull", "n"],
  ["свобо́да", "liberté", "n", 1],
  ["сво́бодный", "libre", "adj"],
  ["свя́зь", "connexion", "n"],
  ["свято́й", "saint", "adj"],
  ["свяще́нник", "prêtre", "n", 1],
  ["сделать", "faire", "v", 1],
  ["сего́дня", "aujourd'hui", "adv"],
  ["сезо́н", "saison", "n"],
  ["сейча́с", "maintenant", "n", 1],
  ["секре́т", "secret", "n", 1],
  ["секрета́рь", "secrétaire", "n", 1],
  ["секу́нда", "seconde", "n", 1],
  ["се́минар", "séminaire", "n"],
  ["семна́дцать", "dix-sept", "adj"],
  ["семь", "sept", "adj"],
  ["семьдеся́т", "soixante-dix", "adj"],
  ["семья́", "famille", "n", 1],
  ["сена́тор", "sénateur", "n", 1],
  ["сентя́брь", "septembre", "n"],
  ["сервирова́ть", "servir", "v"],
  ["серде́зный", "sérieux", "adj"],
  ["сердитый", "fâché", "adj"],
  ["се́рдце", "cœur", "n", 1],
  ["сериа́л", "série", "n", 1],
  ["сертифика́т", "certificat", "n"],
  ["серы́й", "gris", "adj"],
  ["серьёзный", "sérieux", "adj"],
  ["сестра́", "sœur", "n", 1],
  ["сесть", "s'asseoir", "v", 1],
  ["сеть", "réseau", "n"],
  ["сеять", "semer", "v"],
  ["сзади́", "derrière", "adv"],
  ["сиде́ть", "s'asseoir", "v"],
  ["си́ла", "force", "n", 1],
  ["сильный", "fort", "adj"],
  ["сима́", "s'asseoir", "v"],
  ["синий", "bleu (foncé)", "adj", 1],
  ["систе́ма", "système", "n", 1],
  ["сказа́ть", "dire", "v", 1],
  ["ска́зка", "conte", "n", 1],
  ["ска́нер", "scanner", "n"],
  ["скача́ть", "télécharger", "v"],
  ["ске́лет", "squelette", "n"],
  ["ски", "ski", "n"],
  ["скло́ниться", "se courber", "v"],
  ["сково́рода", "poêle", "n"],
  ["ско́лько", "combien", "adv"],
  ["ско́рее", "plutôt", "adv"],
  ["ско́ро", "bientôt", "adv"],
  ["ско́рость", "vitesse", "n"],
  ["скри́пка", "violon", "n"],
  ["скромность", "modestie", "n"],
  ["скромный", "modeste", "adj"],
  ["скука", "ennui", "n"],
  ["скульптура́", "sculpture", "n"],
  ["скупой", "avare", "adj"],
  ["скуча́ть", "s'ennuyer", "v"],
  ["скучный", "ennuyeux", "adj"],
  ["слабо́сть", "faiblesse", "n"],
  ["слабы́й", "faible", "adj"],
  ["сла́ва", "gloire", "n"],
  ["слади́кий", "sucré", "adj"],
  ["сла́дкий", "gentil", "adj"],
  ["сле́дствие", "conséquence", "n"],
  ["сли́ва", "prune", "n"],
  ["сло́варь", "dictionnaire", "n"],
  ["сло́во", "mot", "n", 1],
  ["сложный", "compliqué", "adj"],
  ["сло́мок", "pantoufle", "n"],
  ["слуга́", "serviteur", "n"],
  ["служба", "service", "n"],
  ["служи́ть", "servir", "v"],
  ["слу́чай", "cas", "n", 1],
  ["слу́шать", "écouter", "v", 1],
  ["слы́шать", "entendre", "v", 1],
  ["сме́лость", "courage", "n"],
  ["сме́лый", "courageux", "adj"],
  ["смерть", "mort", "n", 1],
  ["смех", "rire", "n", 1],
  ["сме́шивать", "mélanger", "v"],
  ["сме́шный", "drôle", "adj"],
  ["смея́ться", "rire", "v"],
  ["сми́рение", "humilité", "n"],
  ["смирённый", "humble", "adj"],
  ["смотре́ть", "regarder", "v", 1],
  ["смо́чный", "mouillé", "adj"],
  ["смысл", "sens", "n", 1],
  ["снару́жи", "dehors", "adv"],
  ["сначала́", "d'abord", "adv"],
  ["снег", "neige", "n", 1],
  ["соба́ка", "chien", "n", 1],
  ["собра́ние", "réunion", "n", 1],
  ["собы́тие", "événement", "n", 1],
  ["совсе́м", "complètement", "adv"],
  ["совсе́мне", "pas du tout", "adv"],
  ["согласи́е", "accord", "n"],
  ["согласи́ться", "consentir", "v"],
  ["согла́сный", "consonne", "n"],
  ["соглаше́ние", "accord", "n"],
  ["сожале́ние", "regret", "n"],
  ["сожале́ть", "regretter", "v"],
  ["созерца́ть", "contempler", "v"],
  ["сознава́ть", "admettre", "v"],
  ["сок", "jus", "n", 1],
  ["солда́т", "soldat", "n", 1],
  ["соле́ный", "salé", "adj"],
  ["со́лнце", "soleil", "n", 1],
  ["соль", "sel", "n", 1],
  ["сомнева́ться", "douter", "v"],
  ["сомне́ние", "doute", "n"],
  ["сон", "rêve", "n", 1],
  ["сообще́ние", "message", "n", 1],
  ["соору́жение", "ouvrage", "n"],
  ["со́рок", "quarante", "adj"],
  ["сорока", "pie", "n"],
  ["сосе́д", "voisin", "n", 1],
  ["сосе́дка", "voisine", "n", 1],
  ["сотру́дник", "employé", "n"],
  ["сохрани́ть", "enregistrer", "v"],
  ["сочу́вствовать", "compatir", "v"],
  ["спальня", "chambre à coucher", "n"],
  ["спаси́бо", "merci", "n", 1],
  ["спать", "dormir", "v"],
  ["специали́ст", "spécialiste", "n", 1],
  ["спеши́ть", "se dépêcher", "v"],
  ["спина́", "dos", "n", 1],
  ["спи́сок", "liste", "n", 1],
  ["спокойно́", "calmement", "adv"],
  ["спокойный", "calme", "adj"],
  ["спо́койствие", "calme", "n"],
  ["спо́рить", "discuter", "v"],
  ["спорт", "sport", "n"],
  ["спо́соб", "moyen", "n", 1],
  ["справедливый", "juste", "adj"],
  ["спраши́вать", "demander", "v"],
  ["сра́зу", "tout de suite", "adv"],
  ["среда́", "mercredi", "n"],
  ["сре́дний", "moyen", "adj"],
  ["срок", "délai", "n", 1],
  ["ссори́ться", "se disputer", "v"],
  ["ссы́лка", "lien", "n"],
  ["стака́н", "verre", "n", 1],
  ["стану́ть", "se lever", "v"],
  ["ста́нция", "station", "n", 1],
  ["стари́к", "vieillard", "n", 1],
  ["старый", "vieux", "adj", 1],
  ["статья́", "article", "n", 1],
  ["ствол", "tronc", "n"],
  ["сте́каемый", "verre", "adj"],
  ["стекло́", "verre", "n"],
  ["стена́", "mur", "n", 1],
  ["стихотворение", "poème", "n"],
  ["сто", "cent", "adj"],
  ["сто́имость", "coût", "n"],
  ["стои́ть", "coûter", "v"],
  ["стол", "table", "n", 1],
  ["столе́тие", "siècle", "n"],
  ["столи́ца", "capitale", "n"],
  ["стопа́", "pied", "n"],
  ["сторона́", "côté", "n", 1],
  ["стоя́ть", "être debout", "v", 1],
  ["страда́ть", "souffrir", "v"],
  ["страна́", "pays", "n", 1],
  ["страни́ца", "page", "n"],
  ["страстно́", "passionnément", "adv"],
  ["страх", "peur", "n", 1],
  ["стре́сс", "stress", "n"],
  ["строить", "construire", "v", 1],
  ["стро́й", "construction", "n"],
  ["стройка", "chantier", "n"],
  ["студе́нт", "étudiant", "n", 1],
  ["студе́нтка", "étudiante", "n"],
  ["стул", "chaise", "n", 1],
  ["стыд", "honte", "n"],
  ["стыди́ться", "avoir honte", "v"],
  ["суббо́та", "samedi", "n"],
  ["суд", "tribunal", "n", 1],
  ["судья́", "juge", "n", 1],
  ["су́мка", "sac", "n", 1],
  ["су́мма", "somme", "n", 1],
  ["сумра́чный", "sombre", "adj"],
  ["суп", "soupe", "n", 1],
  ["суста́в", "articulation", "n"],
  ["сухо́й", "sec", "adj"],
  ["сце́на", "scène", "n", 1],
  ["сцены́", "plateau", "n"],
  ["счастли́вый", "heureux", "adj"],
  ["сча́стье", "bonheur", "n", 1],
  ["счёт", "addition", "n", 1],
  ["съесть", "manger", "v", 1],
  ["сын", "fils", "n"],
  ["сыр", "fromage", "n", 1],
  ["сюда́", "ici", "adv"],
  ["сюжет", "intrigue", "n"],
  ["та́блетка", "comprimé", "n"],
  ["табли́ца", "tableau", "n"],
  ["та́йна", "mystère", "n", 1],
  ["такси́", "taxi", "n"],
  ["та́лантливый", "talentueux", "adj"],
  ["там", "là", "adv"],
  ["таможня́", "douane", "n"],
  ["тана́ть", "danser", "v"],
  ["та́нец", "danse", "n", 1],
  ["танцева́ть", "danser", "v"],
  ["танцо́р", "danseur", "n"],
  ["таре́лка", "assiette", "n", 1],
  ["твёрдый", "dur", "adj"],
  ["твой", "ton", "adj"],
  ["теа́тр", "théâtre", "n", 1],
  ["теку́щий", "actuel", "adj"],
  ["телеви́зор", "téléviseur", "n", 1],
  ["телефо́н", "téléphone", "n", 1],
  ["те́ло", "corps", "n"],
  ["тёмный", "sombre", "adj"],
  ["температу́ра", "température", "n"],
  ["те́ннис", "tennis", "n"],
  ["тень", "ombre", "n", 1],
  ["теория́", "théorie", "n"],
  ["тепе́рь", "à présent", "adv"],
  ["тёплый", "chaud (temps)", "adj", 1],
  ["терпе́ть", "supporter", "v"],
  ["терра́са", "terrasse", "n"],
  ["тест", "test", "n"],
  ["те́тра", "cahier", "n"],
  ["тётя", "tante", "n", 1],
  ["ти́хо", "doucement", "adv"],
  ["ткань", "tissu", "n"],
  ["това́р", "marchandise", "n"],
  ["това́рищ", "camarade", "n", 1],
  ["толка́ть", "pousser", "v"],
  ["толкну́ть", "pousser", "v"],
  ["толсто́й", "épais", "adj"],
  ["толстый", "épais", "adj"],
  ["то́лько", "seulement", "adv"],
  ["тонкий", "fin", "adj"],
  ["торго́вля", "commerce", "n"],
  ["торт", "gâteau", "n", 1],
  ["трава́", "herbe", "n"],
  ["тради́ция", "tradition", "n"],
  ["трамва́й", "tramway", "n"],
  ["тра́та", "dépense", "n"],
  ["траты́", "dépenses", "n"],
  ["тревога́", "inquiétude", "n"],
  ["тре́нер", "entraîneur", "n", 1],
  ["треть", "tiers", "n"],
  ["треуго́льный", "triangulaire", "adj"],
  ["три", "trois", "adj"],
  ["три́дцать", "trente", "adj"],
  ["трина́дцать", "treize", "adj"],
  ["тротуа́р", "trottoir", "n"],
  ["тру́дно", "difficilement", "adv"],
  ["трусливый", "lâche", "adj"],
  ["тру́сы", "slip", "n"],
  ["туалет", "toilettes", "n"],
  ["туда́", "là", "adv"],
  ["туман", "brouillard", "n"],
  ["туни́ка", "tunique", "n"],
  ["тупо́й", "obtus", "adj"],
  ["тусклый", "terne", "adj"],
  ["туфли́", "chaussure", "n"],
  ["ту́фля", "chaussure", "n"],
  ["ту́чка", "mocassin", "n"],
  ["ты́сяча", "mille", "adj"],
  ["тюрба́н", "turban", "n"],
  ["тюрьма́", "prison", "n", 1],
  ["тяжёлый", "lourd", "adj"],
  ["тяну́ть", "tirer", "v"],
  ["уважа́ние", "respect", "n"],
  ["уважа́ть", "respecter", "v"],
  ["ува́жение", "respect", "n"],
  ["уве́ренность", "certitude", "n"],
  ["увидеть", "voir", "v", 1],
  ["угожда́ть", "complaire", "v"],
  ["у́гол", "coin", "n", 1],
  ["у́голь", "charbon", "n", 1],
  ["удалённый", "éloigné", "adj"],
  ["удали́ть", "supprimer", "v"],
  ["ударе́ние", "accent tonique", "n"],
  ["уда́чный", "heureux", "adj"],
  ["удивле́ние", "étonnement", "n"],
  ["удивля́ться", "être surpris", "v"],
  ["удо́бный", "confortable", "adj"],
  ["удовле́творение", "satisfaction", "n"],
  ["уезжа́ть", "partir", "v"],
  ["уе́хать", "partir", "v"],
  ["у́жин", "dîner", "n", 1],
  ["узкий", "étroit", "adj"],
  ["уйти́", "partir", "v"],
  ["уко́л", "piqûre", "n"],
  ["у́лица", "rue", "n", 1],
  ["улыба́ться", "sourire", "v"],
  ["уме́ть", "pouvoir", "v"],
  ["умиля́ться", "s'attendrir", "v"],
  ["умный", "intelligent", "adj", 1],
  ["умола́ть", "supplier", "v"],
  ["умыва́ться", "se laver", "v"],
  ["университе́т", "université", "n", 1],
  ["упа́сть", "tomber", "v"],
  ["упражне́ние", "exercice", "n"],
  ["упрёк", "reproche", "n"],
  ["упру́гий", "élastique", "adj"],
  ["уразумева́ть", "saisir", "v"],
  ["у́ровень", "niveau", "n", 1],
  ["уродли́вый", "laid", "adj"],
  ["урожа́й", "récolte", "n"],
  ["уро́к", "leçon", "n", 1],
  ["успе́х", "succès", "n", 1],
  ["успоко́иться", "se calmer", "v"],
  ["устава́ние", "fatigue", "n"],
  ["усталый", "fatigué", "adj"],
  ["утвари́", "ustensiles", "n"],
  ["утвержда́ть", "affirmer", "v"],
  ["утка", "canard", "n"],
  ["утомля́ться", "se fatiguer", "v"],
  ["у́тро", "matin", "n", 1],
  ["у́хо", "oreille", "n", 1],
  ["уходи́ть", "partir", "v"],
  ["уча́ток", "tissu", "n"],
  ["уча́ть", "enseigner", "v"],
  ["уча́ться", "apprendre", "v"],
  ["у́чение", "doctrine", "n"],
  ["учени́к", "élève", "n"],
  ["учи́тель", "professeur", "n", 1],
  ["учи́ть", "apprendre, enseigner", "v", 1],
  ["учи́ться", "apprendre", "v"],
  ["файл", "fichier", "n"],
  ["факульте́т", "faculté", "n"],
  ["фами́лия", "nom de famille", "n", 1],
  ["февра́ль", "février", "n"],
  ["ферма", "ferme", "n"],
  ["фильм", "film", "n", 1],
  ["фина́льно", "enfin", "adv"],
  ["фиоле́товый", "violet", "adj"],
  ["фи́рма", "firme", "n", 1],
  ["флей́та", "flûte", "n"],
  ["фотоаппара́т", "appareil", "n"],
  ["фотогра́фия", "photo", "n", 1],
  ["францу́зский", "français", "adj"],
  ["фру́кт", "fruit", "n"],
  ["футбо́л", "football", "n", 1],
  ["футбо́лка", "t-shirt", "n"],
  ["халат", "peignoir", "n"],
  ["хара́ктер", "caractère", "n", 1],
  ["хвала́", "louange", "n"],
  ["хлеб", "pain", "n", 1],
  ["хло́пок", "coton", "n"],
  ["хмуриться", "froncer", "v"],
  ["ходи́ть", "aller (habituellement)", "v", 1],
  ["хозя́ин", "patron", "n", 1],
  ["хокке́й", "hockey", "n"],
  ["холоди́льник", "réfrigérateur", "n", 1],
  ["хо́лодно", "froid", "adj"],
  ["холодный", "froid", "adj", 1],
  ["хо́р", "chœur", "n"],
  ["хороший", "bon", "adj", 1],
  ["хорошо́", "bien", "n", 1],
  ["хоте́ть", "vouloir", "v", 1],
  ["храбрый", "courageux", "adj"],
  ["христиани́зм", "christianisme", "n"],
  ["хру́пкий", "fragile", "adj"],
  ["худо́жник", "peintre", "n", 1],
  ["цари́", "tsar", "n"],
  ["цвет", "couleur", "n", 1],
  ["цвето́к", "fleur", "n", 1],
  ["цель", "but", "n", 1],
  ["цена́", "prix", "n", 1],
  ["центр", "centre", "n", 1],
  ["центра́льный", "central", "adj"],
  ["це́рковь", "église", "n"],
  ["цифра", "chiffre", "n"],
  ["чай", "thé", "n", 1],
  ["чайни́к", "théière", "n"],
  ["час", "heure", "n", 1],
  ["ча́стный", "privé", "adj"],
  ["часто́", "souvent", "adv"],
  ["чек", "ticket de caisse", "n", 1],
  ["челове́к", "personne", "n", 1],
  ["чемода́н", "valise", "n", 1],
  ["чемпио́н", "champion", "n", 1],
  ["черепаха", "tortue", "n"],
  ["чёрный", "noir", "adj"],
  ["чесно́й", "honnête", "adj"],
  ["чесно́к", "ail", "n"],
  ["чесно́сть", "honnêteté", "n"],
  ["честный", "honnête", "adj"],
  ["честь", "honneur", "n"],
  ["четве́рг", "jeudi", "n", 1],
  ["четве́рть", "quart", "n"],
  ["четы́ре", "quatre", "adj"],
  ["четыре́ндцать", "quatorze", "adj"],
  ["число́", "nombre", "n", 1],
  ["чи́стый", "pur", "adj"],
  ["чита́ть", "lire", "v", 1],
  ["что", "que, quoi", "n", 1],
  ["что́-то", "quelque chose", "adv"],
  ["чу́вство", "sentiment", "n", 1],
  ["чу́вствовать", "sentir", "v"],
  ["чулки", "bas", "n"],
  ["чуть", "à peine", "adv"],
  ["шанс", "chance", "n"],
  ["ша́пка", "bonnet", "n"],
  ["шари́ф", "écharpe", "n"],
  ["шарф", "foulard", "n"],
  ["шво́", "couture", "n"],
  ["шёлк", "soie", "n"],
  ["шеро́хлый", "rugueux", "adj"],
  ["шероховатый", "rugueux", "adj"],
  ["шерсть", "laine", "n"],
  ["шестна́дцать", "seize", "adj"],
  ["шесть", "six", "adj"],
  ["шестьдеся́т", "soixante", "adj"],
  ["шея́", "cou", "n"],
  ["широкий", "large", "adj"],
  ["шкаф", "armoire", "n"],
  ["шко́ла", "école", "n", 1],
  ["шля́па", "chapeau", "n"],
  ["шокола́д", "chocolat", "n", 1],
  ["шорты́", "short", "n"],
  ["шосссе́", "chaussée", "n"],
  ["шпио́н", "espion", "n", 1],
  ["шуба", "fourrure", "n"],
  ["шум", "bruit", "n", 1],
  ["шума́ть", "faire du bruit", "v"],
  ["шу́тка", "blague", "n", 1],
  ["щедрый", "généreux", "adj"],
  ["щека́", "joue", "n"],
  ["щи", "soupe de chou", "n"],
  ["щико́лотка", "cheville", "n"],
  ["экза́мен", "examen", "n", 1],
  ["экра́н", "écran", "n"],
  ["экспе́рт", "expert", "n", 1],
  ["экспорт", "exporter", "v"],
  ["эпо́ха", "époque", "n"],
  ["эссе", "essai", "n"],
  ["эта́ж", "étage", "n", 1],
  ["юбка", "jupe", "n"],
  ["ю́рист", "juriste", "n"],
  ["я́блоко", "pomme", "n", 1],
  ["ягода", "baie", "n"],
  ["язы́к", "langue", "n", 1],
  ["яйцо́", "œuf", "n", 1],
  ["янва́рь", "janvier", "n"],
  ["яркий", "brillant", "adj", 1],
  ["я́щик", "tiroir", "n", 1],
];
