// GÉNÉRÉ PAR scripts/build-lexicon.mjs — NE PAS ÉDITER À LA MAIN.
//
// Index d'autocomplétion : le mot russe accentué, sa traduction, sa nature.
// Voir lib/vocabulary/autocomplete.ts pour la recherche.

/** n = nom, v = verbe, adj = adjectif, adv = adverbe ou mot de liaison. */
export type LexKind = "n" | "v" | "adj" | "adv";

/**
 * [mot accentué, traduction, nature] — et un 4e élément `1` quand l'entrée
 * vient d'une banque RELUE À LA MAIN.
 *
 * Tuple plutôt qu'objet : 1655 entrées, les noms de champs
 * pèseraient plus que les données.
 *
 * POURQUOI DISTINGUER. Le vocabulaire produit par un modèle ne se trompe
 * pas au hasard : il se trompe de façon PLAUSIBLE. La construction écarte
 * les déformations d'un mot connu, mais elle ne peut rien contre une
 * traduction inventée pour un mot qu'aucune banque ne contient. L'apprenant
 * doit donc pouvoir voir, dans la liste, ce qui a été vérifié et ce qui est
 * une proposition.
 */
export type LexEntry = readonly [string, string, LexKind] | readonly [string, string, LexKind, 1];

export const LEXICON: readonly LexEntry[] = [
  ["абрико́с", "abricot", "n"],
  ["а́вгуст", "août", "n"],
  ["авеню́", "avenue", "n"],
  ["авто́бус", "bus", "n", 1],
  ["автомоби́ль", "automobile", "n", 1],
  ["а́втор", "auteur", "n", 1],
  ["адвока́т", "avocat", "n", 1],
  ["а́дрес", "adresse", "n", 1],
  ["актри́са", "actrice", "n", 1],
  ["альбо́м", "album", "n", 1],
  ["ана́лиз", "analyse", "n", 1],
  ["а́нгел", "ange", "n", 1],
  ["англи́йский", "anglais", "adj"],
  ["апельси́н", "orange", "n"],
  ["апре́ль", "avril", "n"],
  ["апте́ка", "pharmacie", "n"],
  ["а́рмия", "armée", "n", 1],
  ["арте́рия", "artère", "n"],
  ["арти́ст", "acteur", "n"],
  ["а́тлас", "satin", "n"],
  ["аэропо́рт", "aéroport", "n", 1],
  ["ба́бочка", "papillon", "n"],
  ["ба́бушка", "grand-mère", "n", 1],
  ["балко́н", "balcon", "n"],
  ["бана́н", "banane", "n"],
  ["банк", "banque", "n"],
  ["ба́нка", "bocal", "n", 1],
  ["бараба́н", "tambour", "n"],
  ["бассе́йн", "piscine", "n", 1],
  ["батаре́я", "batterie", "n"],
  ["бег", "course", "n"],
  ["бе́гать", "courir", "v", 1],
  ["бедро́", "cuisse", "n"],
  ["бежа́ть", "courir", "v", 1],
  ["безопа́сный", "sûr", "adj"],
  ["бе́лка", "écureuil", "n"],
  ["бе́лый", "blanc", "adj"],
  ["беспоко́иться", "s'inquiéter", "v"],
  ["беспоко́йство", "inquiétude", "n"],
  ["бесполе́зный", "inutile", "adj"],
  ["Би́блия", "Bible", "n"],
  ["биле́т", "billet", "n", 1],
  ["бинт", "bandage", "n"],
  ["благодари́ть", "remercier", "v"],
  ["благода́рность", "gratitude", "n"],
  ["бледне́ть", "pâlir", "v"],
  ["бле́дный", "pâle", "adj"],
  ["блёклый", "terne", "adj"],
  ["блестя́щий", "brillant", "adj"],
  ["ближа́йший", "prochain", "adj"],
  ["бли́зко", "près", "adv"],
  ["блу́зка", "blouse", "n"],
  ["блю́до", "plat", "n", 1],
  ["Бог", "Dieu", "n"],
  ["бока́л", "verre (à pied)", "n", 1],
  ["боле́зненный", "douloureux", "adj"],
  ["боле́знь", "maladie", "n", 1],
  ["боль", "douleur", "n", 1],
  ["больни́ца", "hôpital", "n", 1],
  ["больни́чный", "arrêt maladie", "n"],
  ["большо́й", "grand", "adj", 1],
  ["борщ", "bortsch", "n"],
  ["босс", "patron", "n"],
  ["боя́ться", "craindre", "v"],
  ["бра́вый", "brave", "adj"],
  ["брани́ть", "injurier", "v"],
  ["брасле́т", "bracelet", "n", 1],
  ["брат", "frère", "n", 1],
  ["брать", "prendre", "v", 1],
  ["брони́рование", "réservation", "n"],
  ["брони́ровать", "réserver", "v"],
  ["брю́ки", "pantalon", "n"],
  ["буди́ть", "réveiller", "v"],
  ["бу́дущий", "futur", "adj"],
  ["бума́га", "papier", "n", 1],
  ["бухга́лтер", "comptable", "n"],
  ["бы́стро", "vite", "adv"],
  ["бы́стрый", "rapide", "adj"],
  ["быть", "être (futur)", "v", 1],
  ["бюро́", "bureau", "n"],
  ["ваго́н", "wagon", "n"],
  ["ва́нна", "baignoire", "n"],
  ["ва́нная", "salle de bain", "n"],
  ["варе́нье", "confiture", "n"],
  ["вари́ть", "cuire", "v"],
  ["ваш", "votre", "adj"],
  ["вверх", "haut", "adv"],
  ["вводи́ть", "entrer", "v"],
  ["ве́дьма", "sorcière", "n", 1],
  ["ве́жливость", "politesse", "n"],
  ["ве́жливый", "poli", "adj"],
  ["век", "siècle", "n", 1],
  ["веле́ть", "commander", "v"],
  ["вели́кий", "grand", "adj"],
  ["вели́чество", "majesté", "n"],
  ["велосипе́д", "vélo", "n", 1],
  ["вельве́т", "velours côtelé", "n"],
  ["ве́на", "veine", "n"],
  ["ве́ра", "foi", "n"],
  ["ве́рно", "exactement", "adv"],
  ["ве́рность", "fidélité", "n"],
  ["верну́ться", "retourner", "v"],
  ["ве́рный", "fidèle", "adj"],
  ["вероя́тность", "probabilité", "n"],
  ["верте́ться", "tourner", "v"],
  ["ве́рую", "croire", "v"],
  ["вес", "poids", "n"],
  ["весёлый", "gai", "adj"],
  ["ве́ский", "lourd", "adj"],
  ["весна́", "printemps", "n", 1],
  ["весьма́", "fort", "adv"],
  ["ве́тер", "vent", "n"],
  ["ве́чер", "soir", "n", 1],
  ["вечери́нка", "soirée", "n", 1],
  ["взволно́ванный", "agité", "adj"],
  ["вздыха́ть", "soupirer", "v"],
  ["взять", "prendre", "v", 1],
  ["вид", "aspect", "n", 1],
  ["ви́деть", "voir", "v", 1],
  ["ви́за", "visa", "n"],
  ["визи́т", "visite", "n"],
  ["викто́рия", "victoire", "n"],
  ["вила́", "fourchette", "n"],
  ["вина́", "culpabilité", "n"],
  ["вино́", "vin", "n", 1],
  ["виногра́д", "raisin", "n"],
  ["вкус", "goût", "n", 1],
  ["вку́сный", "délicieux", "adj", 1],
  ["владе́лец", "propriétaire", "n", 1],
  ["вла́жный", "humide", "adj"],
  ["власть", "pouvoir", "n", 1],
  ["влия́ние", "influence", "n"],
  ["вме́сте", "ensemble", "adv"],
  ["вниз", "bas", "adv"],
  ["внизу́", "en bas", "adv"],
  ["внима́ние", "attention", "n", 1],
  ["внук", "petit-fils", "n"],
  ["внутри́", "dedans", "adv"],
  ["вну́чка", "petite-fille", "n"],
  ["во́гнутый", "concave", "adj"],
  ["вода́", "eau", "n", 1],
  ["води́тель", "conducteur", "n", 1],
  ["во́дка", "vodka", "n", 1],
  ["вое́нный", "militaire", "adj"],
  ["возвраща́ться", "revenir", "v"],
  ["возмо́жность", "possibilité", "n", 1],
  ["возмуща́ться", "s'indigner", "v"],
  ["вознагради́ть", "récompenser", "v"],
  ["возража́ть", "s'opposer", "v"],
  ["во́зраст", "âge", "n", 1],
  ["во́ин", "guerrier", "n"],
  ["война́", "guerre", "n", 1],
  ["войти́", "entrer", "v"],
  ["вокза́л", "gare", "n", 1],
  ["волк", "loup", "n", 1],
  ["волне́ние", "émotion", "n"],
  ["волнова́ться", "s'émouvoir", "v"],
  ["во́лос", "cheveu", "n", 1],
  ["во́лосы", "cheveux", "n"],
  ["вообража́ть", "imaginer", "v"],
  ["вопро́с", "question", "n", 1],
  ["вор", "voleur", "n", 1],
  ["воробе́й", "moineau", "n"],
  ["воро́на", "corbeau", "n"],
  ["восемна́дцать", "dix-huit", "adj"],
  ["во́семь", "huit", "adj"],
  ["воскресе́нье", "dimanche", "n", 1],
  ["восхища́ться", "admirer", "v"],
  ["восхище́ние", "admiration", "n"],
  ["впереди́", "devant", "adv"],
  ["враг", "ennemi", "n", 1],
  ["вражде́бный", "hostile", "adj"],
  ["врач", "médecin", "n", 1],
  ["враща́ться", "tourner", "v"],
  ["вре́мя", "temps", "n", 1],
  ["всё", "tout", "adv"],
  ["всегда́", "toujours", "adv"],
  ["всего́", "total", "adv"],
  ["вско́ре", "bientôt", "adv"],
  ["вспомина́ть", "se souvenir", "v"],
  ["встава́ть", "se lever", "v", 1],
  ["вставля́ть", "coller", "v"],
  ["встать", "se lever", "v", 1],
  ["встре́тить", "rencontrer", "v", 1],
  ["встре́ча", "rencontre", "n", 1],
  ["встреча́ть", "rencontrer", "v", 1],
  ["вто́рник", "mardi", "n", 1],
  ["второ́й", "second", "adj"],
  ["вход", "entrée", "n", 1],
  ["входи́ть", "entrer", "v"],
  ["вчера́", "hier", "adv"],
  ["выбира́ть", "sélectionner", "v"],
  ["вы́бор", "choix", "n", 1],
  ["вы́езд", "départ", "n"],
  ["вы́здороветь", "guérir", "v"],
  ["вы́йти", "sortir", "v"],
  ["вы́пить", "boire", "v", 1],
  ["вы́пуклый", "convexe", "adj"],
  ["вы́резать", "couper", "v"],
  ["высо́кий", "haut", "adj"],
  ["вы́ступ", "speech", "n"],
  ["вы́учить", "apprendre (par cœur)", "v", 1],
  ["вы́ход", "sortie", "n", 1],
  ["выходи́ть", "sortir", "v"],
  ["гада́ть", "deviner", "v"],
  ["газе́та", "journal", "n", 1],
  ["га́лстук", "cravate", "n", 1],
  ["где́-то", "quelque part", "adv"],
  ["ге́ний", "génie", "n", 1],
  ["геро́й", "héros", "n", 1],
  ["ги́бкий", "flexible", "adj"],
  ["гита́ра", "guitare", "n"],
  ["глава́", "chapitre", "n", 1],
  ["гла́дкий", "lisse", "adj"],
  ["глаз", "œil", "n", 1],
  ["гла́сный", "voyelle", "n"],
  ["глубо́кий", "profond", "adj"],
  ["глу́пый", "bête", "adj"],
  ["гнев", "colère", "n", 1],
  ["гне́ваться", "se fâcher", "v"],
  ["говори́ть", "parler, dire", "v", 1],
  ["год", "an", "n"],
  ["голова́", "tête", "n", 1],
  ["го́лос", "voix", "n", 1],
  ["голубо́й", "bleu ciel", "adj"],
  ["гора́", "montagne", "n", 1],
  ["го́рдость", "fierté", "n"],
  ["го́рдый", "fier", "adj"],
  ["го́ре", "chagrin", "n"],
  ["го́род", "ville", "n", 1],
  ["го́рький", "amer", "adj"],
  ["горя́чий", "chaud", "adj"],
  ["господи́н", "monsieur", "n", 1],
  ["гости́ная", "salon", "n"],
  ["гости́ница", "hôtel", "n", 1],
  ["гость", "invité", "n", 1],
  ["госуда́рственный", "public", "adj"],
  ["госуда́рство", "État", "n"],
  ["гото́вить", "préparer, cuisiner", "v", 1],
  ["гра́дус", "degré", "n"],
  ["грамм", "gramme", "n"],
  ["грамма́тика", "grammaire", "n"],
  ["грани́ца", "frontière", "n"],
  ["гра́фик", "horaire", "n"],
  ["гра́фика", "graphique", "n"],
  ["гроза́", "orage", "n"],
  ["гром", "tonnerre", "n"],
  ["гро́мко", "fort", "adv"],
  ["гру́бый", "rude", "adj"],
  ["грудь", "poitrine", "n"],
  ["грузови́к", "camion", "n", 1],
  ["грусти́ть", "s'attrister", "v"],
  ["гру́стный", "triste", "adj"],
  ["грусть", "tristesse", "n"],
  ["гру́ша", "poire", "n"],
  ["гря́зный", "sale", "adj"],
  ["губа́", "lèvre", "n"],
  ["губерна́тор", "gouverneur", "n", 1],
  ["гуля́ть", "se promener", "v", 1],
  ["гусь", "oie", "n"],
  ["да", "oui", "adv"],
  ["дава́ть", "donner", "v", 1],
  ["далеко́", "loin", "adv"],
  ["да́льше", "plus loin", "adv"],
  ["да́ма", "dame", "n", 1],
  ["да́нные", "données", "n"],
  ["дари́ть", "offrir", "v"],
  ["дать", "donner", "v", 1],
  ["два", "deux", "adj"],
  ["два́дцать", "vingt", "adj"],
  ["двена́дцать", "douze", "adj"],
  ["дверь", "porte", "n", 1],
  ["дви́гать", "bouger", "v"],
  ["движе́ние", "mouvement", "n"],
  ["дви́нуть", "bouger", "v"],
  ["двор", "cour", "n", 1],
  ["дворяни́н", "noble", "n"],
  ["де́вочка", "fillette", "n", 1],
  ["де́вушка", "jeune fille", "n", 1],
  ["девяно́сто", "quatre-vingt-dix", "adj"],
  ["девятна́дцать", "dix-neuf", "adj"],
  ["де́вять", "neuf", "adj"],
  ["де́душка", "grand-père", "n", 1],
  ["дека́брь", "décembre", "n"],
  ["де́лать", "faire", "v", 1],
  ["де́латься", "être fait", "v"],
  ["делика́тный", "délicat", "adj"],
  ["де́ло", "affaire", "n", 1],
  ["день", "jour", "n", 1],
  ["де́ньги", "argent", "n"],
  ["де́рево", "arbre", "n", 1],
  ["держа́ть", "tenir", "v", 1],
  ["десе́рт", "dessert", "n", 1],
  ["десятиле́тие", "décennie", "n"],
  ["де́сять", "dix", "adj"],
  ["де́ти", "enfants", "n"],
  ["дива́н", "canapé", "n", 1],
  ["дире́ктор", "directeur", "n", 1],
  ["дли́нный", "long", "adj"],
  ["дли́ться", "durer", "v"],
  ["дневни́к", "journal intime", "n", 1],
  ["доброта́", "bonté", "n"],
  ["до́брый", "bon", "adj"],
  ["доверя́ть", "faire confiance", "v"],
  ["догово́р", "contrat", "n", 1],
  ["дождь", "pluie", "n", 1],
  ["дока́зывать", "prouver", "v"],
  ["докуме́нт", "document", "n", 1],
  ["должно́", "devoir", "v"],
  ["до́лжность", "poste", "n"],
  ["дом", "maison", "n", 1],
  ["дома́шний", "domestique, familial", "adj", 1],
  ["доро́га", "route", "n", 1],
  ["дорого́й", "cher, précieux", "adj", 1],
  ["доска́", "tableau", "n"],
  ["доста́точно", "assez", "adv"],
  ["дочь", "fille (de qqn)", "n", 1],
  ["дре́вний", "antique", "adj"],
  ["дрожа́ть", "trembler", "v"],
  ["друг", "ami", "n", 1],
  ["дружелю́бный", "amical", "adj"],
  ["ду́мать", "penser", "v", 1],
  ["духо́вка", "four", "n"],
  ["душ", "douche", "n"],
  ["душа́", "âme", "n", 1],
  ["дя́дя", "oncle", "n"],
  ["его́", "son, le sien", "n", 1],
  ["её", "son", "adj"],
  ["ёжик", "hérisson", "n"],
  ["е́здить", "aller (en véhicule)", "v", 1],
  ["есть", "manger", "v", 1],
  ["е́хать", "aller (en véhicule)", "v", 1],
  ["жале́ть", "regretter", "v"],
  ["жа́лованье", "traitement", "n"],
  ["жа́ловаться", "se plaindre", "v"],
  ["жа́лость", "pitié", "n"],
  ["жаль", "dommage", "adv"],
  ["жа́рить", "frire", "v"],
  ["жа́рко", "chaud", "adj"],
  ["жать", "moissonner", "v"],
  ["ждать", "attendre", "v", 1],
  ["же", "or", "adv"],
  ["жела́ть", "souhaiter", "v"],
  ["жёлтый", "jaune", "adj"],
  ["желу́док", "estomac", "n"],
  ["жена́", "épouse", "n", 1],
  ["жени́х", "fiancé", "n", 1],
  ["же́нщина", "femme", "n", 1],
  ["жёсткий", "dur", "adj"],
  ["жесто́кий", "cruel", "adj"],
  ["жи́вопись", "peinture", "n"],
  ["живо́т", "ventre", "n", 1],
  ["живо́тное", "animal", "n", 1],
  ["жи́дкий", "liquide", "adj"],
  ["жизнь", "vie", "n", 1],
  ["жить", "vivre, habiter", "v", 1],
  ["журна́л", "magazine", "n", 1],
  ["заба́вный", "amusant", "adj"],
  ["заболе́ть", "tomber malade", "v"],
  ["забыва́ть", "oublier", "v", 1],
  ["забы́ть", "oublier", "v", 1],
  ["зави́довать", "envier", "v"],
  ["за́висть", "envie", "n"],
  ["заво́д", "usine", "n"],
  ["за́втра", "demain", "adv"],
  ["за́втрак", "petit-déjeuner", "n", 1],
  ["за́втракать", "prendre le petit-déjeuner", "v", 1],
  ["загружа́ть", "charger", "v"],
  ["зада́ние", "mission", "n", 1],
  ["зада́ча", "tâche", "n", 1],
  ["зае́зд", "arrivée", "n"],
  ["заказа́ть", "commander", "v"],
  ["зака́нчивать", "terminer", "v", 1],
  ["зако́н", "loi", "n", 1],
  ["зако́нчить", "terminer", "v", 1],
  ["закрыва́ть", "fermer", "v", 1],
  ["закры́ть", "fermer", "v", 1],
  ["замёрзнуть", "geler", "v"],
  ["замеча́ть", "remarquer", "v"],
  ["за́мок", "château", "n", 1],
  ["за́навес", "rideau", "n"],
  ["занаве́ски", "rideaux", "n"],
  ["за́навесь", "rideau", "n"],
  ["занима́ться", "s'occuper", "v"],
  ["заня́тие", "occupation", "n"],
  ["занято́й", "occupé", "adj"],
  ["за́нятость", "occupation", "n"],
  ["за́пах", "odeur", "n", 1],
  ["записа́ть", "noter", "v"],
  ["за́пись", "note", "n", 1],
  ["заплати́ть", "payer", "v"],
  ["запре́т", "interdiction", "n"],
  ["запя́стье", "poignet", "n"],
  ["зарпла́та", "salaire", "n"],
  ["заря́дка", "chargeur", "n"],
  ["засту́пник", "intercesseur", "n"],
  ["зате́м", "ensuite", "adv"],
  ["зачёт", "validation", "n"],
  ["за́яц", "lièvre", "n"],
  ["звезда́", "étoile", "n", 1],
  ["звони́ть", "téléphoner", "v", 1],
  ["звоно́к", "sonnette", "n"],
  ["звук", "son", "n", 1],
  ["зда́ние", "bâtiment", "n", 1],
  ["здесь", "ici", "adv"],
  ["здоро́вый", "sain", "adj"],
  ["здоро́вье", "santé", "n", 1],
  ["здра́вствуйте", "bonjour", "v"],
  ["зелёный", "vert", "adj"],
  ["земля́", "terre", "n", 1],
  ["зе́ркало", "miroir", "n", 1],
  ["зима́", "hiver", "n", 1],
  ["зли́ться", "se fâcher", "v"],
  ["злой", "méchant", "adj"],
  ["змея́", "serpent", "n", 1],
  ["зна́ние", "connaissance", "n"],
  ["знать", "savoir, connaître", "v", 1],
  ["значе́ние", "signification", "n", 1],
  ["значо́к", "symbole", "n"],
  ["зонт", "parapluie", "n", 1],
  ["зуб", "dent", "n"],
  ["игра́", "jeu", "n", 1],
  ["игра́ть", "jouer", "v", 1],
  ["игро́к", "joueur", "n", 1],
  ["иде́я", "idée", "n", 1],
  ["иди́", "aller", "v"],
  ["идти́", "aller (à pied)", "v", 1],
  ["извине́ние", "excuses", "n"],
  ["извини́те", "excusez-moi", "v"],
  ["извини́ться", "s'excuser", "v"],
  ["извиня́ться", "s'excuser", "v"],
  ["изображе́ние", "image", "n"],
  ["изумля́ться", "s'étonner", "v"],
  ["изуча́ть", "étudier (à fond)", "v", 1],
  ["изучи́ть", "étudier (à fond)", "v", 1],
  ["ико́нка", "icône", "n"],
  ["име́ть", "avoir", "v"],
  ["импера́тор", "empereur", "n"],
  ["и́мпорт", "importer", "v"],
  ["и́мя", "prénom", "n", 1],
  ["инжене́р", "ingénieur", "n"],
  ["иногда́", "parfois", "adv"],
  ["инструме́нт", "instrument", "n"],
  ["интервью́", "entretien", "n"],
  ["интере́с", "intérêt", "n", 1],
  ["интере́сный", "intéressant", "adj", 1],
  ["интересова́ть", "intéresser", "v"],
  ["интерне́т", "internet", "n"],
  ["информа́ция", "information", "n", 1],
  ["иска́ть", "chercher", "v", 1],
  ["исключе́ние", "exception", "n"],
  ["иску́сство", "art", "n", 1],
  ["испо́лненный", "rempli", "adj"],
  ["испра́вить", "corriger", "v"],
  ["исправле́ние", "correction", "n"],
  ["испу́ганный", "effrayé", "adj"],
  ["испуга́ться", "s'effrayer", "v"],
  ["испыта́ть", "éprouver", "v"],
  ["иссле́дование", "recherche", "n", 1],
  ["и́стина", "vérité", "n"],
  ["исто́рия", "histoire", "n", 1],
  ["их", "leur", "adj"],
  ["ию́ль", "juillet", "n"],
  ["ию́нь", "juin", "n"],
  ["ка́бель", "câble", "n"],
  ["кабине́т", "bureau (pièce)", "n", 1],
  ["ка́ждый", "chaque", "adj"],
  ["кальсо́ны", "caleçon", "n"],
  ["камени́стый", "pierreux", "adj"],
  ["ка́мень", "pierre", "n", 1],
  ["капита́н", "capitaine", "n", 1],
  ["капу́ста", "chou", "n"],
  ["каранда́ш", "crayon", "n"],
  ["ка́рта", "carte", "n", 1],
  ["карти́на", "tableau", "n", 1],
  ["карто́фель", "pomme de terre", "n"],
  ["ка́рточка", "carte", "n"],
  ["карье́р", "carrière", "n"],
  ["карье́ра", "carrière", "n"],
  ["ка́сса", "caisse", "n"],
  ["касси́р", "caissier", "n"],
  ["кастрю́ля", "casserole", "n"],
  ["ката́ние", "patinage", "n"],
  ["ката́ться", "rouler", "v"],
  ["кафе́", "café", "n"],
  ["ка́ша", "bouillie", "n"],
  ["ка́шель", "toux", "n"],
  ["квадра́тный", "carré", "adj"],
  ["квалифици́рованный", "qualifié", "adj"],
  ["кварти́ра", "appartement", "n", 1],
  ["ке́дры", "chaussure de toile", "n"],
  ["ке́пка", "casquette", "n"],
  ["килогра́мм", "kilogramme", "n"],
  ["киломе́тр", "kilomètre", "n"],
  ["кино́", "cinéma", "n"],
  ["кисть", "main", "n"],
  ["кишка́", "intestin", "n"],
  ["клавиату́ра", "clavier", "n"],
  ["класс", "classe", "n"],
  ["класть", "poser (à plat)", "v", 1],
  ["клие́нт", "client", "n", 1],
  ["кли́кать", "cliquer", "v"],
  ["клони́ться", "se pencher", "v"],
  ["клуб", "club", "n", 1],
  ["ключ", "clé", "n", 1],
  ["кни́га", "livre", "n", 1],
  ["кно́пка", "bouton", "n"],
  ["князь", "prince", "n"],
  ["ковёр", "tapis", "n"],
  ["ко́врик", "petit tapis", "n"],
  ["когда́-то", "autrefois", "adv"],
  ["ко́жа", "peau", "n", 1],
  ["коза́", "chèvre", "n"],
  ["коле́но", "genou", "n"],
  ["коли́чество", "quantité", "n", 1],
  ["колле́га", "collègue", "n"],
  ["кольцо́", "bague", "n", 1],
  ["кома́нда", "équipe", "n", 1],
  ["команди́р", "commandant", "n", 1],
  ["ко́мната", "pièce", "n", 1],
  ["комо́д", "commode", "n"],
  ["компа́ния", "entreprise", "n", 1],
  ["компью́тер", "ordinateur", "n", 1],
  ["коне́ц", "fin", "n", 1],
  ["контра́кт", "contrat", "n"],
  ["контро́льная", "contrôle", "n"],
  ["конфере́нция", "conférence", "n"],
  ["конце́рт", "concert", "n", 1],
  ["конча́ть", "finir", "v"],
  ["ко́нчить", "finir", "v"],
  ["конь", "cheval", "n"],
  ["копи́ровать", "copier", "v"],
  ["кора́бль", "navire", "n", 1],
  ["ко́рень", "racine", "n"],
  ["коридо́р", "couloir", "n"],
  ["кори́чневый", "marron", "adj"],
  ["коро́бка", "boîte", "n"],
  ["коро́ва", "vache", "n"],
  ["короле́ва", "reine", "n", 1],
  ["коро́ль", "roi", "n", 1],
  ["коро́ткий", "court", "adj"],
  ["ко́смос", "espace", "n", 1],
  ["кость", "os", "n", 1],
  ["костю́м", "costume", "n", 1],
  ["кот", "chat", "n", 1],
  ["ко́фе", "café", "n"],
  ["ко́фта", "cardigan", "n"],
  ["ко́шка", "chatte", "n", 1],
  ["край", "bord", "n", 1],
  ["краса́", "beauté", "n"],
  ["краси́вый", "beau / belle", "adj", 1],
  ["кра́ска", "couleur", "n"],
  ["кра́ски", "peintures", "n"],
  ["красне́ть", "rougir", "v"],
  ["кра́сный", "rouge", "adj"],
  ["кре́сло", "fauteuil", "n", 1],
  ["криво́й", "courbe", "adj"],
  ["кри́зис", "crise", "n"],
  ["кри́тика", "critique", "n"],
  ["крича́ть", "crier", "v"],
  ["крова́ть", "lit", "n", 1],
  ["кро́вля", "couverture", "n"],
  ["кровь", "sang", "n", 1],
  ["кро́лик", "lapin", "n", 1],
  ["кро́мка", "bord", "n"],
  ["кро́ткий", "doux", "adj"],
  ["кро́ткой", "doux", "adj"],
  ["кро́ха", "miettes", "n"],
  ["кру́глый", "rond", "adj"],
  ["круго́м", "tout autour", "adv"],
  ["кру́жево", "dentelle", "n"],
  ["крути́ть", "tourner", "v"],
  ["крути́ться", "tourner", "v"],
  ["кры́са", "rat", "n", 1],
  ["кры́ша", "toit", "n", 1],
  ["кто́-то", "quelqu'un", "adv"],
  ["кузе́н", "cousin", "n", 1],
  ["кузи́на", "cousine", "n"],
  ["купе́ц", "marchand", "n"],
  ["купи́ть", "acheter", "v", 1],
  ["купю́ра", "billet", "n"],
  ["ку́рица", "poule", "n"],
  ["курс", "cours", "n", 1],
  ["курсо́р", "curseur", "n"],
  ["ку́ртка", "blouson", "n"],
  ["кусо́к", "morceau", "n", 1],
  ["ку́хня", "cuisine", "n", 1],
  ["ла́вка", "boutique", "n"],
  ["ла́дно", "d'accord", "adv"],
  ["ла́мпа", "lampe", "n", 1],
  ["ла́сковость", "tendresse", "n"],
  ["ла́сковый", "tendre", "adj"],
  ["леге́нда", "légende", "n", 1],
  ["лёгкий", "léger", "adj"],
  ["легко́", "facilement", "adv"],
  ["лёгкое", "poumon", "n"],
  ["легкомы́сленный", "léger", "adj"],
  ["лёд", "glace", "n"],
  ["ледяно́й", "glacé", "adj"],
  ["лежа́ть", "être couché", "v", 1],
  ["лезть", "grimper", "v"],
  ["лека́рство", "médicament", "n", 1],
  ["ле́кция", "conférence", "n"],
  ["лён", "lin", "n"],
  ["лес", "forêt", "n", 1],
  ["лесни́к", "forestier", "n"],
  ["ле́стница", "escalier", "n"],
  ["лета́ть", "voler, aller (en avion)", "v", 1],
  ["лете́ть", "voler, aller (en avion)", "v", 1],
  ["ле́то", "été", "n", 1],
  ["лечи́ть", "soigner", "v"],
  ["лечь", "se coucher", "v", 1],
  ["лимо́н", "citron", "n"],
  ["лиса́", "renard", "n"],
  ["лист", "feuille", "n"],
  ["литр", "litre", "n"],
  ["лифт", "ascenseur", "n", 1],
  ["лихора́дка", "fièvre", "n"],
  ["лицо́", "visage", "n", 1],
  ["лоб", "front", "n"],
  ["ло́дка", "barque", "n", 1],
  ["ложи́ться", "se coucher", "v", 1],
  ["ло́жка", "cuillère", "n"],
  ["ло́жный", "faux", "adj"],
  ["ложь", "mensonge", "n", 1],
  ["ло́коть", "coude", "n"],
  ["лось", "élan", "n"],
  ["ло́шадь", "cheval", "n", 1],
  ["лук", "oignon", "n", 1],
  ["луна́", "lune", "n", 1],
  ["люб", "amour", "n"],
  ["любе́зность", "courtoisie", "n"],
  ["любе́зный", "courtois", "adj"],
  ["люби́мый", "préféré", "adj"],
  ["люби́ть", "aimer", "v", 1],
  ["любо́вь", "amour", "n", 1],
  ["лю́ди", "gens", "n"],
  ["люк", "trappe", "n", 1],
  ["лю́стра", "lustre", "n"],
  ["лягу́шка", "grenouille", "n"],
  ["магази́н", "magasin", "n", 1],
  ["май", "mai", "n"],
  ["ма́йка", "débardeur", "n"],
  ["макаро́ны", "pâtes", "n"],
  ["ма́ленький", "petit", "adj", 1],
  ["ма́ло", "peu", "adj"],
  ["малы́ш", "bébé", "n", 1],
  ["ма́льчик", "garçon", "n", 1],
  ["ма́ма", "maman", "n", 1],
  ["март", "mars", "n"],
  ["маршру́т", "itinéraire", "n"],
  ["ма́сло", "beurre", "n", 1],
  ["ма́стер", "maître", "n"],
  ["ма́товый", "mat", "adj"],
  ["матч", "match", "n", 1],
  ["мать", "mère", "n", 1],
  ["маши́на", "voiture", "n", 1],
  ["мёд", "miel", "n"],
  ["медве́дь", "ours", "n", 1],
  ["ме́дленно", "lentement", "adv"],
  ["ме́дленный", "lent", "adj"],
  ["медсестра́", "infirmière", "n", 1],
  ["мел", "craie", "n", 1],
  ["ме́лкий", "peu profond", "adj"],
  ["мель", "haut-fond", "n", 1],
  ["ме́неджер", "gérant", "n", 1],
  ["меню́", "menu", "n"],
  ["ме́ра", "mesure", "n"],
  ["ме́сто", "endroit", "n", 1],
  ["ме́сяц", "mois", "n", 1],
  ["ме́тод", "méthode", "n", 1],
  ["метр", "mètre", "n"],
  ["метро́", "métro", "n", 1],
  ["мечта́", "rêve (souhait)", "n", 1],
  ["мечта́ть", "rêver", "v"],
  ["ми́лый", "cher", "adj"],
  ["мини́стр", "ministre", "n", 1],
  ["ми́нус", "moins", "adv"],
  ["мину́та", "minute", "n", 1],
  ["мир", "paix", "n"],
  ["мири́ться", "se réconcilier", "v"],
  ["ми́рный", "paisible", "adj"],
  ["мне́ние", "avis", "n"],
  ["мно́го", "beaucoup", "adj"],
  ["могу́щественный", "puissant", "adj"],
  ["мо́жно", "puis-je", "adv"],
  ["мозг", "cerveau", "n", 1],
  ["мои́", "mon", "adj"],
  ["мо́йка", "évier", "n"],
  ["мо́крый", "mouillé", "adj"],
  ["моли́тва", "prière", "n"],
  ["мо́лния", "éclair", "n"],
  ["молодо́й", "jeune", "adj", 1],
  ["молоко́", "lait", "n", 1],
  ["моме́нт", "moment", "n", 1],
  ["моне́та", "pièce", "n"],
  ["монито́р", "moniteur", "n"],
  ["мо́ре", "mer", "n", 1],
  ["морко́вь", "carotte", "n"],
  ["мост", "pont", "n", 1],
  ["мотоци́кл", "moto", "n", 1],
  ["мочь", "pouvoir", "v", 1],
  ["мощь", "puissance", "n"],
  ["мра́чный", "morose", "adj"],
  ["му́дрый", "sage", "adj"],
  ["муж", "mari", "n", 1],
  ["му́жество", "courage", "n"],
  ["мужчи́на", "homme", "n", 1],
  ["музе́й", "musée", "n", 1],
  ["му́зыка", "musique", "n", 1],
  ["музыка́нт", "musicien", "n"],
  ["му́ка", "farine", "n", 1],
  ["мураве́й", "fourmi", "n"],
  ["му́тный", "trouble", "adj"],
  ["му́читься", "se torturer", "v"],
  ["мы́слить", "penser", "v"],
  ["мысль", "pensée", "n", 1],
  ["мы́шца", "muscle", "n"],
  ["мышь", "souris", "n"],
  ["мя́гкий", "doux", "adj"],
  ["мя́со", "viande", "n", 1],
  ["мять", "froisser", "n", 1],
  ["мяч", "ballon", "n", 1],
  ["наблюда́ть", "observer", "v"],
  ["на́вык", "compétence", "n"],
  ["нагиба́ться", "se plier", "v"],
  ["награ́да", "récompense", "n"],
  ["наде́жда", "espoir", "n", 1],
  ["наде́яться", "espérer", "v"],
  ["назва́ние", "nom (d'une chose)", "n", 1],
  ["наказа́ние", "punition", "n"],
  ["наказа́ть", "punir", "v"],
  ["нале́во", "à gauche", "adv"],
  ["налива́ть", "verser", "v"],
  ["нало́г", "impôt", "n"],
  ["написа́ть", "écrire", "v", 1],
  ["напи́ток", "boisson", "n", 1],
  ["напра́во", "à droite", "adv"],
  ["напро́тив", "en face", "adv"],
  ["наро́д", "peuple", "n", 1],
  ["наслажда́ться", "jouir", "v"],
  ["на́сморк", "rhume", "n"],
  ["настрое́ние", "humeur", "n", 1],
  ["натя́гивать", "étirer", "v"],
  ["нау́ка", "science", "n", 1],
  ["нача́ло", "début", "n", 1],
  ["нача́льник", "chef", "n", 1],
  ["нача́ть", "commencer", "v", 1],
  ["начина́ть", "commencer", "v", 1],
  ["наш", "notre", "adj"],
  ["не́бо", "ciel", "n", 1],
  ["неве́рный", "infidèle", "adj"],
  ["неве́ста", "fiancée", "n", 1],
  ["неде́ля", "semaine", "n", 1],
  ["недоумева́ть", "être perplexe", "v"],
  ["нельзя́", "ne pas pouvoir", "adv"],
  ["неме́цкий", "allemand", "adj"],
  ["ненави́деть", "haïr", "v"],
  ["не́нависть", "haine", "n"],
  ["необходи́мость", "nécessité", "n"],
  ["непра́вильный", "incorrect", "adj"],
  ["не́рвный", "nerveux", "adj"],
  ["неро́вный", "inégal", "adj"],
  ["нёс", "il portait", "n", 1],
  ["не́сколько", "plusieurs", "adj"],
  ["несогла́сие", "désaccord", "n"],
  ["несправедли́вый", "injuste", "adj"],
  ["нести́", "porter (en marchant)", "v", 1],
  ["несча́стный", "malheureux", "adj"],
  ["несча́стье", "malheur", "n"],
  ["нет", "non", "adv"],
  ["неуда́ча", "échec", "n"],
  ["нече́стный", "malhonnête", "adj"],
  ["ни́зкий", "bas", "adj"],
  ["никогда́", "jamais", "adv"],
  ["ничего́", "rien", "adv"],
  ["но", "mais", "adv"],
  ["но́вое", "nouveau", "adj"],
  ["но́вость", "nouvelle", "n", 1],
  ["но́вый", "nouveau", "adj", 1],
  ["нога́", "jambe", "n", 1],
  ["но́гти", "ongle", "n"],
  ["нож", "couteau", "n", 1],
  ["но́мер", "numéro", "n", 1],
  ["нос", "nez", "n", 1],
  ["носи́ть", "porter (en marchant)", "v", 1],
  ["носки́", "chaussette", "n"],
  ["носо́к", "chaussette", "n"],
  ["ночь", "nuit", "n", 1],
  ["ноября́", "novembre", "n"],
  ["нра́ва", "mœurs", "n"],
  ["нра́виться", "plaire", "v"],
  ["нра́вственность", "moralité", "n"],
  ["ну́жно", "falloir", "adv"],
  ["обе́д", "déjeuner", "n", 1],
  ["обе́дать", "déjeuner", "v"],
  ["обижа́ться", "se vexer", "v"],
  ["о́блако", "nuage", "n"],
  ["обожа́ть", "adorer", "v"],
  ["обра́дуется", "se réjouir", "v"],
  ["о́браз", "image", "n", 1],
  ["образова́ние", "formation", "n", 1],
  ["обраща́ть", "tourner", "v"],
  ["о́бщество", "société", "n", 1],
  ["объявле́ние", "annonce", "n", 1],
  ["объясни́ть", "expliquer", "v", 1],
  ["объясня́ть", "expliquer", "v", 1],
  ["обы́чай", "coutume", "n"],
  ["обя́занности", "devoirs", "n"],
  ["обяза́тельно", "absolument", "adv"],
  ["о́вощ", "légume", "n"],
  ["овца́", "mouton", "n"],
  ["ого́нь", "feu", "n", 1],
  ["огуре́ц", "concombre", "n"],
  ["одева́ться", "s'habiller", "v"],
  ["оде́жда", "vêtement", "n", 1],
  ["одея́ло", "couverture", "n"],
  ["оди́н", "un", "adj"],
  ["оди́ннадцать", "onze", "adj"],
  ["одна́ко", "cependant", "adv"],
  ["одобре́ние", "approbation", "n"],
  ["озада́чивать", "déconcerter", "v"],
  ["о́зеро", "lac", "n", 1],
  ["океа́н", "océan", "n", 1],
  ["окно́", "fenêtre", "n", 1],
  ["октя́брь", "octobre", "n"],
  ["оле́нь", "cerf", "n"],
  ["опаса́ться", "redouter", "v"],
  ["опа́сный", "dangereux", "adj"],
  ["опера́тор", "opérateur", "n", 1],
  ["опера́ция", "opération", "n", 1],
  ["описа́ть", "décrire", "v"],
  ["опла́та", "paiement", "n"],
  ["опуска́ть", "baisser", "v"],
  ["опусти́ть", "baisser", "v"],
  ["о́пыт", "expérience", "n", 1],
  ["о́пытный", "expérimenté", "adj"],
  ["ора́нжевый", "orange", "adj"],
  ["орёл", "aigle", "n"],
  ["орке́стр", "orchestre", "n"],
  ["орфогра́фия", "orthographe", "n"],
  ["о́сень", "automne", "n", 1],
  ["осо́бенно", "surtout", "adv"],
  ["остава́ться", "rester", "v"],
  ["оставля́ть", "laisser", "v"],
  ["остана́вливаться", "s'arrêter", "v"],
  ["останови́ться", "s'arrêter", "v"],
  ["остано́вка", "arrêt", "n", 1],
  ["о́стров", "île", "n", 1],
  ["о́стрый", "pointu", "adj"],
  ["остуди́ть", "refroidir", "v"],
  ["отве́т", "réponse", "n", 1],
  ["отве́тить", "répondre", "v", 1],
  ["отвеча́ть", "répondre", "v", 1],
  ["отде́л", "service", "n", 1],
  ["отде́льно", "séparément", "adv"],
  ["о́тдых", "repos", "n", 1],
  ["отдыха́ть", "se reposer", "v", 1],
  ["оте́ль", "hôtel", "n"],
  ["оте́ц", "père", "n", 1],
  ["отказа́ть", "refuser", "v"],
  ["открыва́ть", "ouvrir", "v", 1],
  ["откры́ть", "ouvrir", "v", 1],
  ["отли́чный", "excellent", "adj"],
  ["отме́тка", "note", "n"],
  ["отойти́", "s'éloigner", "v"],
  ["отпра́вить", "envoyer", "v"],
  ["о́тпуск", "congé", "n", 1],
  ["отрица́ть", "nier", "v"],
  ["отходи́ть", "s'éloigner", "v"],
  ["отча́иваться", "désespérer", "v"],
  ["отча́яние", "désespoir", "n"],
  ["отчёт", "rapport", "n", 1],
  ["о́фис", "bureau", "n", 1],
  ["офице́р", "officier", "n", 1],
  ["охо́та", "chasse", "n"],
  ["охо́титься", "chasser", "v"],
  ["охо́тник", "chasseur", "n", 1],
  ["охра́нник", "gardien", "n", 1],
  ["оце́нка", "note", "n"],
  ["о́чень", "très", "adv"],
  ["оши́бка", "erreur", "n", 1],
  ["ощуща́ть", "percevoir", "v"],
  ["па́дать", "tomber", "v"],
  ["паке́т", "sachet", "n", 1],
  ["па́лец", "doigt", "n", 1],
  ["пальто́", "manteau", "n"],
  ["па́мять", "mémoire", "n"],
  ["пане́ль", "panneau", "n"],
  ["па́па", "papa", "n", 1],
  ["па́пка", "dossier", "n"],
  ["па́рень", "gars", "n", 1],
  ["парк", "parc", "n", 1],
  ["парко́вка", "parking", "n"],
  ["паро́ль", "mot de passe", "n"],
  ["па́спорт", "passeport", "n", 1],
  ["патриа́рх", "patriarche", "n"],
  ["паха́ть", "labourer", "v"],
  ["пацие́нт", "patient", "n", 1],
  ["певе́ц", "chanteur", "n"],
  ["пе́рвой", "premier", "adj"],
  ["пе́рвый", "premier", "adj"],
  ["перево́д", "traduction", "n"],
  ["перейти́", "traverser", "v"],
  ["перекрёсток", "carrefour", "n"],
  ["переме́на", "changement", "n"],
  ["перенести́", "transporter", "v"],
  ["переноси́ть", "transporter", "v"],
  ["переходи́ть", "traverser", "v"],
  ["пе́рец", "poivre", "n"],
  ["перо́", "stylo", "n"],
  ["перча́тка", "mitaine", "n"],
  ["пе́сня", "chanson", "n", 1],
  ["песо́к", "sable", "n"],
  ["песча́ный", "sableux", "adj"],
  ["пету́х", "coq", "n"],
  ["петь", "chanter", "v", 1],
  ["печа́ль", "tristesse", "n"],
  ["печа́льный", "mélancolique", "adj"],
  ["печа́тать", "imprimer", "v"],
  ["пе́чень", "foie", "n"],
  ["пече́нье", "biscuit", "n", 1],
  ["пиани́но", "piano", "n"],
  ["пи́во", "bière", "n", 1],
  ["пиджа́к", "veste", "n", 1],
  ["пижа́ма", "pyjama", "n"],
  ["пило́т", "pilote", "n", 1],
  ["пиро́г", "tarte", "n", 1],
  ["писа́тель", "écrivain", "n", 1],
  ["писа́ть", "écrire", "v", 1],
  ["письмо́", "lettre", "n", 1],
  ["пить", "boire", "v", 1],
  ["пла́вание", "natation", "n"],
  ["пла́вать", "nager, naviguer", "v", 1],
  ["пла́кать", "pleurer", "v", 1],
  ["план", "plan", "n", 1],
  ["плане́та", "planète", "n", 1],
  ["пла́стырь", "pansement", "n"],
  ["плати́ть", "payer", "v", 1],
  ["платфо́рма", "quai", "n"],
  ["пла́тье", "robe", "n", 1],
  ["пла́чу", "je pleure", "n", 1],
  ["плащ", "imperméable", "n"],
  ["плечо́", "épaule", "n", 1],
  ["плита́", "cuisinière", "n"],
  ["пло́ский", "plat", "adj"],
  ["пло́тный", "dense", "adj"],
  ["пло́хо", "mal", "adv"],
  ["плохо́й", "mauvais", "adj", 1],
  ["пло́щадь", "place", "n", 1],
  ["плыть", "nager, naviguer", "v", 1],
  ["плюс", "plus", "adv"],
  ["побе́да", "victoire", "n", 1],
  ["повёрнуть", "tourner", "v"],
  ["по́весть", "récit", "n"],
  ["повора́чивать", "tourner", "v"],
  ["повтори́ть", "répéter", "v", 1],
  ["повторя́ть", "répéter", "v", 1],
  ["пого́да", "météo", "n", 1],
  ["пода́рок", "cadeau", "n", 1],
  ["подборо́док", "menton", "n"],
  ["подва́л", "cave", "n", 1],
  ["поддержива́ть", "soutenir", "v"],
  ["подмасте́рье", "apprenti", "n"],
  ["поднима́ть", "lever", "v"],
  ["подня́ть", "lever", "v"],
  ["подойти́", "approcher", "v"],
  ["по́дпись", "signature", "n", 1],
  ["подру́га", "amie", "n", 1],
  ["подстила́ть", "couvrir", "v"],
  ["подтя́жки", "bretelle", "n"],
  ["поду́мать", "réfléchir", "v"],
  ["подходи́ть", "approcher", "v"],
  ["подъе́зд", "entrée d'immeuble", "n", 1],
  ["подыма́ть", "lever", "v"],
  ["по́езд", "train", "n", 1],
  ["пое́здка", "trajet", "n", 1],
  ["пожа́луйста", "s'il vous plaît", "n", 1],
  ["поза́втракать", "prendre le petit-déjeuner", "v", 1],
  ["позвони́ть", "téléphoner", "v", 1],
  ["по́здний", "tardif", "adj"],
  ["по́здно", "tard", "adv"],
  ["по́йма", "compréhension", "n"],
  ["поки́нуть", "quitter", "v"],
  ["покупа́ть", "acheter", "v", 1],
  ["поку́пка", "achat", "n"],
  ["пол", "sol", "n", 1],
  ["по́лдень", "midi", "n"],
  ["по́ле", "champ", "n", 1],
  ["поле́зный", "utile", "adj"],
  ["ползти́", "ramper", "v"],
  ["поликли́ника", "clinique", "n"],
  ["поли́тика", "politique", "n"],
  ["поли́ция", "police", "n", 1],
  ["по́лка", "étagère", "n"],
  ["по́лный", "plein", "adj"],
  ["полови́на", "moitié", "n"],
  ["положе́ние", "position", "n"],
  ["положи́ть", "poser (à plat)", "v", 1],
  ["полоте́нце", "serviette", "n", 1],
  ["получа́ть", "recevoir", "v", 1],
  ["получи́ть", "recevoir", "v", 1],
  ["помидо́р", "tomate", "n"],
  ["по́мнить", "se souvenir", "v", 1],
  ["помога́ть", "aider", "v"],
  ["по́мочь", "aider", "v"],
  ["помо́щник", "assistant", "n", 1],
  ["понеде́льник", "lundi", "n", 1],
  ["понима́ть", "comprendre", "v", 1],
  ["поня́ть", "comprendre", "v", 1],
  ["поп", "pope", "n"],
  ["попа́сть", "arriver", "v"],
  ["пораже́ние", "défaite", "n", 1],
  ["поре́зать", "couper", "v"],
  ["посети́ть", "visiter", "v"],
  ["посеща́ть", "visiter", "v"],
  ["посмотре́ть", "regarder", "v", 1],
  ["посте́ль", "literie", "n", 1],
  ["постро́ить", "construire", "v", 1],
  ["посу́да", "vaisselle", "n"],
  ["потоло́к", "plafond", "n"],
  ["пото́м", "puis", "adv"],
  ["потому́", "parce que", "adv"],
  ["по́чва", "sol", "n"],
  ["почёт", "honneur", "n"],
  ["по́чка", "rein", "n"],
  ["по́чта", "poste", "n"],
  ["почти́", "presque", "adv"],
  ["поэ́т", "poète", "n", 1],
  ["поэ́тому", "c'est pourquoi", "adv"],
  ["по́яс", "ceinture", "n"],
  ["пра́вда", "vérité", "n", 1],
  ["пра́вила", "règles", "n"],
  ["пра́вило", "règle", "n", 1],
  ["пра́вильность", "justesse", "n"],
  ["пра́вильный", "correct", "adj"],
  ["прави́тельство", "gouvernement", "n", 1],
  ["пра́во", "droit", "n", 1],
  ["правосу́дие", "justice", "n"],
  ["пра́здник", "fête", "n", 1],
  ["преда́ние", "légende", "n"],
  ["предполага́ть", "supposer", "v"],
  ["предпочита́ть", "préférer", "v"],
  ["предприя́тие", "entreprise", "n"],
  ["председа́тель", "président (d'assemblée)", "n", 1],
  ["представле́ние", "spectacle", "n"],
  ["президе́нт", "président", "n", 1],
  ["презира́ть", "mépriser", "v"],
  ["презре́ние", "mépris", "n"],
  ["пре́мия", "prime", "n"],
  ["преподава́тель", "professeur", "n"],
  ["преступле́ние", "crime", "n", 1],
  ["престу́пник", "criminel", "n", 1],
  ["прибыва́ть", "arriver", "v"],
  ["прибы́тие", "arrivée", "n"],
  ["приве́т", "salut", "n"],
  ["привиле́гии", "privilèges", "n"],
  ["пригласи́ть", "inviter", "v"],
  ["пригото́вить", "préparer", "v", 1],
  ["прие́хать", "arriver", "v"],
  ["признава́ться", "avouer", "v"],
  ["призна́ть", "reconnaître", "v"],
  ["при́зрак", "fantôme", "n", 1],
  ["прийти́", "venir", "v"],
  ["приказа́ть", "ordonner", "v"],
  ["приле́жный", "diligent", "adj"],
  ["приложе́ние", "application", "n"],
  ["приме́р", "exemple", "n", 1],
  ["приме́рно", "environ", "adv"],
  ["примире́ние", "réconciliation", "n"],
  ["приноси́ть", "apporter", "v"],
  ["при́нтер", "imprimante", "n"],
  ["принц", "prince", "n", 1],
  ["принце́сса", "princesse", "n", 1],
  ["при́нцип", "principe", "n"],
  ["приня́ть", "accepter", "v"],
  ["приро́да", "nature", "n", 1],
  ["пристрасти́ться", "s'accoutumer", "v"],
  ["приходи́ть", "arriver", "v"],
  ["причи́на", "raison", "n", 1],
  ["прия́тель", "copain", "n", 1],
  ["прия́тный", "agréable", "adj"],
  ["пробле́ма", "problème", "n", 1],
  ["проверя́ть", "vérifier", "v"],
  ["програ́мма", "programme", "n", 1],
  ["программи́ст", "programmeur", "n"],
  ["прогре́сс", "progrès", "n"],
  ["продава́ть", "vendre", "v"],
  ["продаве́ц", "vendeur", "n"],
  ["прода́жа", "vente", "n"],
  ["прода́ть", "vendre", "v"],
  ["проду́кты", "aliments", "n"],
  ["проезжа́ть", "passer", "v"],
  ["прое́кт", "projet", "n", 1],
  ["прозра́чный", "transparent", "adj"],
  ["произвести́", "produire", "v"],
  ["производи́ть", "produire", "v"],
  ["произво́дство", "production", "n"],
  ["произноше́ние", "prononciation", "n"],
  ["прокуро́р", "procureur", "n", 1],
  ["просвеща́ть", "instruire", "v"],
  ["проси́ть", "demander", "v", 1],
  ["проска́кивать", "franchir", "v"],
  ["простира́ться", "s'étendre", "v"],
  ["прости́те", "pardon", "v"],
  ["прости́ть", "pardonner", "v"],
  ["про́сто", "simplement", "adv"],
  ["просто́й", "simple", "adj"],
  ["простыня́", "drap", "n"],
  ["просыпа́ться", "se réveiller", "v"],
  ["профе́ссия", "profession", "n"],
  ["прохла́дный", "frais", "adj"],
  ["прохо́д", "passage", "n"],
  ["проце́ссор", "processeur", "n"],
  ["прочита́ть", "lire", "v", 1],
  ["про́чный", "solide", "adj"],
  ["про́шлый", "passé", "adj"],
  ["проща́ть", "pardonner", "v"],
  ["пры́гать", "sauter", "v"],
  ["пры́гнуть", "sauter", "v"],
  ["пря́мо", "tout droit", "adv"],
  ["прямо́й", "droit", "adj"],
  ["пти́ца", "oiseau", "n", 1],
  ["пу́говица", "bouton", "n"],
  ["пунктуа́ция", "ponctuation", "n"],
  ["пусто́й", "vide", "adj"],
  ["путеше́ствие", "voyage", "n", 1],
  ["путеше́ствовать", "voyager", "v"],
  ["путь", "chemin", "n", 1],
  ["пчела́", "abeille", "n"],
  ["пье́са", "pièce", "n"],
  ["пята́", "talon", "n"],
  ["пятна́дцать", "quinze", "adj"],
  ["пя́тница", "vendredi", "n"],
  ["пять", "cinq", "adj"],
  ["пятьдеся́т", "cinquante", "adj"],
  ["раб", "esclave", "n"],
  ["рабо́та", "travail", "n", 1],
  ["рабо́тать", "travailler", "v", 1],
  ["рабо́чий", "ouvrier", "n"],
  ["ра́бство", "esclavage", "n"],
  ["равноду́шие", "indifférence", "n"],
  ["равноме́рный", "uniforme", "adj"],
  ["ра́доваться", "se réjouir", "v"],
  ["ра́достный", "joyeux", "adj"],
  ["ра́дость", "joie", "n", 1],
  ["разбе́гаться", "s'élancer", "v"],
  ["разви́тие", "développement", "n"],
  ["разгово́р", "conversation", "n", 1],
  ["раздева́ться", "se déshabiller", "v"],
  ["разде́л", "rayon", "n"],
  ["раздража́ть", "irriter", "v"],
  ["раздражи́тельный", "irritable", "adj"],
  ["разме́р", "taille", "n", 1],
  ["разочарова́ние", "déception", "n"],
  ["разочарова́ться", "être déçu", "v"],
  ["разрежённый", "raréfié", "adj"],
  ["разъём", "connecteur", "n"],
  ["райо́н", "quartier", "n", 1],
  ["раке́тка", "raquette", "n"],
  ["ра́ма", "cadre", "n"],
  ["ра́на", "blessure", "n", 1],
  ["ра́нний", "précoce", "adj"],
  ["ра́но", "tôt", "adv"],
  ["раскида́ться", "s'étendre", "v"],
  ["расписа́ние", "horaire", "n"],
  ["расска́з", "récit", "n", 1],
  ["расска́зывать", "raconter", "v"],
  ["расстоя́ние", "distance", "n"],
  ["рассужде́ние", "raisonnement", "n"],
  ["расти́", "croître", "v"],
  ["расчёска", "peigne", "n"],
  ["ребёнок", "enfant", "n", 1],
  ["ре́вность", "jalousie", "n"],
  ["регистри́роваться", "s'enregistrer", "v"],
  ["ре́дко", "rarement", "adv"],
  ["режиссёр", "réalisateur", "n", 1],
  ["ре́зать", "couper", "v"],
  ["результа́т", "résultat", "n", 1],
  ["резюме́", "CV", "n"],
  ["рейс", "vol", "n", 1],
  ["река́", "rivière", "n", 1],
  ["рели́гия", "religion", "n"],
  ["рельс", "rail", "n"],
  ["реме́нь", "courroie", "n"],
  ["ремо́нт", "réparation", "n"],
  ["ремонти́ровать", "réparer", "v"],
  ["рестора́н", "restaurant", "n", 1],
  ["рефо́рма", "réforme", "n"],
  ["реце́пт", "recette", "n", 1],
  ["речь", "discours", "n", 1],
  ["реша́ть", "résoudre, décider", "v", 1],
  ["реше́ние", "décision", "n", 1],
  ["реши́ть", "résoudre, décider", "v", 1],
  ["рис", "riz", "n", 1],
  ["рисова́ть", "dessiner", "v"],
  ["рису́нок", "dessin", "n"],
  ["ро́вный", "régulier", "adj"],
  ["ро́дина", "patrie", "n"],
  ["роди́тели", "parents", "n"],
  ["роди́тель", "parent", "n"],
  ["ро́за", "rose", "n"],
  ["ро́зовый", "rose", "adj"],
  ["роль", "rôle", "n", 1],
  ["рома́н", "roman", "n", 1],
  ["рост", "croissance", "n", 1],
  ["рот", "bouche", "n", 1],
  ["руба́ха", "chemise", "n"],
  ["руба́шка", "chemise", "n", 1],
  ["рубль", "rouble", "n"],
  ["руга́ть", "gronder", "v"],
  ["руга́ться", "jurer", "v"],
  ["рука́", "main", "n", 1],
  ["ру́сский", "russe", "adj", 1],
  ["ру́чка", "stylo", "n"],
  ["ры́ба", "poisson", "n", 1],
  ["рыба́к", "pêcheur", "n"],
  ["рыда́ть", "pleurer", "v"],
  ["ры́нок", "marché", "n", 1],
  ["рюкза́к", "sac à dos", "n"],
  ["ря́дом", "à côté", "adv"],
  ["сад", "jardin", "n", 1],
  ["сади́ться", "s'asseoir", "v", 1],
  ["сайт", "site", "n"],
  ["сала́т", "salade", "n", 1],
  ["самолёт", "avion", "n", 1],
  ["сантиме́тр", "centimètre", "n"],
  ["сапо́г", "botte", "n"],
  ["сара́ю", "maison", "v"],
  ["са́хар", "sucre", "n", 1],
  ["сва́дьба", "mariage (cérémonie)", "n", 1],
  ["свари́ть", "cuire", "v"],
  ["све́жий", "frais", "adj"],
  ["све́рху", "en haut", "adv"],
  ["све́тлый", "clair", "adj"],
  ["свеча́", "bougie", "n"],
  ["свиде́тель", "témoin", "n", 1],
  ["свинья́", "cochon", "n", 1],
  ["свит", "lumière", "n"],
  ["сви́тер", "pull", "n"],
  ["свобо́да", "liberté", "n", 1],
  ["свобо́дный", "libre", "adj"],
  ["связь", "connexion", "n"],
  ["свято́й", "saint", "adj"],
  ["свяще́нник", "prêtre", "n", 1],
  ["сде́лать", "faire", "v", 1],
  ["сего́дня", "aujourd'hui", "adv"],
  ["сезо́н", "saison", "n"],
  ["сейча́с", "maintenant", "n", 1],
  ["секре́т", "secret", "n", 1],
  ["секрета́рь", "secrétaire", "n", 1],
  ["секу́нда", "seconde", "n", 1],
  ["семина́р", "séminaire", "n"],
  ["семна́дцать", "dix-sept", "adj"],
  ["семь", "sept", "adj"],
  ["се́мьдесят", "soixante-dix", "adj"],
  ["семья́", "famille", "n", 1],
  ["сена́тор", "sénateur", "n", 1],
  ["сентя́брь", "septembre", "n"],
  ["сервирова́ть", "servir", "v"],
  ["серди́тый", "fâché", "adj"],
  ["се́рдце", "cœur", "n", 1],
  ["сериа́л", "série", "n", 1],
  ["сертифика́т", "certificat", "n"],
  ["се́рый", "gris", "adj"],
  ["серьёзный", "sérieux", "adj"],
  ["сестра́", "sœur", "n", 1],
  ["сесть", "s'asseoir", "v", 1],
  ["сеть", "réseau", "n"],
  ["се́ять", "semer", "v"],
  ["сза́ди", "derrière", "adv"],
  ["сиде́ть", "s'asseoir", "v"],
  ["си́ла", "force", "n", 1],
  ["си́льный", "fort", "adj"],
  ["си́ний", "bleu (foncé)", "adj", 1],
  ["систе́ма", "système", "n", 1],
  ["сказа́ть", "dire", "v", 1],
  ["ска́зка", "conte", "n", 1],
  ["ска́нер", "scanner", "n"],
  ["скача́ть", "télécharger", "v"],
  ["скеле́т", "squelette", "n"],
  ["склони́ться", "se courber", "v"],
  ["сковорода́", "poêle", "n"],
  ["ско́лько", "combien", "adv"],
  ["скоре́е", "plutôt", "adv"],
  ["ско́ро", "bientôt", "adv"],
  ["ско́рость", "vitesse", "n"],
  ["скри́пка", "violon", "n"],
  ["скро́мность", "modestie", "n"],
  ["скро́мный", "modeste", "adj"],
  ["ску́ка", "ennui", "n"],
  ["скульпту́ра", "sculpture", "n"],
  ["скупо́й", "avare", "adj"],
  ["скуча́ть", "s'ennuyer", "v"],
  ["ску́чный", "ennuyeux", "adj"],
  ["сла́бость", "faiblesse", "n"],
  ["сла́бый", "faible", "adj"],
  ["сла́ва", "gloire", "n"],
  ["сла́дкий", "gentil", "adj"],
  ["сле́дствие", "conséquence", "n"],
  ["слива́", "prune", "n"],
  ["слова́рь", "dictionnaire", "n"],
  ["сло́во", "mot", "n", 1],
  ["сло́жный", "compliqué", "adj"],
  ["слуга́", "serviteur", "n"],
  ["слу́жба", "service", "n"],
  ["служи́ть", "servir", "v"],
  ["слу́чай", "cas", "n", 1],
  ["слу́шать", "écouter", "v", 1],
  ["слы́шать", "entendre", "v", 1],
  ["сме́лость", "courage", "n"],
  ["сме́лый", "courageux", "adj"],
  ["смерть", "mort", "n", 1],
  ["смех", "rire", "n", 1],
  ["сме́шивать", "mélanger", "v"],
  ["смея́ться", "rire", "v"],
  ["смире́ние", "humilité", "n"],
  ["смирённый", "humble", "adj"],
  ["смотре́ть", "regarder", "v", 1],
  ["смысл", "sens", "n", 1],
  ["снару́жи", "dehors", "adv"],
  ["снача́ла", "d'abord", "adv"],
  ["снег", "neige", "n", 1],
  ["соба́ка", "chien", "n", 1],
  ["собра́ние", "réunion", "n", 1],
  ["собы́тие", "événement", "n", 1],
  ["совсе́м", "complètement", "adv"],
  ["согла́сие", "accord", "n"],
  ["согласи́ться", "consentir", "v"],
  ["согла́сный", "consonne", "n"],
  ["соглаше́ние", "accord", "n"],
  ["сожале́ние", "regret", "n"],
  ["сожале́ть", "regretter", "v"],
  ["созерца́ть", "contempler", "v"],
  ["сознава́ть", "admettre", "v"],
  ["сок", "jus", "n", 1],
  ["солда́т", "soldat", "n", 1],
  ["солёный", "salé", "adj"],
  ["со́лнце", "soleil", "n", 1],
  ["соль", "sel", "n", 1],
  ["сомнева́ться", "douter", "v"],
  ["сомне́ние", "doute", "n"],
  ["сон", "rêve", "n", 1],
  ["сообще́ние", "message", "n", 1],
  ["сооруже́ние", "ouvrage", "n"],
  ["со́рок", "quarante", "adj"],
  ["соро́ка", "pie", "n"],
  ["сосе́д", "voisin", "n", 1],
  ["сосе́дка", "voisine", "n", 1],
  ["сотру́дник", "employé", "n"],
  ["сохрани́ть", "enregistrer", "v"],
  ["сочу́вствовать", "compatir", "v"],
  ["спа́льня", "chambre à coucher", "n"],
  ["спаси́бо", "merci", "n", 1],
  ["спать", "dormir", "v"],
  ["специали́ст", "spécialiste", "n", 1],
  ["спе́шить", "se dépêcher", "v"],
  ["спина́", "dos", "n", 1],
  ["спи́сок", "liste", "n", 1],
  ["споко́йно", "calmement", "adv"],
  ["споко́йный", "calme", "adj"],
  ["споко́йствие", "calme", "n"],
  ["спо́рить", "discuter", "v"],
  ["спорт", "sport", "n"],
  ["спо́соб", "moyen", "n", 1],
  ["справедли́вый", "juste", "adj"],
  ["спра́шивать", "demander", "v"],
  ["сра́зу", "tout de suite", "adv"],
  ["среда́", "mercredi", "n"],
  ["сре́дний", "moyen", "adj"],
  ["срок", "délai", "n", 1],
  ["ссо́риться", "se disputer", "v"],
  ["ссы́лка", "lien", "n"],
  ["стака́н", "verre", "n", 1],
  ["ста́нция", "station", "n", 1],
  ["стари́к", "vieillard", "n", 1],
  ["ста́рый", "vieux", "adj", 1],
  ["статья́", "article", "n", 1],
  ["ствол", "tronc", "n"],
  ["стекло́", "verre", "n"],
  ["стена́", "mur", "n", 1],
  ["стихотворе́ние", "poème", "n"],
  ["сто", "cent", "adj"],
  ["сто́имость", "coût", "n"],
  ["сто́ить", "coûter", "v"],
  ["стол", "table", "n", 1],
  ["столе́тие", "siècle", "n"],
  ["столи́ца", "capitale", "n"],
  ["стопа́", "pied", "n"],
  ["сторона́", "côté", "n", 1],
  ["стоя́ть", "être debout", "v", 1],
  ["страда́ть", "souffrir", "v"],
  ["страна́", "pays", "n", 1],
  ["страни́ца", "page", "n"],
  ["стра́стно", "passionnément", "adv"],
  ["страх", "peur", "n", 1],
  ["стресс", "stress", "n"],
  ["стро́ить", "construire", "v", 1],
  ["строй", "construction", "n"],
  ["стро́йка", "chantier", "n"],
  ["студе́нт", "étudiant", "n", 1],
  ["студе́нтка", "étudiante", "n"],
  ["стул", "chaise", "n", 1],
  ["стыд", "honte", "n"],
  ["стыди́ться", "avoir honte", "v"],
  ["суббо́та", "samedi", "n"],
  ["суд", "tribunal", "n", 1],
  ["судья́", "juge", "n", 1],
  ["су́мка", "sac", "n", 1],
  ["су́мма", "somme", "n", 1],
  ["су́мрачный", "sombre", "adj"],
  ["суп", "soupe", "n", 1],
  ["суста́в", "articulation", "n"],
  ["сухо́й", "sec", "adj"],
  ["сце́на", "scène", "n", 1],
  ["сце́ны", "plateau", "n"],
  ["счастли́вый", "heureux", "adj"],
  ["сча́стье", "bonheur", "n", 1],
  ["счёт", "addition", "n", 1],
  ["съесть", "manger", "v", 1],
  ["сын", "fils", "n"],
  ["сыр", "fromage", "n", 1],
  ["сюда́", "ici", "adv"],
  ["сюже́т", "intrigue", "n"],
  ["табле́тка", "comprimé", "n"],
  ["табли́ца", "tableau", "n"],
  ["та́йна", "mystère", "n", 1],
  ["такси́", "taxi", "n"],
  ["тала́нтливый", "talentueux", "adj"],
  ["там", "là", "adv"],
  ["тамо́жня", "douane", "n"],
  ["та́нец", "danse", "n", 1],
  ["танцева́ть", "danser", "v"],
  ["танцо́р", "danseur", "n"],
  ["таре́лка", "assiette", "n", 1],
  ["твёрдый", "dur", "adj"],
  ["твой", "ton", "adj"],
  ["теа́тр", "théâtre", "n", 1],
  ["теку́щий", "actuel", "adj"],
  ["телеви́зор", "téléviseur", "n", 1],
  ["телефо́н", "téléphone", "n", 1],
  ["те́ло", "corps", "n"],
  ["тёмный", "sombre", "adj"],
  ["температу́ра", "température", "n"],
  ["те́ннис", "tennis", "n"],
  ["тень", "ombre", "n", 1],
  ["тео́рия", "théorie", "n"],
  ["тепе́рь", "à présent", "adv"],
  ["тёплый", "chaud (temps)", "adj", 1],
  ["терпе́ть", "supporter", "v"],
  ["терра́са", "terrasse", "n"],
  ["тест", "test", "n"],
  ["тётя", "tante", "n", 1],
  ["ти́хо", "doucement", "adv"],
  ["ткань", "tissu", "n"],
  ["това́р", "marchandise", "n"],
  ["това́рищ", "camarade", "n", 1],
  ["толка́ть", "pousser", "v"],
  ["толкну́ть", "pousser", "v"],
  ["то́лстой", "épais", "adj"],
  ["то́лстый", "épais", "adj"],
  ["то́лько", "seulement", "adv"],
  ["то́нкий", "fin", "adj"],
  ["торго́вля", "commerce", "n"],
  ["торт", "gâteau", "n", 1],
  ["трава́", "herbe", "n"],
  ["тради́ция", "tradition", "n"],
  ["трамва́й", "tramway", "n"],
  ["тра́та", "dépense", "n"],
  ["тра́ты", "dépenses", "n"],
  ["трево́га", "inquiétude", "n"],
  ["тре́нер", "entraîneur", "n", 1],
  ["треть", "tiers", "n"],
  ["треуго́льный", "triangulaire", "adj"],
  ["три", "trois", "adj"],
  ["три́дцать", "trente", "adj"],
  ["трина́дцать", "treize", "adj"],
  ["тротуа́р", "trottoir", "n"],
  ["тру́дно", "difficilement", "adv"],
  ["трусли́вый", "lâche", "adj"],
  ["трусы́", "slip", "n"],
  ["туале́т", "toilettes", "n"],
  ["туда́", "là", "adv"],
  ["тума́н", "brouillard", "n"],
  ["туни́ка", "tunique", "n"],
  ["тупо́й", "obtus", "adj"],
  ["ту́склый", "terne", "adj"],
  ["ту́фли", "chaussure", "n"],
  ["ту́фля", "chaussure", "n"],
  ["ту́чка", "mocassin", "n"],
  ["ты́сяча", "mille", "adj"],
  ["тюрба́н", "turban", "n"],
  ["тюрьма́", "prison", "n", 1],
  ["тяжёлый", "lourd", "adj"],
  ["тяну́ть", "tirer", "v"],
  ["уважа́ть", "respecter", "v"],
  ["уваже́ние", "respect", "n"],
  ["уве́ренность", "certitude", "n"],
  ["уви́деть", "voir", "v", 1],
  ["угожда́ть", "complaire", "v"],
  ["у́гол", "coin", "n", 1],
  ["у́голь", "charbon", "n", 1],
  ["удалённый", "éloigné", "adj"],
  ["удали́ть", "supprimer", "v"],
  ["ударе́ние", "accent tonique", "n"],
  ["уда́чный", "heureux", "adj"],
  ["удивле́ние", "étonnement", "n"],
  ["удивля́ться", "être surpris", "v"],
  ["удо́бный", "confortable", "adj"],
  ["удовлетворе́ние", "satisfaction", "n"],
  ["уезжа́ть", "partir", "v"],
  ["уе́хать", "partir", "v"],
  ["у́жин", "dîner", "n", 1],
  ["у́зкий", "étroit", "adj"],
  ["уйти́", "partir", "v"],
  ["уко́л", "piqûre", "n"],
  ["у́лица", "rue", "n", 1],
  ["улыба́ться", "sourire", "v"],
  ["уме́ть", "pouvoir", "v"],
  ["умиля́ться", "s'attendrir", "v"],
  ["у́мный", "intelligent", "adj", 1],
  ["умыва́ться", "se laver", "v"],
  ["университе́т", "université", "n", 1],
  ["упа́сть", "tomber", "v"],
  ["упражне́ние", "exercice", "n"],
  ["упрёк", "reproche", "n"],
  ["упру́гий", "élastique", "adj"],
  ["у́ровень", "niveau", "n", 1],
  ["уро́дливый", "laid", "adj"],
  ["урожа́й", "récolte", "n"],
  ["уро́к", "leçon", "n", 1],
  ["успе́х", "succès", "n", 1],
  ["успоко́иться", "se calmer", "v"],
  ["уста́лый", "fatigué", "adj"],
  ["у́твари", "ustensiles", "n"],
  ["утвержда́ть", "affirmer", "v"],
  ["у́тка", "canard", "n"],
  ["утомля́ться", "se fatiguer", "v"],
  ["у́тро", "matin", "n", 1],
  ["у́хо", "oreille", "n", 1],
  ["уходи́ть", "partir", "v"],
  ["уче́ние", "doctrine", "n"],
  ["учени́к", "élève", "n"],
  ["учи́тель", "professeur", "n", 1],
  ["учи́ть", "apprendre, enseigner", "v", 1],
  ["учи́ться", "apprendre", "v"],
  ["файл", "fichier", "n"],
  ["факульте́т", "faculté", "n"],
  ["фами́лия", "nom de famille", "n", 1],
  ["февра́ль", "février", "n"],
  ["фе́рма", "ferme", "n"],
  ["фильм", "film", "n", 1],
  ["фиоле́товый", "violet", "adj"],
  ["фи́рма", "firme", "n", 1],
  ["фле́йта", "flûte", "n"],
  ["фотоаппара́т", "appareil", "n"],
  ["фотогра́фия", "photo", "n", 1],
  ["францу́зский", "français", "adj"],
  ["фрукт", "fruit", "n"],
  ["футбо́л", "football", "n", 1],
  ["футбо́лка", "t-shirt", "n"],
  ["хала́т", "peignoir", "n"],
  ["хара́ктер", "caractère", "n", 1],
  ["хвала́", "louange", "n"],
  ["хлеб", "pain", "n", 1],
  ["хлопо́к", "coton", "n"],
  ["хму́риться", "froncer", "v"],
  ["ходи́ть", "aller (habituellement)", "v", 1],
  ["хозя́ин", "patron", "n", 1],
  ["хокке́й", "hockey", "n"],
  ["холоди́льник", "réfrigérateur", "n", 1],
  ["хо́лодно", "froid", "adj"],
  ["холо́дный", "froid", "adj", 1],
  ["хор", "chœur", "n"],
  ["хоро́ший", "bon", "adj", 1],
  ["хорошо́", "bien", "n", 1],
  ["хоте́ть", "vouloir", "v", 1],
  ["хра́брый", "courageux", "adj"],
  ["хру́пкий", "fragile", "adj"],
  ["худо́жник", "peintre", "n", 1],
  ["цари́", "tsar", "n"],
  ["цвет", "couleur", "n", 1],
  ["цвето́к", "fleur", "n", 1],
  ["цель", "but", "n", 1],
  ["цена́", "prix", "n", 1],
  ["центр", "centre", "n", 1],
  ["центра́льный", "central", "adj"],
  ["це́рковь", "église", "n"],
  ["ци́фра", "chiffre", "n"],
  ["чай", "thé", "n", 1],
  ["ча́йник", "théière", "n"],
  ["час", "heure", "n", 1],
  ["ча́стный", "privé", "adj"],
  ["ча́сто", "souvent", "adv"],
  ["чек", "ticket de caisse", "n", 1],
  ["челове́к", "personne", "n", 1],
  ["чемода́н", "valise", "n", 1],
  ["чемпио́н", "champion", "n", 1],
  ["черепа́ха", "tortue", "n"],
  ["чёрный", "noir", "adj"],
  ["чесно́к", "ail", "n"],
  ["че́стный", "honnête", "adj"],
  ["честь", "honneur", "n"],
  ["четве́рг", "jeudi", "n", 1],
  ["че́тверть", "quart", "n"],
  ["четы́ре", "quatre", "adj"],
  ["число́", "nombre", "n", 1],
  ["чи́стый", "pur", "adj"],
  ["чита́ть", "lire", "v", 1],
  ["что", "que, quoi", "n", 1],
  ["что́-то", "quelque chose", "adv"],
  ["чу́вство", "sentiment", "n", 1],
  ["чу́вствовать", "sentir", "v"],
  ["чулки́", "bas", "n"],
  ["чуть", "à peine", "adv"],
  ["шанс", "chance", "n"],
  ["ша́пка", "bonnet", "n"],
  ["шарф", "foulard", "n"],
  ["шёлк", "soie", "n"],
  ["шерохова́тый", "rugueux", "adj"],
  ["шерсть", "laine", "n"],
  ["шестна́дцать", "seize", "adj"],
  ["шесть", "six", "adj"],
  ["шестьдеся́т", "soixante", "adj"],
  ["ше́я", "cou", "n"],
  ["широ́кий", "large", "adj"],
  ["шкаф", "armoire", "n"],
  ["шко́ла", "école", "n", 1],
  ["шля́па", "chapeau", "n"],
  ["шокола́д", "chocolat", "n", 1],
  ["шо́рты", "short", "n"],
  ["шпио́н", "espion", "n", 1],
  ["шу́ба", "fourrure", "n"],
  ["шум", "bruit", "n", 1],
  ["шу́тка", "blague", "n", 1],
  ["ще́дрый", "généreux", "adj"],
  ["щека́", "joue", "n"],
  ["щи", "soupe de chou", "n"],
  ["щи́колотка", "cheville", "n"],
  ["экза́мен", "examen", "n", 1],
  ["экра́н", "écran", "n"],
  ["экспе́рт", "expert", "n", 1],
  ["э́кспорт", "exporter", "v"],
  ["эпо́ха", "époque", "n"],
  ["эссе́", "essai", "n"],
  ["эта́ж", "étage", "n", 1],
  ["ю́бка", "jupe", "n"],
  ["юри́ст", "juriste", "n"],
  ["я́блоко", "pomme", "n", 1],
  ["я́года", "baie", "n"],
  ["язы́к", "langue", "n", 1],
  ["яйцо́", "œuf", "n", 1],
  ["янва́рь", "janvier", "n"],
  ["я́ркий", "brillant", "adj", 1],
  ["я́щик", "tiroir", "n", 1],
];
