// Généré par scripts/curate-contexts.mjs — ne pas éditer à la main.
//
// Des VARIANTES des contextes écrits à la main : même verbe, même marqueur,
// même règle enseignée, autre situation. La réponse, le schéma et
// l'explication sont hérités du contexte d'origine — donc justes par
// construction. Voir l'en-tête du script pour ce qu'on n'a pas demandé au
// modèle, et pourquoi.

export const EXTRA_CONTEXTS: Record<string, Record<string, unknown>[]> = {
  DIRECTION_CONTEXTS: [
    {
      id: "now-1",
      marker: "Сейча́с я ___ в библиоте́ку.",
      fr: "En ce moment, je vais à la bibliothèque.",
      schema: "oneway",
      modes: ["foot","vehicle"],
      form: "present1",
      answer: "uni",
      why: "« Сейча́с » : un trajet en cours, dans une direction — unidirectionnel.",
    },
    {
      id: "now-2",
      marker: "Сейча́с я ___ в магази́н.",
      fr: "En ce moment, je vais au magasin.",
      schema: "oneway",
      modes: ["foot","vehicle"],
      form: "present1",
      answer: "uni",
      why: "« Сейча́с » : un trajet en cours, dans une direction — unidirectionnel.",
    },
    {
      id: "every-day-1",
      marker: "Ка́ждый день я ___ в шко́лу.",
      fr: "Chaque jour, je vais à l'école.",
      schema: "repeated",
      modes: ["foot","vehicle"],
      form: "present1",
      answer: "multi",
      why: "« Ка́ждый день » : une habitude qui se répète — multidirectionnel.",
    },
    {
      id: "every-day-2",
      marker: "Ка́ждый день я ___ в бассе́йн.",
      fr: "Chaque jour, je vais à la piscine.",
      schema: "repeated",
      modes: ["foot","vehicle"],
      form: "present1",
      answer: "multi",
      why: "« Ка́ждый день » : une habitude qui se répète — multidirectionnel.",
    },
    {
      id: "usually-1",
      marker: "Обы́чно я ___ в о́фис ве́чером.",
      fr: "D'habitude, je vais au bureau le soir.",
      schema: "repeated",
      modes: ["foot","vehicle"],
      form: "present1",
      answer: "multi",
      why: "« Обы́чно » marque l'habitude — multidirectionnel.",
    },
    {
      id: "usually-2",
      marker: "Обы́чно я ___ на ры́нок в суббо́ту.",
      fr: "D'habitude, je vais au marché le samedi.",
      schema: "repeated",
      modes: ["foot","vehicle"],
      form: "present1",
      answer: "multi",
      why: "« Обы́чно » marque l'habitude — multidirectionnel.",
    },
    {
      id: "on-the-way-1",
      marker: "Когда́ он ___ в шко́лу, начался́ дождь.",
      fr: "Alors qu'il allait à l'école, la pluie a commencé.",
      schema: "oneway",
      modes: ["foot","vehicle"],
      form: "pastM",
      answer: "uni",
      why: "Une action en cours pendant laquelle une autre survient : le trajet n'est pas terminé — unidirectionnel.",
    },
    {
      id: "on-the-way-2",
      marker: "Когда́ он ___ на рабо́ту, начался́ дождь.",
      fr: "Alors qu'il allait au travail, la pluie a commencé.",
      schema: "oneway",
      modes: ["foot","vehicle"],
      form: "pastM",
      answer: "uni",
      why: "Une action en cours pendant laquelle une autre survient : le trajet n'est pas terminé — unidirectionnel.",
    },
    {
      id: "tomorrow-1",
      marker: "За́втра я ___ в Петербу́рг.",
      fr: "Demain, je vais à Saint-Pétersbourg.",
      schema: "oneway",
      modes: ["vehicle"],
      form: "present1",
      answer: "uni",
      why: "Un déplacement prévu, unique et daté : le présent unidirectionnel sert de futur proche.",
    },
    {
      id: "tomorrow-2",
      marker: "За́втра я ___ в теа́тр.",
      fr: "Demain, je vais au théâtre.",
      schema: "oneway",
      modes: ["vehicle"],
      form: "present1",
      answer: "uni",
      why: "Un déplacement prévu, unique et daté : le présent unidirectionnel sert de futur proche.",
    },
    {
      id: "likes-1",
      marker: "Я люблю́ ___ по ле́су.",
      fr: "J'aime marcher dans la forêt.",
      schema: "repeated",
      modes: ["foot"],
      form: "infinitive",
      answer: "multi",
      why: "Un goût ou une aptitude générale, sans trajet précis — multidirectionnel.",
    },
    {
      id: "likes-2",
      marker: "Я люблю́ ___ по пля́жу.",
      fr: "J'aime marcher sur la plage.",
      schema: "repeated",
      modes: ["foot"],
      form: "infinitive",
      answer: "multi",
      why: "Un goût ou une aptitude générale, sans trajet précis — multidirectionnel.",
    },
    {
      id: "can-walk-1",
      marker: "Щено́к уже́ уме́ет ___.",
      fr: "Le chiot sait déjà marcher.",
      schema: "repeated",
      modes: ["foot"],
      form: "infinitive",
      answer: "multi",
      why: "Savoir faire quelque chose est une aptitude, pas un trajet — multidirectionnel.",
    },
    {
      id: "can-walk-2",
      marker: "Мой брат уже́ уме́ет ___.",
      fr: "Mon frère sait déjà marcher.",
      schema: "repeated",
      modes: ["foot"],
      form: "infinitive",
      answer: "multi",
      why: "Savoir faire quelque chose est une aptitude, pas un trajet — multidirectionnel.",
    },
    {
      id: "bus-now-1",
      marker: "Смотри́, маши́на ___ в дере́вню.",
      fr: "Regarde, la voiture va vers le village.",
      schema: "oneway",
      modes: ["vehicle"],
      form: "present3",
      answer: "uni",
      why: "Le trajet est visible, en cours, dans une direction — unidirectionnel.",
    },
    {
      id: "bus-now-2",
      marker: "Смотри́, по́езд ___ на юг.",
      fr: "Regarde, le train va vers le sud.",
      schema: "oneway",
      modes: ["vehicle"],
      form: "present3",
      answer: "uni",
      why: "Le trajet est visible, en cours, dans une direction — unidirectionnel.",
    },
    {
      id: "often-1",
      marker: "Он ча́сто ___ в библиоте́ку.",
      fr: "Il va souvent à la bibliothèque.",
      schema: "repeated",
      modes: ["foot","vehicle"],
      form: "pastM",
      answer: "multi",
      why: "« Ча́сто » marque la répétition — multidirectionnel.",
    },
    {
      id: "often-2",
      marker: "Он ча́сто ___ в спортза́л.",
      fr: "Il va souvent à la salle de sport.",
      schema: "repeated",
      modes: ["foot","vehicle"],
      form: "pastM",
      answer: "multi",
      why: "« Ча́сто » marque la répétition — multidirectionnel.",
    },
  ],
};
