// Généré par scripts/curate-contexts.mjs — ne pas éditer à la main.
//
// Des VARIANTES des contextes écrits à la main : même verbe, même marqueur,
// même règle enseignée, autre situation. La réponse, le schéma et
// l'explication sont hérités du contexte d'origine — donc justes par
// construction. Voir l'en-tête du script pour ce qu'on n'a pas demandé au
// modèle, et pourquoi.

export const EXTRA_CONTEXTS: Record<string, Record<string, unknown>[]> = {
  PAST_CONTEXTS: [
    {
      id: "ves-vecher-1",
      template: "Вчера́ я весь ве́чер ___ дома́шнее зада́ние.",
      fr: "Hier, j'ai fait mes devoirs toute la soirée.",
      schema: "process",
      answer: "imperfective",
      why: "« весь ве́чер » mesure une durée occupée, sans dire qu'on est arrivé au bout — imperfectif.",
      pair: "delat",
    },
    {
      id: "ves-vecher-2",
      template: "Вчера́ я весь ве́чер ___ телеви́зор.",
      fr: "Hier, j'ai regardé la télévision toute la soirée.",
      schema: "process",
      answer: "imperfective",
      why: "« весь ве́чер » mesure une durée occupée, sans dire qu'on est arrivé au bout — imperfectif.",
      pair: "smotret",
    },
    {
      id: "dolgo-1",
      template: "Он до́лго ___ но́вое пра́вило.",
      fr: "Il a longtemps expliqué cette nouvelle règle.",
      schema: "attempt",
      answer: "imperfective",
      why: "« до́лго » décrit l'effort qui dure ; rien ne dit qu'il a abouti — imperfectif.",
      pair: "obyasnyat",
    },
    {
      id: "nakonets-1",
      template: "Наконе́ц он ___ письмо́.",
      fr: "Il a fini par écrire la lettre.",
      schema: "result",
      answer: "perfective",
      why: "« наконе́ц » annonce l'aboutissement après l'effort — perfectif.",
      pair: "pisat",
    },
    {
      id: "kazhdyy-den-1",
      template: "Ка́ждый день я ___ газе́ту.",
      fr: "Chaque jour, je lisais le journal.",
      schema: "repetition",
      answer: "imperfective",
      why: "« ка́ждый день » marque la répétition : une suite d'occurrences, pas un événement unique — imperfectif.",
      pair: "chitat",
    },
    {
      id: "vdrug-2",
      template: "Вдруг он ___ отве́т.",
      fr: "Soudain, il a reçu la réponse.",
      schema: "result",
      answer: "perfective",
      why: "« вдруг » signale un événement ponctuel, une rupture — perfectif.",
      pair: "poluchat",
    },
    {
      id: "uzhe-kartina",
      template: "Я уже́ ___ э́ту карти́ну.",
      fr: "J'ai déjà vu ce tableau.",
      schema: "result",
      answer: "perfective",
      why: "« уже́ » pointe un résultat acquis, dont l'effet vaut encore — perfectif.",
      pair: "videt",
    },
    {
      id: "uzhe-otvet",
      template: "Я уже́ ___ отве́т на письмо́.",
      fr: "J'ai déjà reçu la réponse à la lettre.",
      schema: "result",
      answer: "perfective",
      why: "« уже́ » pointe un résultat acquis, dont l'effet vaut encore — perfectif.",
      pair: "poluchat",
    },
    {
      id: "kogda-zazvonil-uchil",
      template: "Когда́ я ___ стихотворе́ние, зазвони́л телефо́н.",
      fr: "Pendant que j'apprenais le poème par cœur, le téléphone a sonné.",
      schema: "interrupted",
      answer: "imperfective",
      why: "Un processus en cours pendant lequel un événement survient : la première action n'est pas bornée — imperfectif.",
      pair: "uchit",
    },
    {
      id: "kogda-zazvonil-gotovil",
      template: "Когда́ я ___ у́жин, зазвони́л телефо́н.",
      fr: "Pendant que je préparais le dîner, le téléphone a sonné.",
      schema: "interrupted",
      answer: "imperfective",
      why: "Un processus en cours pendant lequel un événement survient : la première action n'est pas bornée — imperfectif.",
      pair: "gotovit",
    },
    {
      id: "potom-otkryl",
      template: "Он ___ окно́ и сра́зу вы́шел из ко́мнаты.",
      fr: "Il a ouvert la fenêtre et est sorti de la pièce aussitôt.",
      schema: "sequence",
      answer: "perfective",
      why: "Deux actions qui s'enchaînent, chacune menée à son terme — perfectif.",
      pair: "otkryvat",
    },
    {
      id: "obychno-zavtrak",
      template: "Обы́чно я ___ в во́семь часо́в.",
      fr: "D'habitude, je prenais le petit-déjeuner à huit heures.",
      schema: "repetition",
      answer: "imperfective",
      why: "« обы́чно » décrit une habitude — imperfectif.",
      pair: "zavtrakat",
    },
    {
      id: "obychno-lozhilsya",
      template: "Обы́чно я ___ в де́сять часо́в.",
      fr: "D'habitude, je me couchais à dix heures.",
      schema: "repetition",
      answer: "imperfective",
      why: "« обы́чно » décrit une habitude — imperfectif.",
      pair: "lozhitsya",
    },
    {
      id: "nikogda-gazeta",
      template: "Я никогда́ не ___ э́ту газе́ту.",
      fr: "Je n'ai jamais lu ce journal.",
      schema: "process",
      answer: "imperfective",
      why: "La négation d'expérience porte sur le fait même, pas sur un résultat manqué — imperfectif.",
      pair: "chitat",
    },
    {
      id: "srazu-obyasnila",
      template: "Она́ сра́зу ___ пра́вило.",
      fr: "Elle a expliqué la règle tout de suite.",
      schema: "result",
      answer: "perfective",
      why: "« сра́зу » présente l'action comme un événement unique et abouti — perfectif.",
      subject: "f",
      pair: "obyasnyat",
    },
    {
      id: "srazu-pozvonila",
      template: "Она́ сра́зу ___ дру́гу.",
      fr: "Elle a téléphoné à son ami tout de suite.",
      schema: "result",
      answer: "perfective",
      why: "« сра́зу » présente l'action comme un événement unique et abouti — perfectif.",
      subject: "f",
      pair: "zvonit",
    },
    {
      id: "chasto-babushke",
      template: "В де́тстве он ча́сто ___ ба́бушке.",
      fr: "Enfant, il téléphonait souvent à sa grand-mère.",
      schema: "repetition",
      answer: "imperfective",
      why: "« ча́сто » marque la répétition — imperfectif.",
      pair: "zvonit",
    },
    {
      id: "vypil-chai",
      template: "Он ___ ча́шку ча́я и вы́шел.",
      fr: "Il a bu une tasse de thé et il est sorti.",
      schema: "sequence",
      answer: "perfective",
      why: "Enchaînement de deux actions achevées — perfectif.",
      pair: "pit",
    },
    {
      id: "sel-yablako",
      template: "Он ___ я́блоко и вы́шел.",
      fr: "Il a mangé une pomme et il est sorti.",
      schema: "sequence",
      answer: "perfective",
      why: "Enchaînement de deux actions achevées — perfectif.",
      pair: "est",
    },
    {
      id: "uzhe-otkryl",
      template: "Я уже́ ___ окно́.",
      fr: "J'ai déjà ouvert la fenêtre.",
      schema: "result",
      answer: "perfective",
      why: "« уже́ » + résultat encore valable — perfectif.",
      pair: "otkryvat",
    },
    {
      id: "uzhe-poluchil",
      template: "Я уже́ ___ письмо́.",
      fr: "J'ai déjà reçu la lettre.",
      schema: "result",
      answer: "perfective",
      why: "« уже́ » + résultat encore valable — perfectif.",
      pair: "poluchat",
    },
  ],
  FUTURE_CONTEXTS: [
    {
      id: "i-otpravlyu-var1",
      template: "За́втра я ___ отве́т и отпра́влю его́.",
      fr: "Demain, j'écrirai la réponse et je l'enverrai.",
      schema: "sequence",
      answer: "perfective",
      why: "Deux actions qui s'enchaînent, chacune menée à son terme — futur perfectif.",
      pair: "pisat",
    },
    {
      id: "i-otpravlyu-var2",
      template: "За́втра я ___ пода́рок и отпра́влю его́.",
      fr: "Demain, j'achèterai le cadeau et je l'enverrai.",
      schema: "sequence",
      answer: "perfective",
      why: "Deux actions qui s'enchaînent, chacune menée à son terme — futur perfectif.",
      pair: "pokupat",
    },
    {
      id: "kazhdyy-vecher-var1",
      template: "Ка́ждый ве́чер я ___ кни́гу.",
      fr: "Chaque soir, je lirai un livre.",
      schema: "repetition",
      answer: "imperfective",
      why: "La répétition exclut le perfectif, qui ne décrit qu'une occurrence — futur imperfectif.",
      pair: "chitat",
    },
    {
      id: "kazhdyy-vecher-var2",
      template: "Ка́ждый ве́чер я ___ слова́.",
      fr: "Chaque soir, je répéterai les mots.",
      schema: "repetition",
      answer: "imperfective",
      why: "La répétition exclut le perfectif, qui ne décrit qu'une occurrence — futur imperfectif.",
      pair: "povtoryat",
    },
    {
      id: "obeshchayu-var1",
      template: "Обеща́ю, я ___ тебе́ сего́дня.",
      fr: "Je te promets que je te téléphonerai aujourd'hui.",
      schema: "result",
      answer: "perfective",
      why: "Une promesse porte sur un résultat, pas sur une occupation — futur perfectif.",
      pair: "zvonit",
    },
    {
      id: "obeshchayu-var2",
      template: "Обеща́ю, я ___ уро́к сего́дня.",
      fr: "Je te promets que je commencerai la leçon aujourd'hui.",
      schema: "result",
      answer: "perfective",
      why: "Une promesse porte sur un résultat, pas sur une occupation — futur perfectif.",
      pair: "nachinat",
    },
    {
      id: "vsyu-nedelyu-var1",
      template: "Я всю неде́лю ___ но́вые слова́.",
      fr: "Toute la semaine, je vais apprendre de nouveaux mots.",
      schema: "process",
      answer: "imperfective",
      why: "« всю неде́лю » décrit une occupation étalée — futur imperfectif.",
      pair: "uchit",
    },
    {
      id: "vsyu-nedelyu-var2",
      template: "Я всю неде́лю ___ ру́сский язы́к.",
      fr: "Toute la semaine, je vais étudier le russe.",
      schema: "process",
      answer: "imperfective",
      why: "« всю неде́лю » décrit une occupation étalée — futur imperfectif.",
      pair: "izuchat",
    },
    {
      id: "zavtra-pozvonyu",
      template: "За́втра я ___ тебе́ в шесть часо́в.",
      fr: "Demain, je te téléphonerai à six heures.",
      schema: "result",
      answer: "perfective",
      why: "Un événement unique et daté — futur perfectif.",
      pair: "zvonit",
    },
    {
      id: "zavtra-otkroyu",
      template: "За́втра я ___ магази́н в шесть часо́в.",
      fr: "Demain, j'ouvrirai le magasin à six heures.",
      schema: "result",
      answer: "perfective",
      why: "Un événement unique et daté — futur perfectif.",
      pair: "otkryvat",
    },
    {
      id: "tselyy-god-stroit",
      template: "Весь год я ___ но́вый дом.",
      fr: "Toute l'année, je vais construire une nouvelle maison.",
      schema: "process",
      answer: "imperfective",
      why: "« весь год » annonce une occupation étalée dans le temps — futur imperfectif.",
      pair: "stroit",
    },
    {
      id: "tselyy-god-gotovit",
      template: "Весь год я ___ обе́д для семьи́.",
      fr: "Toute l'année, je vais préparer le déjeuner pour la famille.",
      schema: "process",
      answer: "imperfective",
      why: "« весь год » annonce une occupation étalée dans le temps — futur imperfectif.",
      pair: "gotovit",
    },
    {
      id: "kak-tolko-otvechu",
      template: "Как то́лько прие́ду, я ___ на письмо́.",
      fr: "Dès que j'arrive, je répondrai à la lettre.",
      schema: "sequence",
      answer: "perfective",
      why: "Un événement unique déclenché par un autre — futur perfectif.",
      pair: "otvechat",
    },
    {
      id: "kak-tolko-otkroyu",
      template: "Как то́лько прие́ду, я ___ окно́.",
      fr: "Dès que j'arrive, j'ouvrirai la fenêtre.",
      schema: "sequence",
      answer: "perfective",
      why: "Un événement unique déclenché par un autre — futur perfectif.",
      pair: "otkryvat",
    },
    {
      id: "nikogda-ne-zabudu",
      template: "Бо́льше я никогда́ не ___ твой день рожде́ния.",
      fr: "Je n'oublierai plus jamais ton anniversaire.",
      schema: "process",
      answer: "imperfective",
      why: "« никогда́ не » nie l'action en général, pas un résultat manqué — futur imperfectif.",
      pair: "zabyvat",
    },
    {
      id: "nikogda-ne-kuplyu",
      template: "Бо́льше я никогда́ не ___ э́тот журна́л.",
      fr: "Je n'achèterai plus jamais ce magazine.",
      schema: "process",
      answer: "imperfective",
      why: "« никогда́ не » nie l'action en général, pas un résultat manqué — futur imperfectif.",
      pair: "pokupat",
    },
    {
      id: "poka-ne-vyuchu",
      template: "Я не уйду́, пока́ не ___ э́ти слова́.",
      fr: "Je ne partirai pas tant que je n'aurai pas appris ces mots par cœur.",
      schema: "sequence",
      answer: "perfective",
      why: "« пока́ не » attend un RÉSULTAT atteint : futur perfectif, malgré la négation.",
      pair: "uchit",
    },
    {
      id: "poka-ne-otkroyu",
      template: "Я не уйду́, пока́ не ___ дверь.",
      fr: "Je ne partirai pas tant que je n'aurai pas ouvert la porte.",
      schema: "sequence",
      answer: "perfective",
      why: "« пока́ не » attend un RÉSULTAT atteint : futur perfectif, malgré la négation.",
      pair: "otkryvat",
    },
    {
      id: "kazhdyy-den-chitat",
      template: "В Москве́ я ___ газе́ту ка́ждый день.",
      fr: "À Moscou, je lirai le journal tous les jours.",
      schema: "process",
      answer: "imperfective",
      why: "Action répétée jour après jour, sans achèvement visé — futur imperfectif composé (бу́ду + infinitif).",
      pair: "chitat",
    },
    {
      id: "kazhdyy-den-zavtrakat",
      template: "В Москве́ я ___ в кафе́ ка́ждый день.",
      fr: "À Moscou, je prendrai le petit-déjeuner au café tous les jours.",
      schema: "process",
      answer: "imperfective",
      why: "Action répétée jour après jour, sans achèvement visé — futur imperfectif composé (бу́ду + infinitif).",
      pair: "zavtrakat",
    },
    {
      id: "vecherom-doma",
      template: "Ве́чером я ___ у́жин и позвоню́ ма́ме.",
      fr: "Le soir je préparerai le dîner et j'appellerai maman.",
      schema: "sequence",
      answer: "perfective",
      why: "Deux actions uniques qui s'enchaînent, chacune menée à son terme — futur perfectif.",
      pair: "gotovit",
    },
    {
      id: "posle-obeda",
      template: "По́сле обе́да я ___ хле́б и верну́сь домо́й.",
      fr: "Après le déjeuner j'achèterai du pain et je rentrerai à la maison.",
      schema: "sequence",
      answer: "perfective",
      why: "Deux actions uniques qui s'enchaînent, chacune menée à son terme — futur perfectif.",
      pair: "pokupat",
    },
  ],
  IMPERATIVE_CONTEXTS: [
    {
      id: "negation-opozdat-utrom",
      template: "Не ___ мне так ра́но у́тром!",
      fr: "Ne me téléphone pas si tôt le matin !",
      answer: "imperfective",
      why: "Même règle : une interdiction se dit à l'imperfectif.",
      address: "ty",
      pair: "zvonit",
    },
    {
      id: "negation-opozdat-nochyu",
      template: "Не ___ мне но́чью!",
      fr: "Ne me téléphone pas la nuit !",
      answer: "imperfective",
      why: "Même règle : une interdiction se dit à l'imperfectif.",
      address: "ty",
      pair: "zvonit",
    },
    {
      id: "polite-request-vopros",
      template: "___, пожа́луйста, вопро́с ещё раз.",
      fr: "Répétez la question encore une fois, s'il vous plaît.",
      answer: "perfective",
      why: "Demande ponctuelle et unique, dont on attend le résultat — perfectif.",
      address: "vy",
      pair: "povtoryat",
    },
    {
      id: "polite-request-pravilo",
      template: "___, пожа́луйста, э́то пра́вило.",
      fr: "Expliquez cette règle, s'il vous plaît.",
      answer: "perfective",
      why: "Demande ponctuelle et unique, dont on attend le résultat — perfectif.",
      address: "vy",
      pair: "obyasnyat",
    },
    {
      id: "one-off-hleb",
      template: "___ мне хлеб, пожа́луйста.",
      fr: "Donne-moi le pain, s'il te plaît.",
      answer: "perfective",
      why: "Une seule action attendue, avec son résultat — perfectif.",
      address: "ty",
      pair: "davat",
    },
    {
      id: "one-off-nozh",
      template: "___ мне нож, пожа́луйста.",
      fr: "Donne-moi le couteau, s'il te plaît.",
      answer: "perfective",
      why: "Une seule action attendue, avec son résultat — perfectif.",
      address: "ty",
      pair: "davat",
    },
    {
      id: "negation-brat-ruchku",
      template: "Не ___ э́ту ру́чку без разреше́ния.",
      fr: "Ne prends pas ce stylo sans autorisation.",
      answer: "imperfective",
      why: "Interdiction générale : l'impératif négatif appelle l'imperfectif.",
      address: "ty",
      pair: "brat",
    },
    {
      id: "negation-brat-mashinu",
      template: "Не ___ э́ту маши́ну без разреше́ния.",
      fr: "Ne prends pas cette voiture sans autorisation.",
      answer: "imperfective",
      why: "Interdiction générale : l'impératif négatif appelle l'imperfectif.",
      address: "ty",
      pair: "brat",
    },
    {
      id: "negation-secret",
      template: "Не ___ об э́том сосе́дям!",
      fr: "N'en parle pas aux voisins !",
      answer: "imperfective",
      why: "Défense de faire quelque chose, sans limite de temps — imperfectif.",
      address: "ty",
      pair: "govorit",
    },
    {
      id: "negation-podruga",
      template: "Не ___ об э́том подру́ге!",
      fr: "N'en parle pas à ta copine !",
      answer: "imperfective",
      why: "Défense de faire quelque chose, sans limite de temps — imperfectif.",
      address: "ty",
      pair: "govorit",
    },
    {
      id: "polite-close-door",
      template: "___, пожа́луйста, дверь.",
      fr: "Fermez la porte, s'il vous plaît.",
      answer: "perfective",
      why: "Une action unique dont on attend le résultat immédiat — perfectif.",
      address: "vy",
      pair: "zakryvat",
    },
    {
      id: "polite-open-box",
      template: "___, пожа́луйста, коро́бку.",
      fr: "Ouvrez la boîte, s'il vous plaît.",
      answer: "perfective",
      why: "Une action unique dont on attend le résultat immédiat — perfectif.",
      address: "vy",
      pair: "otkryvat",
    },
    {
      id: "warning-passport",
      template: "Не ___ па́спорт!",
      fr: "N'oublie pas ton passeport !",
      answer: "perfective",
      why: "Mise en garde contre un accident ponctuel — c'est le cas RARE où l'impératif négatif prend le perfectif.",
      address: "ty",
      pair: "zabyvat",
    },
    {
      id: "warning-telefon",
      template: "Не ___ телефо́н!",
      fr: "N'oublie pas ton téléphone !",
      answer: "perfective",
      why: "Mise en garde contre un accident ponctuel — c'est le cas RARE où l'impératif négatif prend le perfectif.",
      address: "ty",
      pair: "zabyvat",
    },
    {
      id: "request-number",
      template: "___ мне свой но́мер, пожа́луйста.",
      fr: "Écris-moi ton numéro, s'il te plaît.",
      answer: "perfective",
      why: "Demande d'un acte unique dont on attend le résultat — perfectif.",
      address: "ty",
      pair: "pisat",
    },
    {
      id: "request-email",
      template: "___ мне свою́ по́чту, пожа́луйста.",
      fr: "Écris-moi ton adresse mail, s'il te plaît.",
      answer: "perfective",
      why: "Demande d'un acte unique dont on attend le résultat — perfectif.",
      address: "ty",
      pair: "pisat",
    },
    {
      id: "habit-listen-news",
      template: "___ но́вости ка́ждый день — так ты быстре́е вы́учишь язы́к.",
      fr: "Regarde les infos tous les jours — tu apprendras la langue plus vite.",
      answer: "imperfective",
      why: "Conseil de répéter l'action régulièrement, sans point d'arrivée : imperfectif.",
      address: "ty",
      pair: "smotret",
    },
    {
      id: "habit-repeat-words",
      template: "___ слова́ ка́ждый день — так ты быстре́е вы́учишь язы́к.",
      fr: "Répète les mots tous les jours — tu apprendras la langue plus vite.",
      answer: "imperfective",
      why: "Conseil de répéter l'action régulièrement, sans point d'arrivée : imperfectif.",
      address: "ty",
      pair: "povtoryat",
    },
  ],
};
