// Généré par scripts/curate-contexts.mjs — ne pas éditer à la main.
//
// Des VARIANTES des contextes écrits à la main : même verbe, même marqueur,
// même règle enseignée, autre situation. La réponse, le schéma et
// l'explication sont hérités du contexte d'origine — donc justes par
// construction. Voir l'en-tête du script pour ce qu'on n'a pas demandé au
// modèle, et pourquoi.

export const EXTRA_CONTEXTS: Record<string, Record<string, unknown>[]> = {
  GERUND_CONTEXTS: [
    {
      id: "finished-project-office",
      expanded: "Когда́ он зако́нчил прое́кт, он ушёл из о́фиса.",
      compressed: "___ прое́кт, он ушёл из о́фиса.",
      fr: "Ayant terminé son projet, il est parti du bureau.",
      aspect: "perfective",
      why: "L'action est ACHEVÉE avant celle du verbe principal → gérondif perfectif en -в.",
      verb: "zakanchivat",
    },
    {
      id: "reading-note-frowned",
      expanded: "Пока́ он чита́л запи́ску, он хму́рился.",
      compressed: "___ запи́ску, он хму́рился.",
      fr: "En lisant le billet, il fronçait les sourcils.",
      aspect: "imperfective",
      why: "Les deux actions sont SIMULTANÉES → gérondif imperfectif en -я.",
      verb: "chitat",
    },
    {
      id: "having-read-article",
      expanded: "Когда́ он прочита́л статью́, он её показа́л дру́гу.",
      compressed: "___ статью́, он её показа́л дру́гу.",
      fr: "Après avoir lu l'article, il l'a montré à un ami.",
      aspect: "perfective",
      why: "L'action est terminée avant la suivante → gérondif perfectif.",
      verb: "chitat",
    },
    {
      id: "having-arrived-station",
      expanded: "Когда́ он пришёл на ста́нцию, он сра́зу купи́л биле́т.",
      compressed: "___ на ста́нцию, он сра́зу купи́л биле́т.",
      fr: "Une fois arrivé à la gare, il a aussitôt acheté un billet.",
      aspect: "perfective",
      why: "Arrivée achevée, puis action suivante → gérondif perfectif (придя́).",
      verb: "idti",
    },
    {
      id: "helping-explained-var2",
      expanded: "Когда́ она́ помога́ла ему́, она́ всё пока́зывала.",
      compressed: "___ ему́, она́ всё пока́зывала.",
      fr: "En l'aidant, elle montrait tout.",
      aspect: "imperfective",
      why: "Actions simultanées → gérondif imperfectif.",
      verb: "pomogat",
      subject: "f",
    },
    {
      id: "opening-saw-var2",
      expanded: "Когда́ она́ откры́ла шкаф, она́ нашла́ пла́тье.",
      compressed: "___ шкаф, она́ нашла́ пла́тье.",
      fr: "Ayant ouvert l'armoire, elle a trouvé une robe.",
      aspect: "perfective",
      why: "L'ouverture précède et s'achève avant l'écoute → gérondif perfectif en -в.",
      verb: "otkryvat",
      subject: "f",
    },
    {
      id: "studying-took-notes-var2",
      expanded: "Пока́ он изуча́л хи́мию, он вёл за́писи.",
      compressed: "___ хи́мию, он вёл за́писи.",
      fr: "Tout en étudiant la chimie, il prenait des notes.",
      aspect: "imperfective",
      why: "Les deux actions se déroulent en même temps → gérondif imperfectif en -я.",
      verb: "izuchat",
    },
    {
      id: "cooking-listened-var1",
      expanded: "Пока́ она́ гото́вила обе́д, она́ слу́шала му́зыку.",
      compressed: "___ обе́д, она́ слу́шала му́зыку.",
      fr: "En préparant le déjeuner, elle écoutait de la musique.",
      aspect: "imperfective",
      why: "Deux occupations menées de front → gérondif imperfectif. Le radical alterne : гото́вить → гото́вя.",
      verb: "gotovit",
      subject: "f",
    },
    {
      id: "cooking-listened-var2",
      expanded: "Пока́ она́ гото́вила пиро́г, она́ слу́шала но́вости.",
      compressed: "___ пиро́г, она́ слу́шала но́вости.",
      fr: "En préparant la tarte, elle écoutait les nouvelles.",
      aspect: "imperfective",
      why: "Deux occupations menées de front → gérondif imperfectif. Le radical alterne : гото́вить → гото́вя.",
      verb: "gotovit",
      subject: "f",
    },
  ],
  ACTIVE_CONTEXTS: [
    {
      id: "student-reading-1",
      expanded: "Студе́нт, кото́рый чита́ет в кафе́, — мой сосе́д.",
      compressed: "Студе́нт, ___ в кафе́, — мой сосе́д.",
      fr: "L'étudiant qui lit au café est mon voisin.",
      tense: "present",
      why: "L'action est en cours et le sujet la fait : participe présent ACTIF en -щий.",
      verb: "chitat",
    },
    {
      id: "student-reading-2",
      expanded: "Студе́нт, кото́рый чита́ет в па́рке, — мой брат.",
      compressed: "Студе́нт, ___ в па́рке, — мой брат.",
      fr: "L'étudiant qui lit dans le parc est mon frère.",
      tense: "present",
      why: "L'action est en cours et le sujet la fait : participe présent ACTIF en -щий.",
      verb: "chitat",
    },
    {
      id: "man-worked-1",
      expanded: "Челове́к, кото́рый рабо́тал на заво́де, уе́хал.",
      compressed: "Челове́к, ___ на заво́де, уе́хал.",
      fr: "L'homme qui travaillait à l'usine est parti.",
      tense: "past",
      why: "L'action est révolue : participe passé actif en -вший.",
      verb: "rabotat",
    },
    {
      id: "man-worked-2",
      expanded: "Челове́к, кото́рый рабо́тал в магази́не, уе́хал.",
      compressed: "Челове́к, ___ в магази́не, уе́хал.",
      fr: "L'homme qui travaillait au magasin est parti.",
      tense: "past",
      why: "L'action est révolue : participe passé actif en -вший.",
      verb: "rabotat",
    },
    {
      id: "people-living-1",
      expanded: "Лю́ди, кото́рые живу́т в э́той дере́вне, о́чень дру́жные.",
      compressed: "Лю́ди, ___ в э́той дере́вне, о́чень дру́жные.",
      fr: "Les gens qui habitent ce village sont très soudés.",
      tense: "present",
      why: "État actuel : participe présent actif. Il s'accorde ici au pluriel — comme un adjectif.",
      verb: "zhit",
    },
    {
      id: "people-living-2",
      expanded: "Лю́ди, кото́рые живу́т на э́той у́лице, о́чень дру́жные.",
      compressed: "Лю́ди, ___ на э́той у́лице, о́чень дру́жные.",
      fr: "Les gens qui habitent cette rue sont très soudés.",
      tense: "present",
      why: "État actuel : participe présent actif. Il s'accorde ici au pluriel — comme un adjectif.",
      verb: "zhit",
    },
    {
      id: "girl-helped-1",
      expanded: "Де́вушка, кото́рая помога́ла врачу́, рабо́тает здесь.",
      compressed: "Де́вушка, ___ врачу́, рабо́тает здесь.",
      fr: "La jeune fille qui aidait le médecin travaille ici.",
      tense: "past",
      why: "Action passée et durable : participe passé actif imperfectif en -вший.",
      verb: "pomogat",
    },
    {
      id: "girl-helped-2",
      expanded: "Де́вушка, кото́рая помога́ла учи́телю, рабо́тает здесь.",
      compressed: "Де́вушка, ___ учи́телю, рабо́тает здесь.",
      fr: "La jeune fille qui aidait le professeur travaille ici.",
      tense: "past",
      why: "Action passée et durable : participe passé actif imperfectif en -вший.",
      verb: "pomogat",
    },
    {
      id: "engineer-building-1",
      expanded: "Инжене́р, кото́рый стро́ит э́тот заво́д, о́чень о́пытный.",
      compressed: "Инжене́р, ___ э́тот заво́д, о́чень о́пытный.",
      fr: "L'ingénieur qui construit cette usine est très expérimenté.",
      tense: "present",
      why: "Le sujet accomplit l'action maintenant : participe présent actif.",
      verb: "stroit",
    },
    {
      id: "engineer-building-2",
      expanded: "Инжене́р, кото́рый стро́ит э́тот дом, о́чень о́пытный.",
      compressed: "Инжене́р, ___ э́тот дом, о́чень о́пытный.",
      fr: "L'ingénieur qui construit cette maison est très expérimenté.",
      tense: "present",
      why: "Le sujet accomplit l'action maintenant : participe présent actif.",
      verb: "stroit",
    },
    {
      id: "friend-returning-1",
      expanded: "Друг, кото́рый возвраща́ется из Петербу́рга, позвони́т у́тром.",
      compressed: "Друг, ___ из Петербу́рга, позвони́т у́тром.",
      fr: "L'ami qui revient de Saint-Pétersbourg appellera le matin.",
      tense: "present",
      why: "Verbe pronominal : le participe garde le -ся, qui ne devient jamais -сь.",
      verb: "vozvrashchatsya",
    },
    {
      id: "friend-returning-2",
      expanded: "Друг, кото́рый возвраща́ется из аэропо́рта, позвони́т ве́чером.",
      compressed: "Друг, ___ из аэропо́рта, позвони́т ве́чером.",
      fr: "L'ami qui revient de l'aéroport appellera ce soir.",
      tense: "present",
      why: "Verbe pronominal : le participe garde le -ся, qui ne devient jamais -сь.",
      verb: "vozvrashchatsya",
    },
  ],
  PASSIVE_CONTEXTS: [
    {
      id: "door-closed-shop",
      expanded: "Дверь, кото́рую закры́ли ве́чером в магази́не, так и оста́лась закры́той.",
      compressed: "___ ве́чером в магази́не дверь так и оста́лась закры́той.",
      fr: "La porte fermée le soir dans le magasin est restée close.",
      agreement: "f",
      why: "Participe passé passif accordé au féminin avec « дверь ».",
      verb: "zakryvat",
    },
    {
      id: "door-closed-school",
      expanded: "Дверь, кото́рую закры́ли по́сле уро́ков, так и оста́лась закры́той.",
      compressed: "___ по́сле уро́ков дверь так и оста́лась закры́той.",
      fr: "La porte fermée après les cours est restée close.",
      agreement: "f",
      why: "Participe passé passif accordé au féminin avec « дверь ».",
      verb: "zakryvat",
    },
    {
      id: "window-opened-kitchen",
      expanded: "Окно́, кото́рое откры́ли на ку́хне, впусти́ло хо́лод.",
      compressed: "___ на ку́хне окно́ впусти́ло хо́лод.",
      fr: "La fenêtre ouverte dans la cuisine a laissé entrer le froid.",
      agreement: "n",
      why: "« окно́ » est neutre : le participe prend la terminaison neutre.",
      verb: "otkryvat",
    },
    {
      id: "window-opened-train",
      expanded: "Окно́, кото́рое откры́ли в по́езде, впусти́ло хо́лод.",
      compressed: "___ в по́езде окно́ впусти́ло хо́лод.",
      fr: "La fenêtre ouverte dans le train a laissé entrer le froid.",
      agreement: "n",
      why: "« окно́ » est neutre : le participe prend la terminaison neutre.",
      verb: "otkryvat",
    },
    {
      id: "work-done-project",
      expanded: "Рабо́та, кото́рую сде́лали за ночь, всех устро́ила.",
      compressed: "___ за ночь рабо́та всех устро́ила.",
      fr: "Le travail fait dans la nuit a satisfait tout le monde.",
      agreement: "f",
      why: "Accord au féminin avec « рабо́та ».",
      verb: "delat",
    },
    {
      id: "work-done-team",
      expanded: "Рабо́та, кото́рую сде́лали в кома́нде, всех устро́ила.",
      compressed: "___ в кома́нде рабо́та всех устро́ила.",
      fr: "Le travail fait en équipe a satisfait tout le monde.",
      agreement: "f",
      why: "Accord au féminin avec « рабо́та ».",
      verb: "delat",
    },
    {
      id: "topic-studied-course",
      expanded: "Те́ма, кото́рую изучи́ли на ку́рсе, сно́ва появи́лась на экза́мене.",
      compressed: "___ на ку́рсе те́ма сно́ва появи́лась на экза́мене.",
      fr: "Le sujet étudié pendant le cours est réapparu à l'examen.",
      agreement: "f",
      why: "Le participe se place avant le nom et s'accorde avec lui.",
      verb: "izuchat",
    },
    {
      id: "topic-studied-seminar",
      expanded: "Те́ма, кото́рую изучи́ли на семина́ре, сно́ва появи́лась на экза́мене.",
      compressed: "___ на семина́ре те́ма сно́ва появи́лась на экза́мене.",
      fr: "Le sujet étudié pendant le séminaire est réapparu à l'examen.",
      agreement: "f",
      why: "Le participe se place avant le nom et s'accorde avec lui.",
      verb: "izuchat",
    },
  ],
};
