import { CaseId } from "./types";
import { ArticleMode } from "./french-article";
// Type seul : évite un cycle de modules avec noun-categories, qui lit la banque.
import type { NounCategory } from "./noun-categories";

// Banque des "déclencheurs" de chaque cas : prépositions, verbes à régime
// et expressions figées qui imposent le cas. Objectif pédagogique : ne pas
// seulement faire décliner un mot isolé, mais montrer QUAND/POURQUOI ce cas
// apparaît en russe (approche des manuels RLE). Chaque déclencheur fournit
// aussi un gabarit de phrase à trou (`template`), utilisé comme repli
// hors-IA et comme base des exercices QCM.
//
// Couverture volontairement large et déséquilibrée entre cas : le génitif
// a près de trois fois plus de déclencheurs que les autres (~15 prépositions
// courantes + verbes + expressions de quantité/possession) — c'est un fait
// de la langue russe, pas un oubli. Le prépositionnel, à l'inverse, n'a par
// nature que 4 prépositions possibles (в, на, о, при) : sa richesse vient
// des verbes qui l'imposent, pas des prépositions.
//
// Limite assumée : seuls les déclencheurs dont le mot à trou peut être un
// nom commun générique sont inclus (pas de déclencheur du type "jours de la
// semaine" ou "le 5 mai" qui exigerait un nom précis hors de la banque de
// noms, ni de verbe à régime ambigu selon le sens comme искать/ждать qui
// prennent tantôt l'accusatif tantôt le génitif).

export type TriggerKind = "preposition" | "verb" | "expression";

// Palier de fréquence/registre — pas du CEFR fin (trop de granularité à
// maintenir sur autant d'entrées), juste de quoi biaiser le tirage des
// exercices vers l'essentiel pour un débutant et débloquer progressivement
// le reste plutôt que de tout servir à poids égal dès A0.
export type TriggerTier = "basic" | "intermediate" | "advanced";

export interface CaseTrigger {
  id: string;
  caseId: CaseId;
  kind: TriggerKind;
  tier: TriggerTier;
  ru: string; // ex. "у", "помогать (+ дат.)"
  meaningFr: string;
  template: { ru: string; fr: string }; // "___" = trou
  plural?: boolean; // ce déclencheur appelle naturellement le pluriel
  // Article français à appliquer devant la traduction insérée dans le trou
  // du template.fr — voir lib/grammar/french-article.ts. Champ obligatoire
  // (pas de défaut implicite) : chaque déclencheur a été revu au cas par
  // cas plutôt que de laisser un mode par défaut potentiellement faux.
  article: ArticleMode;
  /**
   * Classes de noms que ce déclencheur accepte (voir noun-categories.ts).
   *
   * Absent = accepte tout, et c'est une décision, pas un oubli : « Я люблю
   * ___ » ou « Я ду́маю о ___ » vont avec n'importe quel nom, les restreindre
   * appauvrirait le tirage sans rien corriger.
   *
   * Présent = le déclencheur EXIGE quelque chose. « Я ем ___ » tombait sur
   * « помо́щник » — « je mange cet assistant » : désinence juste, phrase
   * impossible. La liste est une alternative (l'un OU l'autre), jamais un
   * cumul.
   */
  accepts?: NounCategory[];
}

// "Меня зовут ___" n'a de sens qu'avec un prénom, jamais un nom commun de
// la banque générale ("Меня зовут музыка" est absurde) — repéré par id
// plutôt qu'un champ générique sur CaseTrigger puisque c'est, à ce jour, le
// seul déclencheur dans ce cas. Utilisé à la fois pour réserver le tirage
// du nom (lib/grammar/exercise-generator.ts) et pour adapter le prompt IA
// (lib/ai/prompts.ts).
export const PROPER_NOUN_TRIGGER_ID = "expr-nom-zovut";

export const TRIGGERS: CaseTrigger[] = [
  // ─── Nominatif ──────────────────────────────────────────────────
  {
    id: "expr-nom-eto",
    caseId: "nominative",
    kind: "expression",
    tier: "basic",
    article: "indefinite",
    ru: "это",
    meaningFr: "Identifier quelqu'un ou quelque chose.",
    template: { ru: "Это ___.", fr: "C'est ___." },
  },
  {
    id: "expr-nom-vot",
    caseId: "nominative",
    kind: "expression",
    tier: "basic",
    article: "demonstrative",
    ru: "вот",
    meaningFr: "Présenter, montrer du doigt.",
    template: { ru: "Вот ___.", fr: "Voici ___." },
  },
  {
    id: "expr-nom-est",
    accepts: ["human", "animal", "object", "food", "drink", "text"],
    caseId: "nominative",
    kind: "expression",
    tier: "basic",
    article: "demonstrative",
    ru: "есть",
    meaningFr: "Existence : \"il y a\" (contraste avec нет + génitif pour l'absence).",
    template: { ru: "Здесь есть ___.", fr: "Il y a ___ ici." },
  },
  {
    id: "expr-nom-zovut",
    caseId: "nominative",
    kind: "expression",
    tier: "basic",
    // Jamais d'article devant un prénom ("Je m'appelle Anna", jamais
    // "Je m'appelle cette Anna") — voir aussi le tirage réservé aux
    // prénoms (RUSSIAN_NAMES) dans exercise-generator.ts pour ce
    // déclencheur précis.
    article: "none",
    ru: "зовут",
    meaningFr: "Se présenter : le nom reste au nominatif après \"меня зовут\".",
    template: { ru: "Меня зовут ___.", fr: "Je m'appelle ___." },
  },
  {
    id: "expr-nom-pluriel",
    accepts: ["human", "animal", "object", "food", "drink", "text"],
    caseId: "nominative",
    kind: "expression",
    tier: "basic",
    article: "none",
    ru: "мн. число",
    meaningFr: "Le sujet est au pluriel.",
    template: { ru: "Здесь только ___.", fr: "Ici il n'y a que des ___." },
    plural: true,
  },

  // ─── Génitif ────────────────────────────────────────────────────
  // Absence / négation
  {
    id: "expr-gen-net",
    caseId: "genitive",
    kind: "expression",
    tier: "basic",
    article: "none",
    ru: "нет",
    meaningFr: "Absence : нет + génitif.",
    template: { ru: "У меня нет ___.", fr: "Je n'ai pas de ___." },
  },
  // Quantité et mesure
  {
    id: "expr-gen-mnogo",
    caseId: "genitive",
    kind: "expression",
    tier: "basic",
    article: "none",
    ru: "много",
    meaningFr: "Quantité importante (+ génitif pluriel).",
    template: { ru: "У меня много ___.", fr: "J'ai beaucoup de ___." },
    plural: true,
  },
  {
    id: "expr-gen-malo",
    caseId: "genitive",
    kind: "expression",
    tier: "basic",
    article: "none",
    ru: "мало",
    meaningFr: "Quantité insuffisante (+ génitif pluriel).",
    template: { ru: "У меня мало ___.", fr: "J'ai peu de ___." },
    plural: true,
  },
  {
    id: "expr-gen-neskolko",
    accepts: ["human", "animal", "object", "food", "drink", "text"],
    caseId: "genitive",
    kind: "expression",
    tier: "intermediate",
    article: "none",
    ru: "несколько",
    meaningFr: "\"Plusieurs\" (+ génitif pluriel).",
    template: { ru: "У меня есть несколько ___.", fr: "J'ai plusieurs ___." },
    plural: true,
  },
  {
    id: "expr-gen-skolko",
    accepts: ["human", "animal", "object", "food", "drink", "text"],
    caseId: "genitive",
    kind: "expression",
    tier: "basic",
    article: "none",
    ru: "сколько",
    meaningFr: "\"Combien de\" (+ génitif).",
    template: { ru: "Сколько ___ у тебя?", fr: "Combien de ___ as-tu ?" },
    plural: true,
  },
  {
    id: "expr-gen-kusok",
    accepts: ["food"],
    caseId: "genitive",
    kind: "expression",
    tier: "intermediate",
    article: "none",
    ru: "кусок",
    meaningFr: "Unité de mesure : \"un morceau de\".",
    template: { ru: "Дай мне кусок ___.", fr: "Donne-moi un morceau de ___." },
  },
  {
    id: "expr-gen-stakan",
    accepts: ["drink"],
    caseId: "genitive",
    kind: "expression",
    tier: "intermediate",
    article: "none",
    ru: "стакан",
    meaningFr: "Unité de mesure : \"un verre de\".",
    template: { ru: "Я хочу стакан ___.", fr: "Je veux un verre de ___." },
  },
  // Possession
  {
    id: "prep-gen-u",
    accepts: ["human"],
    caseId: "genitive",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "у",
    meaningFr: "Possession, \"chez\" : у + génitif.",
    template: { ru: "Я живу у ___.", fr: "Je vis chez ___." },
  },
  {
    id: "expr-gen-u-est",
    accepts: ["human"],
    caseId: "genitive",
    kind: "expression",
    tier: "basic",
    article: "demonstrative",
    ru: "у ... есть",
    meaningFr: "Possession : \"chez X il y a Y\" = \"X a Y\" — le possesseur (X) est au génitif après у.",
    template: { ru: "У ___ есть машина.", fr: "___ a une voiture." },
  },
  {
    id: "expr-gen-possession",
    accepts: ["human"],
    caseId: "genitive",
    kind: "expression",
    tier: "intermediate",
    article: "demonstrative",
    ru: "сущ. + сущ.",
    meaningFr: "Possession : \"le X de Y\" — le possesseur se met au génitif juste après le nom possédé.",
    template: { ru: "Это машина ___.", fr: "C'est la voiture de ___." },
  },
  // Prépositions
  {
    id: "prep-gen-iz",
    accepts: ["place", "area"],
    caseId: "genitive",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "из",
    meaningFr: "Provenance, origine.",
    template: { ru: "Я приехал из ___.", fr: "Je suis venu de ___." },
  },
  {
    id: "prep-gen-ot",
    accepts: ["human"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "от",
    meaningFr: "En provenance de (personne, source).",
    template: { ru: "Это письмо от ___.", fr: "Cette lettre vient de ___." },
  },
  {
    id: "prep-gen-s",
    accepts: ["time"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "с",
    meaningFr: "\"Depuis\", \"à partir de\" (sens temporel — différent de с + instrumental qui signifie \"avec\").",
    template: { ru: "Я не спал с ___.", fr: "Je n'ai pas dormi depuis ___." },
  },
  {
    id: "prep-gen-do",
    accepts: ["place", "area"],
    caseId: "genitive",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "до",
    meaningFr: "\"Jusqu'à\".",
    template: { ru: "Мы едем до ___.", fr: "Nous allons jusqu'à ___." },
  },
  {
    id: "prep-gen-posle",
    accepts: ["time", "abstract"],
    caseId: "genitive",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "после",
    meaningFr: "\"Après\".",
    template: { ru: "Я приду после ___.", fr: "Je viendrai après ___." },
  },
  {
    id: "prep-gen-vovremya",
    accepts: ["time", "abstract"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "во время",
    meaningFr: "\"Pendant\".",
    template: { ru: "Я молчал во время ___.", fr: "Je me suis tu pendant ___." },
  },
  {
    id: "prep-gen-okolo",
    accepts: ["place", "area"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "около",
    meaningFr: "\"Près de\", \"environ\".",
    template: { ru: "Магазин около ___.", fr: "Le magasin est près de ___." },
  },
  {
    id: "prep-gen-vokrug",
    accepts: ["place", "area", "object"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "вокруг",
    meaningFr: "\"Autour de\".",
    template: { ru: "Дети бегали вокруг ___.", fr: "Les enfants couraient autour de ___." },
  },
  {
    id: "prep-gen-vdol",
    accepts: ["place", "area"],
    caseId: "genitive",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "вдоль",
    meaningFr: "\"Le long de\".",
    template: { ru: "Мы гуляли вдоль ___.", fr: "Nous nous sommes promenés le long de ___." },
  },
  {
    id: "prep-gen-mimo",
    accepts: ["place", "area", "object"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "мимо",
    meaningFr: "\"Devant\", \"en passant par\" (mouvement).",
    template: { ru: "Я прошёл мимо ___.", fr: "Je suis passé devant ___." },
  },
  {
    id: "prep-gen-naprotiv",
    accepts: ["place", "area"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "напротив",
    meaningFr: "\"En face de\".",
    template: { ru: "Кафе напротив ___.", fr: "Le café est en face de ___." },
  },
  {
    id: "prep-gen-sredi",
    accepts: ["human"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "среди",
    meaningFr: "\"Parmi\".",
    template: { ru: "Я чувствую себя одиноко среди ___.", fr: "Je me sens seul parmi ___." },
    plural: true,
  },
  {
    id: "prep-gen-protiv",
    accepts: ["human", "abstract"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "против",
    meaningFr: "\"Contre\".",
    template: { ru: "Я ничего не имею против ___.", fr: "Je n'ai rien contre ___." },
  },
  {
    id: "prep-gen-krome",
    accepts: ["human"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "кроме",
    meaningFr: "\"Sauf\", \"à part\".",
    template: { ru: "Все пришли, кроме ___.", fr: "Tout le monde est venu, sauf ___." },
  },
  {
    id: "prep-gen-vmesto",
    accepts: ["food", "drink"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "none",
    ru: "вместо",
    meaningFr: "\"Au lieu de\".",
    template: { ru: "Возьми чай вместо ___.", fr: "Prends du thé au lieu de ___." },
  },
  {
    id: "prep-gen-izza",
    accepts: ["human", "abstract"],
    caseId: "genitive",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "из-за",
    meaningFr: "\"À cause de\".",
    template: { ru: "Я опоздал из-за ___.", fr: "Je suis arrivé en retard à cause de ___." },
  },
  {
    id: "prep-gen-izpod",
    accepts: ["object", "place", "area"],
    caseId: "genitive",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "из-под",
    meaningFr: "\"De dessous\".",
    template: { ru: "Кот вылез из-под ___.", fr: "Le chat est sorti de dessous ___." },
  },
  {
    id: "prep-gen-bez",
    caseId: "genitive",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "без",
    meaningFr: "Absence, \"sans\".",
    template: { ru: "Я не могу жить без ___.", fr: "Je ne peux pas vivre sans ___." },
  },
  {
    id: "prep-gen-dlya",
    accepts: ["human"],
    caseId: "genitive",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "для",
    meaningFr: "Destination, \"pour\".",
    template: { ru: "Это подарок для ___.", fr: "C'est un cadeau pour ___." },
  },
  {
    id: "prep-gen-vnutri",
    accepts: ["object", "place"],
    caseId: "genitive",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "внутри",
    meaningFr: "\"À l'intérieur de\".",
    template: { ru: "Кот сидит внутри ___.", fr: "Le chat est assis à l'intérieur de ___." },
  },
  {
    id: "prep-gen-radi",
    accepts: ["human", "abstract"],
    caseId: "genitive",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "ради",
    meaningFr: "\"Pour l'amour de\", \"pour le bien de\".",
    template: { ru: "Я сделал это ради ___.", fr: "J'ai fait ça pour ___." },
  },
  {
    id: "prep-gen-nakanune",
    accepts: ["time"],
    caseId: "genitive",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "накануне",
    meaningFr: "\"La veille de\".",
    template: { ru: "Я пришёл накануне ___.", fr: "Je suis venu la veille de ___." },
  },
  {
    id: "prep-gen-vrode",
    accepts: ["object", "animal", "food", "drink", "abstract"],
    caseId: "genitive",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "вроде",
    meaningFr: "\"Une sorte de\", \"comme\" (familier).",
    template: { ru: "Это что-то вроде ___.", fr: "C'est une sorte de ___." },
  },
  // Verbes
  {
    id: "verb-gen-boyatsya",
    accepts: ["human", "animal", "abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "бояться",
    meaningFr: "\"Avoir peur de\" se construit au génitif.",
    template: { ru: "Я боюсь ___.", fr: "J'ai peur de ___." },
  },
  {
    id: "verb-gen-izbegat",
    accepts: ["human", "abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "избегать",
    meaningFr: "\"Éviter\" se construit au génitif.",
    template: { ru: "Я избегаю ___.", fr: "J'évite ___." },
  },
  {
    id: "verb-gen-zhelat",
    accepts: ["abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "желать",
    meaningFr: "\"Souhaiter\" se construit au génitif (surtout dans les vœux).",
    template: { ru: "Желаю тебе ___.", fr: "Je te souhaite ___." },
  },
  {
    id: "verb-gen-trebovat",
    accepts: ["abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "требовать",
    meaningFr: "\"Exiger\" se construit au génitif.",
    template: { ru: "Я требую ___.", fr: "J'exige ___." },
  },
  {
    id: "verb-gen-kasatsya",
    accepts: ["human", "abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "касаться",
    meaningFr: "\"Concerner\" se construit au génitif.",
    template: { ru: "Это касается ___.", fr: "Ça concerne ___." },
  },
  {
    id: "verb-gen-dostigat",
    accepts: ["place", "area", "abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "достигать",
    meaningFr: "\"Atteindre, parvenir à\" se construit au génitif.",
    template: { ru: "Мы достигли ___.", fr: "Nous avons atteint ___." },
  },
  {
    id: "verb-gen-vypit",
    accepts: ["drink"],
    caseId: "genitive",
    kind: "verb",
    tier: "intermediate",
    article: "none",
    ru: "выпить",
    meaningFr: "Génitif partitif : boire UNE PARTIE de (contraste avec l'accusatif пить qui boit la chose entière/précise).",
    template: { ru: "Я хочу выпить ___.", fr: "Je veux boire un peu de ___." },
  },
  {
    id: "verb-gen-lishitsya",
    accepts: ["object", "abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "лишиться",
    meaningFr: "\"Perdre, être privé de\" se construit au génitif.",
    template: { ru: "Он лишился ___.", fr: "Il a perdu ___." },
  },
  {
    id: "verb-gen-stesnyatsya",
    accepts: ["human", "abstract"],
    caseId: "genitive",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "стесняться",
    meaningFr: "\"Avoir honte de, être gêné par\" se construit au génitif.",
    template: { ru: "Не стесняйся ___.", fr: "N'aie pas honte de ___." },
  },
  {
    id: "verb-gen-slushatsya",
    accepts: ["human"],
    caseId: "genitive",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "слушаться",
    meaningFr: "\"Obéir à\" se construit au génitif.",
    template: { ru: "Дети слушаются ___.", fr: "Les enfants obéissent à ___." },
  },
  // Adjectifs / expressions figées
  {
    id: "expr-gen-polnyy",
    accepts: ["drink", "food"],
    caseId: "genitive",
    kind: "expression",
    tier: "intermediate",
    article: "none",
    ru: "полный",
    meaningFr: "\"Plein de\" se construit au génitif.",
    template: { ru: "Стакан полный ___.", fr: "Le verre est plein de ___." },
  },
  {
    id: "expr-gen-dostoin",
    accepts: ["abstract"],
    caseId: "genitive",
    kind: "expression",
    tier: "advanced",
    article: "demonstrative",
    ru: "достоин",
    meaningFr: "\"Digne de\" se construit au génitif.",
    template: { ru: "Он достоин ___.", fr: "Il est digne de ___." },
  },
  {
    id: "expr-gen-zhal",
    accepts: ["human", "abstract"],
    caseId: "genitive",
    kind: "expression",
    tier: "basic",
    article: "demonstrative",
    ru: "жаль",
    meaningFr: "\"Avoir de la peine pour\" se construit au génitif.",
    template: { ru: "Мне жаль ___.", fr: "Je suis désolé pour ___." },
  },

  // ─── Datif ──────────────────────────────────────────────────────
  {
    id: "prep-dat-k",
    accepts: ["place", "area", "human"],
    caseId: "dative",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "к",
    meaningFr: "Direction vers quelqu'un/quelque chose.",
    template: { ru: "Я иду к ___.", fr: "Je vais vers ___." },
  },
  {
    id: "prep-dat-po",
    accepts: ["place", "area"],
    caseId: "dative",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "по",
    meaningFr: "\"Le long de\", \"selon\".",
    template: { ru: "Я гуляю по ___.", fr: "Je me promène le long de ___." },
  },
  {
    id: "prep-dat-blagodarya",
    accepts: ["human", "abstract"],
    caseId: "dative",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "благодаря",
    meaningFr: "\"Grâce à\".",
    template: { ru: "Мы победили благодаря ___.", fr: "Nous avons gagné grâce à ___." },
  },
  {
    id: "prep-dat-vopreki",
    accepts: ["abstract"],
    caseId: "dative",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "вопреки",
    meaningFr: "\"Malgré\", \"contrairement à\".",
    template: { ru: "Мы выиграли вопреки ___.", fr: "Nous avons gagné malgré ___." },
  },
  {
    id: "prep-dat-soglasno",
    accepts: ["human", "abstract"],
    caseId: "dative",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "согласно",
    meaningFr: "\"Selon\", \"conformément à\" (registre plutôt formel).",
    template: { ru: "Согласно ___, это правда.", fr: "Selon ___, c'est vrai." },
  },
  {
    id: "verb-dat-pomogat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "помогать",
    meaningFr: "\"Aider quelqu'un\" se construit au datif.",
    template: { ru: "Я помогаю ___.", fr: "J'aide ___." },
  },
  {
    id: "verb-dat-zvonit",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "звонить",
    meaningFr: "\"Téléphoner à quelqu'un\" se construit au datif.",
    template: { ru: "Я звоню ___.", fr: "J'appelle ___." },
  },
  {
    id: "verb-dat-nravitsya",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "нравиться",
    meaningFr: "\"Plaire à quelqu'un\" se construit au datif.",
    template: { ru: "Эта музыка нравится ___.", fr: "Cette musique plaît à ___." },
  },
  {
    id: "verb-dat-davat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "давать",
    meaningFr: "\"Donner à quelqu'un\" se construit au datif.",
    template: { ru: "Я даю подарок ___.", fr: "Je donne un cadeau à ___." },
  },
  {
    id: "verb-dat-verit",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "верить",
    meaningFr: "\"Croire quelqu'un\" se construit au datif.",
    template: { ru: "Я верю ___.", fr: "Je crois ___." },
  },
  {
    id: "verb-dat-doveryat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "доверять",
    meaningFr: "\"Faire confiance à\" se construit au datif.",
    template: { ru: "Я доверяю ___.", fr: "Je fais confiance à ___." },
  },
  {
    id: "verb-dat-sovetovat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "советовать",
    meaningFr: "\"Conseiller à quelqu'un\" se construit au datif.",
    template: { ru: "Я советую ___.", fr: "Je conseille ___." },
  },
  {
    id: "verb-dat-zavidovat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "завидовать",
    meaningFr: "\"Envier quelqu'un\" se construit au datif.",
    template: { ru: "Я завидую ___.", fr: "J'envie ___." },
  },
  {
    id: "verb-dat-otvechat",
    accepts: ["human", "abstract"],
    caseId: "dative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "отвечать",
    meaningFr: "\"Répondre à quelqu'un\" se construit au datif.",
    template: { ru: "Я отвечаю ___.", fr: "Je réponds à ___." },
  },
  {
    id: "verb-dat-meshat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "мешать",
    meaningFr: "\"Déranger quelqu'un\" se construit au datif.",
    template: { ru: "Не мешай ___.", fr: "Ne dérange pas ___." },
  },
  {
    id: "verb-dat-razreshat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "разрешать",
    meaningFr: "\"Permettre à quelqu'un\" se construit au datif.",
    template: { ru: "Мама разрешает ___.", fr: "Maman donne la permission à ___." },
  },
  {
    id: "verb-dat-udivlyatsya",
    accepts: ["human", "abstract"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "удивляться",
    meaningFr: "\"Être surpris de\" se construit au datif.",
    template: { ru: "Я удивляюсь ___.", fr: "Je suis surpris de ___." },
  },
  {
    id: "verb-dat-radovatsya",
    accepts: ["human", "abstract"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "радоваться",
    meaningFr: "\"Se réjouir de\" se construit au datif.",
    template: { ru: "Я радуюсь ___.", fr: "Je me réjouis de ___." },
  },
  {
    id: "verb-dat-prinadlezhat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "принадлежать",
    meaningFr: "\"Appartenir à\" se construit au datif.",
    template: { ru: "Эта идея принадлежит ___.", fr: "Cette idée appartient à ___." },
  },
  {
    id: "verb-dat-sochuvstvovat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "сочувствовать",
    meaningFr: "\"Compatir avec\" se construit au datif.",
    template: { ru: "Я сочувствую ___.", fr: "Je compatis avec ___." },
  },
  {
    id: "verb-dat-ugrozhat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "угрожать",
    meaningFr: "\"Menacer\" se construit au datif.",
    template: { ru: "Он угрожает ___.", fr: "Il menace ___." },
  },
  {
    id: "verb-dat-podchinyatsya",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "подчиняться",
    meaningFr: "\"Obéir à, se soumettre à\" se construit au datif.",
    template: { ru: "Мы подчиняемся ___.", fr: "Nous obéissons à ___." },
  },
  {
    id: "verb-dat-soprotivlyatsya",
    accepts: ["human", "abstract"],
    caseId: "dative",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "сопротивляться",
    meaningFr: "\"Résister à\" se construit au datif.",
    template: { ru: "Я сопротивляюсь ___.", fr: "Je résiste à ___." },
  },
  {
    id: "verb-dat-aplodirovat",
    accepts: ["human"],
    caseId: "dative",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "аплодировать",
    meaningFr: "\"Applaudir\" se construit au datif.",
    template: { ru: "Зрители аплодируют ___.", fr: "Les spectateurs applaudissent ___." },
  },
  {
    id: "verb-dat-sluzhit",
    accepts: ["human", "abstract"],
    caseId: "dative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "служить",
    meaningFr: "\"Servir\" se construit au datif.",
    template: { ru: "Я служу ___.", fr: "Je sers ___." },
  },

  // ─── Accusatif ──────────────────────────────────────────────────
  {
    id: "verb-acc-videt",
    accepts: ["human", "animal", "object", "food", "drink", "place", "area"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "видеть",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я вижу ___.", fr: "Je vois ___." },
  },
  {
    id: "verb-acc-lyubit",
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "любить",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я люблю ___.", fr: "J'aime ___." },
  },
  {
    id: "verb-acc-chitat",
    accepts: ["text"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "читать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я читаю ___.", fr: "Je lis ___." },
  },
  {
    id: "verb-acc-znat",
    accepts: ["human", "abstract", "place", "area"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "знать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я хорошо знаю ___.", fr: "Je connais bien ___." },
  },
  {
    id: "verb-acc-pokupat",
    accepts: ["object", "text", "food", "drink", "animal"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "покупать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я покупаю ___.", fr: "J'achète ___." },
  },
  {
    id: "verb-acc-pisat",
    accepts: ["text"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "писать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я пишу ___.", fr: "J'écris ___." },
  },
  {
    id: "verb-acc-ponimat",
    accepts: ["human", "text", "abstract"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "понимать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я понимаю ___.", fr: "Je comprends ___." },
  },
  {
    id: "verb-acc-slushat",
    accepts: ["human", "abstract"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "слушать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я слушаю ___.", fr: "J'écoute ___." },
  },
  {
    id: "verb-acc-est",
    accepts: ["food"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "есть",
    meaningFr: "\"Manger\" (à ne pas confondre avec есть \"il y a\", qui n'a pas de complément).",
    template: { ru: "Я ем ___.", fr: "Je mange ___." },
  },
  {
    id: "verb-acc-pit",
    accepts: ["drink"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "пить",
    meaningFr: "Complément d'objet direct (contraste avec выпить + génitif pour \"boire un peu de\").",
    template: { ru: "Я пью ___.", fr: "Je bois ___." },
  },
  {
    id: "verb-acc-delat",
    accepts: ["abstract"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "делать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я делаю ___.", fr: "Je fais ___." },
  },
  {
    id: "verb-acc-vstrechat",
    accepts: ["human"],
    caseId: "accusative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "встречать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я встречаю ___.", fr: "Je rencontre ___." },
  },
  {
    id: "verb-acc-brat",
    accepts: ["object", "text", "food", "drink"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "брать",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я беру ___.", fr: "Je prends ___." },
  },
  {
    id: "verb-acc-izuchat",
    accepts: ["abstract", "text"],
    caseId: "accusative",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "изучать",
    meaningFr: "Complément d'objet direct (étudier une matière, une langue).",
    template: { ru: "Я изучаю ___.", fr: "J'étudie ___." },
  },
  {
    id: "verb-acc-nenavidet",
    caseId: "accusative",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "ненавидеть",
    meaningFr: "Complément d'objet direct.",
    template: { ru: "Я ненавижу ___.", fr: "Je déteste ___." },
  },
  {
    id: "prep-acc-v",
    accepts: ["place"],
    caseId: "accusative",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "в",
    meaningFr: "Mouvement vers l'intérieur (\"dans\").",
    template: { ru: "Я иду в ___.", fr: "Je vais dans ___." },
  },
  {
    id: "prep-acc-na",
    accepts: ["human", "animal", "object", "place", "area"],
    caseId: "accusative",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "на",
    meaningFr: "Mouvement vers une surface (\"sur\") ou \"regarder qqch\".",
    template: { ru: "Я смотрю на ___.", fr: "Je regarde ___." },
  },
  {
    id: "prep-acc-za",
    accepts: ["abstract", "object", "food", "drink"],
    caseId: "accusative",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "за",
    meaningFr: "\"En échange de\", \"merci pour\".",
    template: { ru: "Спасибо за ___.", fr: "Merci pour ___." },
  },
  {
    id: "prep-acc-cherez",
    accepts: ["place", "area"],
    caseId: "accusative",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "через",
    meaningFr: "\"À travers\", \"en passant par\".",
    template: { ru: "Мы едем через ___.", fr: "Nous passons par ___." },
  },
  {
    id: "prep-acc-pro",
    caseId: "accusative",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "про",
    meaningFr: "\"À propos de\" (familier, équivalent oral de о + prépositionnel).",
    template: { ru: "Расскажи мне про ___.", fr: "Raconte-moi à propos de ___." },
  },
  {
    id: "prep-acc-skvoz",
    accepts: ["object", "place", "area"],
    caseId: "accusative",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "сквозь",
    meaningFr: "\"À travers\" (sens physique, plus fort que через).",
    template: { ru: "Я вижу свет сквозь ___.", fr: "Je vois la lumière à travers ___." },
  },
  {
    id: "prep-acc-nesmotrya-na",
    accepts: ["abstract"],
    caseId: "accusative",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "несмотря на",
    meaningFr: "\"Malgré\".",
    template: { ru: "Несмотря на ___, мы пошли гулять.", fr: "Malgré ___, nous sommes sortis nous promener." },
  },

  // ─── Instrumental ───────────────────────────────────────────────
  {
    id: "prep-instr-s",
    accepts: ["human"],
    caseId: "instrumental",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "с",
    meaningFr: "Accompagnement, \"avec\".",
    template: { ru: "Я пью чай с ___.", fr: "Je bois du thé avec ___." },
  },
  {
    id: "prep-instr-pod",
    accepts: ["object", "place", "area"],
    caseId: "instrumental",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "под",
    meaningFr: "Lieu statique, \"sous\".",
    template: { ru: "Кот спит под ___.", fr: "Le chat dort sous ___." },
  },
  {
    id: "prep-instr-nad",
    accepts: ["object", "place", "area"],
    caseId: "instrumental",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "над",
    meaningFr: "Lieu statique, \"au-dessus de\".",
    template: { ru: "Лампа висит над ___.", fr: "La lampe est suspendue au-dessus de ___." },
  },
  {
    id: "prep-instr-pered",
    accepts: ["object", "place", "area"],
    caseId: "instrumental",
    kind: "preposition",
    tier: "intermediate",
    article: "demonstrative",
    ru: "перед",
    meaningFr: "Lieu statique, \"devant\".",
    template: { ru: "Мы встретимся перед ___.", fr: "On se retrouve devant ___." },
  },
  {
    id: "expr-instr-rabotat",
    accepts: ["human"],
    caseId: "instrumental",
    kind: "expression",
    tier: "basic",
    article: "demonstrative",
    ru: "работать +",
    meaningFr: "Métier, profession exercée.",
    template: { ru: "Он работает ___.", fr: "Il travaille comme ___." },
  },
  {
    id: "expr-instr-stat",
    accepts: ["human"],
    caseId: "instrumental",
    kind: "expression",
    tier: "intermediate",
    article: "demonstrative",
    ru: "стать +",
    meaningFr: "Devenir quelque chose.",
    template: { ru: "Он хочет стать ___.", fr: "Il veut devenir ___." },
  },
  {
    id: "verb-instr-yavlyatsya",
    accepts: ["abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "являться",
    meaningFr: "\"Être, constituer\" (registre formel) se construit à l'instrumental.",
    template: { ru: "Это является ___.", fr: "Ceci constitue ___." },
  },
  {
    id: "verb-instr-kazatsya",
    accepts: ["human", "abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "казаться",
    meaningFr: "\"Sembler être\" se construit à l'instrumental.",
    template: { ru: "Он кажется ___.", fr: "Il semble être ___." },
  },
  {
    id: "verb-instr-schitatsya",
    accepts: ["human", "abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "считаться",
    meaningFr: "\"Être considéré comme\" se construit à l'instrumental.",
    template: { ru: "Он считается ___.", fr: "Il est considéré comme ___." },
  },
  {
    id: "verb-instr-interesovatsya",
    accepts: ["abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "интересоваться",
    meaningFr: "\"S'intéresser à\" se construit à l'instrumental.",
    template: { ru: "Я интересуюсь ___.", fr: "Je m'intéresse à ___." },
  },
  {
    id: "verb-instr-gorditsya",
    accepts: ["human", "abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "гордиться",
    meaningFr: "\"Être fier de\" se construit à l'instrumental.",
    template: { ru: "Я горжусь ___.", fr: "Je suis fier de ___." },
  },
  {
    id: "verb-instr-zanimatsya",
    accepts: ["abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "заниматься",
    meaningFr: "\"Pratiquer, s'occuper de\" se construit à l'instrumental.",
    template: { ru: "Я занимаюсь ___.", fr: "Je pratique ___." },
  },
  {
    id: "verb-instr-uvlekatsya",
    accepts: ["abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "увлекаться",
    meaningFr: "\"Être passionné par\" se construit à l'instrumental.",
    template: { ru: "Он увлекается ___.", fr: "Il est passionné par ___." },
  },
  {
    id: "verb-instr-polzovatsya",
    accepts: ["object", "text"],
    caseId: "instrumental",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "пользоваться",
    meaningFr: "\"Utiliser, se servir de\" se construit à l'instrumental.",
    template: { ru: "Я пользуюсь ___.", fr: "J'utilise ___." },
  },
  {
    id: "verb-instr-vladet",
    accepts: ["abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "владеть",
    meaningFr: "\"Maîtriser, posséder\" (une langue, un bien) se construit à l'instrumental.",
    template: { ru: "Я владею ___.", fr: "Je maîtrise ___." },
  },
  {
    id: "verb-instr-upravlyat",
    accepts: ["human", "abstract", "place"],
    caseId: "instrumental",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "управлять",
    meaningFr: "\"Diriger, conduire\" se construit à l'instrumental.",
    template: { ru: "Он управляет ___.", fr: "Il dirige ___." },
  },
  {
    id: "verb-instr-voskhishchatsya",
    accepts: ["human", "abstract", "place", "area"],
    caseId: "instrumental",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "восхищаться",
    meaningFr: "\"Admirer\" se construit à l'instrumental.",
    template: { ru: "Я восхищаюсь ___.", fr: "J'admire ___." },
  },
  {
    id: "verb-instr-riskovat",
    accepts: ["abstract"],
    caseId: "instrumental",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "рисковать",
    meaningFr: "\"Risquer\" se construit à l'instrumental.",
    template: { ru: "Не рискуй ___.", fr: "Ne risque pas ___." },
  },
  {
    id: "verb-instr-torgovat",
    accepts: ["object", "food", "drink"],
    caseId: "instrumental",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "торговать",
    meaningFr: "\"Faire le commerce de\" se construit à l'instrumental.",
    template: { ru: "Он торгует ___.", fr: "Il fait le commerce de ___." },
  },
  {
    id: "verb-instr-dorozhit",
    accepts: ["human", "abstract", "object"],
    caseId: "instrumental",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "дорожить",
    meaningFr: "\"Tenir à, accorder de la valeur à\" se construit à l'instrumental.",
    template: { ru: "Я дорожу ___.", fr: "Je tiens à ___." },
  },

  // ─── Prépositionnel ─────────────────────────────────────────────
  // Par nature, seules 4 prépositions gouvernent ce cas (в, на, о, при) —
  // sa richesse vient des verbes, pas des prépositions.
  {
    id: "prep-prep-v",
    accepts: ["place"],
    caseId: "prepositional",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "в",
    meaningFr: "Lieu statique (\"dans\").",
    template: { ru: "Я живу в ___.", fr: "J'habite dans ___." },
  },
  {
    id: "prep-prep-na",
    accepts: ["place", "abstract"],
    caseId: "prepositional",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "на",
    meaningFr: "Lieu statique (\"sur\", \"à\").",
    template: { ru: "Я работаю на ___.", fr: "Je travaille sur/à ___." },
  },
  {
    id: "prep-prep-o",
    caseId: "prepositional",
    kind: "preposition",
    tier: "basic",
    article: "demonstrative",
    ru: "о",
    meaningFr: "Sujet dont on parle, \"à propos de\".",
    template: { ru: "Я думаю о ___.", fr: "Je pense à ___." },
  },
  {
    id: "prep-prep-pri",
    accepts: ["place"],
    caseId: "prepositional",
    kind: "preposition",
    tier: "advanced",
    article: "demonstrative",
    ru: "при",
    meaningFr: "\"Rattaché à\", \"auprès de\".",
    template: { ru: "Библиотека при ___.", fr: "La bibliothèque est rattachée à ___." },
  },
  {
    id: "expr-prep-nakhoditsya",
    accepts: ["place"],
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "находиться",
    meaningFr: "\"Se trouver\" (registre soutenu de \"être quelque part\") se construit avec в/на + prépositionnel.",
    template: { ru: "Дом находится в ___.", fr: "La maison se trouve dans ___." },
  },
  {
    id: "verb-prep-govorit",
    caseId: "prepositional",
    kind: "verb",
    tier: "basic",
    article: "demonstrative",
    ru: "говорить о",
    meaningFr: "\"Parler de\" se construit au prépositionnel.",
    template: { ru: "Мы говорим о ___.", fr: "Nous parlons de ___." },
  },
  {
    id: "verb-prep-sporit",
    accepts: ["abstract"],
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "спорить о",
    meaningFr: "\"Discuter, se disputer à propos de\" se construit au prépositionnel.",
    template: { ru: "Мы спорим о ___.", fr: "Nous discutons de ___." },
  },
  {
    id: "verb-prep-mechtat",
    accepts: ["abstract", "object", "place", "area"],
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "мечтать о",
    meaningFr: "\"Rêver de\" se construit au prépositionnel.",
    template: { ru: "Я мечтаю о ___.", fr: "Je rêve de ___." },
  },
  {
    id: "verb-prep-slyshat",
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "слышать о",
    meaningFr: "\"Entendre parler de\" se construit au prépositionnel.",
    template: { ru: "Я слышал о ___.", fr: "J'ai entendu parler de ___." },
  },
  {
    id: "verb-prep-chitat",
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "читать о",
    meaningFr: "\"Lire à propos de\" se construit au prépositionnel.",
    template: { ru: "Я читаю о ___.", fr: "Je lis à propos de ___." },
  },
  {
    id: "verb-prep-znat",
    accepts: ["abstract"],
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "знать о",
    meaningFr: "\"Être au courant de\" se construit au prépositionnel.",
    template: { ru: "Я знаю о ___.", fr: "Je suis au courant de ___." },
  },
  {
    id: "verb-prep-rasskazyvat",
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "рассказывать о",
    meaningFr: "\"Raconter à propos de\" se construit au prépositionnel.",
    template: { ru: "Расскажи мне о ___.", fr: "Parle-moi de ___." },
  },
  {
    id: "verb-prep-zabotitsya",
    accepts: ["human", "animal"],
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "заботиться о",
    meaningFr: "\"S'occuper de, prendre soin de\" se construit au prépositionnel.",
    template: { ru: "Я забочусь о ___.", fr: "Je prends soin de ___." },
  },
  {
    id: "verb-prep-bespokoitsya",
    accepts: ["human", "abstract"],
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "беспокоиться о",
    meaningFr: "\"S'inquiéter de\" se construit au prépositionnel.",
    template: { ru: "Я беспокоюсь о ___.", fr: "Je m'inquiète pour ___." },
  },
  {
    id: "verb-prep-soobshchat",
    accepts: ["abstract"],
    caseId: "prepositional",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "сообщать о",
    meaningFr: "\"Informer de, annoncer\" se construit au prépositionnel.",
    template: { ru: "Я сообщаю о ___.", fr: "J'informe de ___." },
  },
  {
    id: "verb-prep-vspominat",
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "вспоминать о",
    meaningFr: "\"Se souvenir de\" se construit au prépositionnel.",
    template: { ru: "Я вспоминаю о ___.", fr: "Je me souviens de ___." },
  },
  {
    id: "verb-prep-upominat",
    accepts: ["human", "abstract"],
    caseId: "prepositional",
    kind: "verb",
    tier: "advanced",
    article: "demonstrative",
    ru: "упоминать о",
    meaningFr: "\"Mentionner\" se construit au prépositionnel.",
    template: { ru: "Я упоминаю о ___.", fr: "Je mentionne ___." },
  },
  {
    id: "verb-prep-zhalet",
    accepts: ["abstract"],
    caseId: "prepositional",
    kind: "verb",
    tier: "intermediate",
    article: "demonstrative",
    ru: "жалеть о",
    meaningFr: "\"Regretter\" se construit au prépositionnel.",
    template: { ru: "Я жалею о ___.", fr: "Je regrette ___." },
  },
];

export function triggersForCase(caseId: CaseId): CaseTrigger[] {
  return TRIGGERS.filter((t) => t.caseId === caseId);
}

export function getTrigger(id: string): CaseTrigger | undefined {
  return TRIGGERS.find((t) => t.id === id);
}
