// Généré par scripts/curate-adjectives.mjs — ne pas éditer à la main.
//
// Les contextes SUPPLÉMENTAIRES de chaque compétence. Les douze premiers de
// chacune restent écrits à la main dans exercises.ts : ils fixent le style
// et servent de référence au modèle.
//
// Un contexte fige un couple adjectif + nom, et c'est voulu — voir l'en-tête
// d'exercises.ts. Il en faut donc BEAUCOUP, pas des viviers à croiser.
//
// 105 contextes supplémentaires.

import type { AdjectiveContext } from "./exercises";

export const ADJECTIVE_CONTEXTS_EXTRA: Record<string, AdjectiveContext[]> = {
  nominative: [
    {
      id: "novyy-magazin-otkrylsya",
      adjective: "novyy",
      noun: "magazin",
      case: "nominative",
      ru: "На наше́й у́лице откры́лся ___ {N}.",
      fr: "Un nouveau magasin a ouvert dans notre rue.",
      why: "« магазин » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "staryy-dedushka-ustal",
      adjective: "staryy",
      noun: "dedushka",
      case: "nominative",
      ru: "___ {N} уста́л по́сле прогу́лки.",
      fr: "Le vieux grand-père est fatigué après la promenade.",
      why: "« дедушка » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "krasivyy-braslet-podarok",
      adjective: "krasivyy",
      noun: "braslet",
      case: "nominative",
      ru: "Э́то ___ {N}, ты его́ сама́ купи́ла?",
      fr: "C'est un beau bracelet, tu l'as acheté toi-même ?",
      why: "« браслет » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "molodoy-ofitser-prishyol",
      adjective: "molodoy",
      noun: "ofitser",
      case: "nominative",
      ru: "___ {N} пришёл на встре́чу во́время.",
      fr: "Le jeune officier est arrivé à l'heure au rendez-vous.",
      why: "« офицер » est masculin singulier : au nominatif, l'adjectif prend -ой.",
    },
    {
      id: "vkusnyy-syr-lezhit",
      adjective: "vkusnyy",
      noun: "syr",
      case: "nominative",
      ru: "На столе́ лежи́т ___ {N} из дере́вни.",
      fr: "Un fromage délicieux venu du village est posé sur la table.",
      why: "« сыр » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "interesnyy-zhurnal-lezhit",
      adjective: "interesnyy",
      noun: "zhurnal",
      case: "nominative",
      ru: "На ку́хне лежи́т ___ {N} про живо́тных.",
      fr: "Un magazine intéressant sur les animaux est posé dans la cuisine.",
      why: "« журнал » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "krasivyy-kot-spit",
      adjective: "krasivyy",
      noun: "kot",
      case: "nominative",
      ru: "На кре́сле спит ___ {N} сосе́дки.",
      fr: "Un beau chat de la voisine dort dans le fauteuil.",
      why: "« кот » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "molodoy-pisatel-vystupil",
      adjective: "molodoy",
      noun: "pisatel",
      case: "nominative",
      ru: "На встре́че вы́ступил ___ {N} из Москвы́.",
      fr: "Un jeune écrivain de Moscou a pris la parole à la rencontre.",
      why: "« писатель » est masculin singulier : au nominatif, l'adjectif prend -ой.",
    },
    {
      id: "novyy-sosed-priekhal",
      adjective: "novyy",
      noun: "sosed",
      case: "nominative",
      ru: "Вчера́ к нам ___ {N} прие́хал.",
      fr: "Hier, un nouveau voisin est arrivé chez nous.",
      why: "« сосед » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "staryy-shpion-molchal",
      adjective: "staryy",
      noun: "shpion",
      case: "nominative",
      ru: "___ {N} молча́л на допро́се.",
      fr: "Le vieil espion s'est taisant pendant l'interrogatoire.",
      why: "« шпион » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "krasivaya-nevesta-tantsevala",
      adjective: "krasivyy",
      noun: "nevesta",
      case: "nominative",
      ru: "На сва́дьбе ___ {N} танцева́ла до́лго.",
      fr: "Au mariage, la belle fiancée a dansé longtemps.",
      why: "« невеста » est féminin singulier : au nominatif, l'adjectif prend -ая.",
    },
    {
      id: "molodoy-korol-pravit",
      adjective: "molodoy",
      noun: "korol",
      case: "nominative",
      ru: "Тепе́рь э́той страно́й пра́вит ___ {N}.",
      fr: "Maintenant, c'est un jeune roi qui règne sur ce pays.",
      why: "« король » est masculin singulier : au nominatif, l'adjectif prend -ой.",
    },
    {
      id: "umnaya-koshka-otkryla",
      adjective: "umnyy",
      noun: "koshka",
      case: "nominative",
      ru: "___ {N} сама́ откры́ла дверь.",
      fr: "La chatte intelligente a ouvert la porte elle-même.",
      why: "« кошка » est féminin singulier : au nominatif, l'adjectif prend -ая.",
    },
    {
      id: "vkusnoe-yabloko-lezhalo",
      adjective: "vkusnyy",
      noun: "yabloko",
      case: "nominative",
      ru: "На столе́ лежа́ло ___ {N}.",
      fr: "Une pomme délicieuse était posée sur la table.",
      why: "« яблоко » est neutre singulier : au nominatif, l'adjectif prend -ое.",
    },
    {
      id: "interesnyy-avtor-priehal",
      adjective: "interesnyy",
      noun: "avtor",
      case: "nominative",
      ru: "На встре́чу прие́хал ___ {N}.",
      fr: "Un auteur intéressant est venu à la rencontre.",
      why: "« автор » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "kholodnaya-noch-nastupila",
      adjective: "kholodnyy",
      noun: "noch",
      case: "nominative",
      ru: "Вдруг наступи́ла ___ {N}.",
      fr: "Soudain, une nuit froide est tombée.",
      why: "« ночь » est féminin singulier : au nominatif, l'adjectif prend -ая.",
    },
    {
      id: "tyoplaya-odezhda-lezhala",
      adjective: "tyoplyy",
      noun: "odezhda",
      case: "nominative",
      ru: "На крова́ти лежа́ла ___ {N}.",
      fr: "Des vêtements chauds étaient posés sur le lit.",
      why: "« одежда » est féminin singulier : au nominatif, l'adjectif prend -ая.",
    },
    {
      id: "staraya-koroleva-ushla",
      adjective: "staryy",
      noun: "koroleva",
      case: "nominative",
      ru: "___ {N} ти́хо ушла́ из за́ла.",
      fr: "La vieille reine est sortie silencieusement de la salle.",
      why: "« королева » est féminin singulier : au nominatif, l'adjectif prend -ая.",
    },
    {
      id: "krasivyy-dvorets-stoit",
      adjective: "krasivyy",
      noun: "most",
      case: "nominative",
      ru: "Че́рез ре́ку идёт ___ {N}.",
      fr: "Un beau pont traverse la rivière.",
      why: "« мост » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "molodaya-zhenshchina-voshla",
      adjective: "molodoy",
      noun: "zhenshchina",
      case: "nominative",
      ru: "В ко́мнату вошла́ ___ {N}.",
      fr: "Une jeune femme est entrée dans la pièce.",
      why: "« женщина » est féminin singulier : au nominatif, l'adjectif prend -ая.",
    },
    {
      id: "novyy-kompyuter-stoit",
      adjective: "novyy",
      noun: "kompyuter",
      case: "nominative",
      ru: "На столе́ стои́т ___ {N}.",
      fr: "Un nouvel ordinateur est sur la table.",
      why: "« компьютер » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "staryy-dedushka-otdykhaet",
      adjective: "staryy",
      noun: "dom",
      case: "nominative",
      ru: "Здесь стои́т ___ {N}.",
      fr: "Il y a une vieille maison ici.",
      why: "« дом » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
    {
      id: "krasivyy-tsvetok-tsena",
      adjective: "krasivyy",
      noun: "koltso",
      case: "nominative",
      ru: "Э́то о́чень ___ {N}.",
      fr: "C'est une très belle bague.",
      why: "« кольцо » est neutre singulier : au nominatif, l'adjectif prend -ое.",
    },
    {
      id: "kholodnyy-napitok-podan",
      adjective: "kholodnyy",
      noun: "napitok",
      case: "nominative",
      ru: "На столе́ стои́т ___ {N}.",
      fr: "Une boisson froide est sur la table.",
      why: "« напиток » est masculin singulier : au nominatif, l'adjectif prend -ый.",
    },
  ],
  spelling: [
    {
      id: "khoroshiy-vrach-gorod",
      adjective: "khoroshiy",
      noun: "vrach",
      case: "nominative",
      ru: "В э́том го́роде рабо́тает ___ {N}.",
      fr: "Dans cette ville travaille un bon médecin.",
      why: "« врач » est masculin singulier : au nominatif, l'adjectif prend -ий. Après ш, la règle des 7 lettres interdit ы : -ый s'écrit -ий.",
    },
    {
      id: "russkiy-pisatel-znayut",
      adjective: "russkiy",
      noun: "pisatel",
      case: "accusative",
      ru: "Все зна́ют э́того ___ {N}.",
      fr: "Tout le monde connaît cet écrivain russe.",
      why: "« писатель » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "yarkiy-galstuk-kupil",
      adjective: "yarkiy",
      noun: "galstuk",
      case: "accusative",
      ru: "Он купи́л ___ {N} для сва́дьбы.",
      fr: "Il a acheté une cravate voyante pour le mariage.",
      why: "« галстук » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ий. Après к, la règle des 7 lettres interdit ы : -ый s'écrit -ий.",
    },
    {
      id: "khoroshiy-uchitel-blagodarny",
      adjective: "khoroshiy",
      noun: "uchitel",
      case: "dative",
      ru: "Ученики́ благода́рны своему́ ___ {N}.",
      fr: "Les élèves sont reconnaissants envers leur bon professeur.",
      why: "« учитель » est masculin singulier : au datif, l'adjectif prend -ему. Après ш non accentué, о devient е : -ому s'écrit -ему.",
    },
    {
      id: "yarkiy-plate-devushki",
      adjective: "yarkiy",
      noun: "plate",
      case: "genitive",
      ru: "Цвет э́того ___ {N} мне о́чень нра́вится.",
      fr: "La couleur de cette robe voyante me plaît beaucoup.",
      why: "« платье » est neutre singulier : au génitif, l'adjectif prend -ого.",
    },
    {
      id: "russkiy-tovarishch-vstretil",
      adjective: "russkiy",
      noun: "tovarishch",
      case: "instrumental",
      ru: "Он познако́мился с э́тим ___ {N} в а́рмии.",
      fr: "Il a fait connaissance avec ce camarade russe à l'armée.",
      why: "« товарищ » est masculin singulier : à l'instrumental, l'adjectif prend -им. Après к, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "yarkiy-zhenshchina-govoril",
      adjective: "yarkiy",
      noun: "zhenshchina",
      case: "instrumental",
      ru: "Дире́ктор говори́л с э́той ___ {N} на приёме.",
      fr: "Le directeur a parlé avec cette femme éclatante à la réception.",
      why: "« женщина » est féminin singulier : à l'instrumental, l'adjectif prend -ой.",
    },
    {
      id: "khoroshiy-muzh-mechtaet",
      adjective: "khoroshiy",
      noun: "muzh",
      case: "genitive",
      ru: "У э́той же́нщины нет ___ {N}.",
      fr: "Cette femme n'a pas de bon mari.",
      why: "« муж » est masculin singulier : au génitif, l'adjectif prend -его. Après ш non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "russkiy-nachalnik-podarok",
      adjective: "russkiy",
      noun: "nachalnik",
      case: "dative",
      ru: "Секрета́рь дал пода́рок своему́ ___ {N}.",
      fr: "La secrétaire a donné un cadeau à son chef russe.",
      why: "« начальник » est masculin singulier : au datif, l'adjectif prend -ому.",
    },
    {
      id: "russkiy-geroy-filme",
      adjective: "russkiy",
      noun: "geroy",
      case: "prepositional",
      ru: "Мы говори́ли о ___ {N} в э́том фи́льме.",
      fr: "Nous avons parlé du héros russe dans ce film.",
      why: "« герой » est masculin singulier : au prépositionnel, l'adjectif prend -ом.",
    },
    {
      id: "khoroshiy-uchitel-shkole",
      adjective: "khoroshiy",
      noun: "uchitel",
      case: "instrumental",
      ru: "Он стал ___ {N} в наше́й шко́ле.",
      fr: "Il est devenu un bon professeur dans notre école.",
      why: "« учитель » est masculin singulier : à l'instrumental, l'adjectif prend -им. Après ш, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "yarkiy-geniy-vspominayut",
      adjective: "yarkiy",
      noun: "geniy",
      case: "accusative",
      ru: "Все до сих пор по́мнят э́того ___ {N}.",
      fr: "Tout le monde se souvient encore de ce génie brillant.",
      why: "« гений » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "khoroshiy-drug-podarok",
      adjective: "khoroshiy",
      noun: "drug",
      case: "dative",
      ru: "Я дал э́тот пода́рок своему́ ___ {N}.",
      fr: "J'ai donné ce cadeau à mon bon ami.",
      why: "« друг » est masculin singulier : au datif, l'adjectif prend -ему. Après ш non accentué, о devient е : -ому s'écrit -ему.",
    },
    {
      id: "russkiy-ofitser-forme",
      adjective: "russkiy",
      noun: "ofitser",
      case: "nominative",
      ru: "На фотогра́фии стои́т молодо́й ___ {N}.",
      fr: "Sur la photo se tient un jeune officier russe.",
      why: "« офицер » est masculin singulier : au nominatif, l'adjectif prend -ий. Après к, la règle des 7 lettres interdit ы : -ый s'écrit -ий.",
    },
    {
      id: "khoroshiy-sosed-doma",
      adjective: "khoroshiy",
      noun: "sosed",
      case: "genitive",
      ru: "Мы жда́ли ___ {N} у до́ма.",
      fr: "Nous attendions le bon voisin près de la maison.",
      why: "« сосед » est masculin singulier : au génitif, l'adjectif prend -его. Après ш non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "yarkiy-khudozhnik-vystavke",
      adjective: "yarkiy",
      noun: "khudozhnik",
      case: "instrumental",
      ru: "Она́ была́ знако́ма с э́тим ___ {N}.",
      fr: "Elle connaissait ce peintre brillant.",
      why: "« художник » est masculin singulier : à l'instrumental, l'adjectif prend -им. Après к, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "khoroshiy-muzhchina-vstretila",
      adjective: "khoroshiy",
      noun: "muzhchina",
      case: "accusative",
      ru: "Она́ встре́тила там ___ {N}.",
      fr: "Elle a rencontré là un homme bien.",
      why: "« мужчина » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -его. Après ш non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "russkiy-tovarishch-pisal",
      adjective: "russkiy",
      noun: "tovarishch",
      case: "dative",
      ru: "Он написа́л письмо́ своему́ ___ {N}.",
      fr: "Il a écrit une lettre à son camarade russe.",
      why: "« товарищ » est masculin singulier : au datif, l'adjectif prend -ому.",
    },
    {
      id: "khoroshiy-otets-detyam",
      adjective: "khoroshiy",
      noun: "otets",
      case: "nominative",
      ru: "Все говоря́т, что он ___ {N}.",
      fr: "Tout le monde dit que c'est un bon père.",
      why: "« отец » est masculin singulier : au nominatif, l'adjectif prend -ий. Après ш, la règle des 7 lettres interdit ы : -ый s'écrit -ий.",
    },
    {
      id: "khoroshiy-khleb-magazine",
      adjective: "khoroshiy",
      noun: "khleb",
      case: "accusative",
      ru: "Мы купи́ли в магази́не ___ {N}.",
      fr: "Nous avons acheté du bon pain au magasin.",
      why: "« хлеб » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ий. Après ш, la règle des 7 lettres interdit ы : -ый s'écrit -ий.",
    },
    {
      id: "khoroshiy-vino-vecherom",
      adjective: "khoroshiy",
      noun: "vino",
      case: "genitive",
      ru: "Ве́чером у нас не бы́ло ___ {N}.",
      fr: "Le soir, nous n'avions pas de bon vin.",
      why: "« вино » est neutre singulier : au génitif, l'adjectif prend -его. Après ш non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "russkiy-nozh-podarok",
      adjective: "russkiy",
      noun: "nozh",
      case: "instrumental",
      ru: "Он ре́жет хлеб ___ {N}.",
      fr: "Il coupe le pain avec un couteau russe.",
      why: "« нож » est masculin singulier : à l'instrumental, l'adjectif prend -им. Après к, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "khoroshiy-syr-rynke",
      adjective: "khoroshiy",
      noun: "syr",
      case: "genitive",
      ru: "На ры́нке не оста́лось ___ {N}.",
      fr: "Il ne restait plus de bon fromage au marché.",
      why: "« сыр » est masculin singulier : au génitif, l'adjectif prend -его. Après ш non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "yarkiy-pirog-stole",
      adjective: "yarkiy",
      noun: "pirog",
      case: "nominative",
      ru: "На ку́хне лежи́т ___ {N}.",
      fr: "Dans la cuisine se trouve une tarte éclatante.",
      why: "« пирог » est masculin singulier : au nominatif, l'adjectif prend -ий. Après к, la règle des 7 lettres interdit ы : -ый s'écrit -ий.",
    },
  ],
  accusative: [
    {
      id: "molodoy-muzhchina-restoran",
      adjective: "molodoy",
      noun: "muzhchina",
      case: "accusative",
      ru: "Я ви́жу ___ {N} в рестора́не.",
      fr: "Je vois un jeune homme au restaurant.",
      why: "« мужчина » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "novyy-telefon-magazin",
      adjective: "novyy",
      noun: "telefon",
      case: "accusative",
      ru: "Он купи́л ___ {N} в магази́не.",
      fr: "Il a acheté un nouveau téléphone au magasin.",
      why: "« телефон » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ый.",
    },
    {
      id: "staryy-koroleva-portret",
      adjective: "staryy",
      noun: "koroleva",
      case: "accusative",
      ru: "Худо́жник рису́ет ___ {N} на портре́те.",
      fr: "Le peintre dessine la vieille reine sur le portrait.",
      why: "« королева » est féminin singulier : à l'accusatif, l'adjectif prend -ую.",
    },
    {
      id: "khoroshiy-drug-vstretil",
      adjective: "khoroshiy",
      noun: "drug",
      case: "accusative",
      ru: "Вчера́ я встре́тил ___ {N} на у́лице.",
      fr: "Hier j'ai rencontré un bon ami dans la rue.",
      why: "« друг » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -его. Après ш non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "vkusnyy-sup-gotovit",
      adjective: "vkusnyy",
      noun: "sup",
      case: "accusative",
      ru: "Ма́ма гото́вит ___ {N} на у́жин.",
      fr: "Maman prépare une soupe délicieuse pour le dîner.",
      why: "« суп » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ый.",
    },
    {
      id: "umnyy-devochka-khvalit",
      adjective: "umnyy",
      noun: "devochka",
      case: "accusative",
      ru: "Учи́тель хва́лит ___ {N} за отве́т.",
      fr: "Le professeur félicite une fillette intelligente pour sa réponse.",
      why: "« девочка » est féminin singulier : à l'accusatif, l'adjectif prend -ую.",
    },
    {
      id: "bolshoy-chemodan-nesti",
      adjective: "bolshoy",
      noun: "chemodan",
      case: "accusative",
      ru: "Он несёт ___ {N} на вокза́л.",
      fr: "Il porte une grande valise à la gare.",
      why: "« чемодан » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ой.",
    },
    {
      id: "molodoy-koroleva-videt",
      adjective: "molodoy",
      noun: "koroleva",
      case: "accusative",
      ru: "Наро́д уви́дел ___ {N} на пло́щади.",
      fr: "Le peuple a vu la jeune reine sur la place.",
      why: "« королева » est féminin singulier : à l'accusatif, l'adjectif prend -ую.",
    },
    {
      id: "dorogoy-chasy-podarit",
      adjective: "dorogoy",
      noun: "zerkalo",
      case: "accusative",
      ru: "Она́ поста́вила ___ {N} в спа́льню.",
      fr: "Elle a installé un miroir précieux dans la chambre.",
      why: "« зеркало » est neutre singulier : à l'accusatif, l'adjectif prend -ое.",
    },
    {
      id: "malenkiy-koshka-lyubit",
      adjective: "malenkiy",
      noun: "koshka",
      case: "accusative",
      ru: "Де́ти о́чень лю́бят ___ {N}.",
      fr: "Les enfants aiment beaucoup la petite chatte.",
      why: "« кошка » est féminin singulier : à l'accusatif, l'adjectif prend -ую.",
    },
    {
      id: "interesnyy-gost-priglasili",
      adjective: "interesnyy",
      noun: "gost",
      case: "accusative",
      ru: "Хозя́йка пригласи́ла ___ {N} на сва́дьбу.",
      fr: "L'hôtesse a invité un invité intéressant au mariage.",
      why: "« гость » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "vizhu-noviy-stul",
      adjective: "novyy",
      noun: "stul",
      case: "accusative",
      ru: "Я купи́л ___ {N} для ку́хни.",
      fr: "J'ai acheté une nouvelle chaise pour la cuisine.",
      why: "« стул » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ый.",
    },
    {
      id: "kupit-novoe-plate",
      adjective: "novyy",
      noun: "plate",
      case: "accusative",
      ru: "Она́ купи́ла ___ {N} на пра́здник.",
      fr: "Elle a acheté une nouvelle robe pour la fête.",
      why: "« платье » est neutre singulier : à l'accusatif, l'adjectif prend -ое.",
    },
    {
      id: "lyubit-dobruyu-babushku",
      adjective: "khoroshiy",
      noun: "babushka",
      case: "accusative",
      ru: "Де́ти лю́бят свою́ ___ {N}.",
      fr: "Les enfants aiment leur bonne grand-mère.",
      why: "« бабушка » est féminin singulier : à l'accusatif, l'adjectif prend -ую.",
    },
    {
      id: "pomnit-dorogogo-otsa",
      adjective: "dorogoy",
      noun: "otets",
      case: "accusative",
      ru: "Она́ всегда́ по́мнит своего́ ___ {N}.",
      fr: "Elle se souvient toujours de son cher père.",
      why: "« отец » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "kupit-vkusnyy-tort",
      adjective: "vkusnyy",
      noun: "tort",
      case: "accusative",
      ru: "Ма́ма испекла́ ___ {N} на день рожде́ния.",
      fr: "Maman a préparé un délicieux gâteau pour l'anniversaire.",
      why: "« торт » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ый.",
    },
    {
      id: "boyatsya-strashnogo-volka",
      adjective: "plokhoy",
      noun: "volk",
      case: "accusative",
      ru: "Де́ти боя́тся ___ {N} в ска́зке.",
      fr: "Les enfants ont peur du méchant loup dans le conte.",
      why: "« волк » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "vizhu-novogo-menedzhera",
      adjective: "novyy",
      noun: "menedzher",
      case: "accusative",
      ru: "Я ви́жу ___ {N} в о́фисе.",
      fr: "Je vois le nouveau gérant dans le bureau.",
      why: "« менеджер » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "vizhu-novyy-kholodilnik",
      adjective: "novyy",
      noun: "kholodilnik",
      case: "accusative",
      ru: "Мы купи́ли ___ {N} на ку́хню.",
      fr: "Nous avons acheté un nouveau réfrigérateur pour la cuisine.",
      why: "« холодильник » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ый.",
    },
    {
      id: "videt-molodogo-pilota",
      adjective: "molodoy",
      noun: "pilot",
      case: "accusative",
      ru: "Де́ти хотя́т уви́деть ___ {N} по́сле полёта.",
      fr: "Les enfants veulent voir le jeune pilote après le vol.",
      why: "« пилот » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
    {
      id: "videt-molodoy-yabloko",
      adjective: "molodoy",
      noun: "sad",
      case: "accusative",
      ru: "Они́ посади́ли ___ {N} за до́мом.",
      fr: "Ils ont planté un jeune jardin derrière la maison.",
      why: "« сад » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ой.",
    },
    {
      id: "zhdat-khoroshego-advokata",
      adjective: "khoroshiy",
      noun: "advokat",
      case: "accusative",
      ru: "Клие́нт ждёт ___ {N} пе́ред судо́м.",
      fr: "Le client attend le bon avocat avant le procès.",
      why: "« адвокат » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -его. Après ш non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "kupit-teplyy-shkarf",
      adjective: "tyoplyy",
      noun: "pidzhak",
      case: "accusative",
      ru: "Я купи́л ___ {N} на зи́му.",
      fr: "J'ai acheté une veste chaude pour l'hiver.",
      why: "« пиджак » est masculin inanimé : à l'accusatif l'adjectif copie le nominatif, d'où -ый.",
    },
    {
      id: "vstretit-plokhogo-prestupnika",
      adjective: "plokhoy",
      noun: "prestupnik",
      case: "accusative",
      ru: "Поли́ция пойма́ла ___ {N} вчера́ но́чью.",
      fr: "La police a attrapé le mauvais criminel hier soir.",
      why: "« преступник » est masculin animé : à l'accusatif l'adjectif copie le génitif, d'où -ого.",
    },
  ],
  oblique: [
    {
      id: "staryy-most-gorod",
      adjective: "staryy",
      noun: "most",
      case: "genitive",
      ru: "Мы шли к це́нтру от ___ {N}.",
      fr: "Nous marchions vers le centre depuis le vieux pont.",
      why: "« мост » est masculin singulier : au génitif, l'adjectif prend -ого.",
    },
    {
      id: "khoroshiy-vrach-bolnitsa",
      adjective: "khoroshiy",
      noun: "vrach",
      case: "instrumental",
      ru: "Пацие́нт был о́чень дово́лен ___ {N}.",
      fr: "Le patient était très content du bon médecin.",
      why: "« врач » est masculin singulier : à l'instrumental, l'adjectif prend -им. Après ш, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "russkiy-pisatel-kniga",
      adjective: "russkiy",
      noun: "pisatel",
      case: "prepositional",
      ru: "В шко́ле мы говори́ли о ___ {N}.",
      fr: "À l'école, nous parlions du célèbre écrivain russe.",
      why: "« писатель » est masculin singulier : au prépositionnel, l'adjectif prend -ом.",
    },
    {
      id: "novyy-uchitel-shkola",
      adjective: "novyy",
      noun: "uchitel",
      case: "dative",
      ru: "Де́ти принесли́ цветы́ ___ {N}.",
      fr: "Les enfants ont apporté des fleurs au nouveau professeur.",
      why: "« учитель » est masculin singulier : au datif, l'adjectif prend -ому.",
    },
    {
      id: "plokhoy-sosed-dvor",
      adjective: "plokhoy",
      noun: "sosed",
      case: "instrumental",
      ru: "Она́ поссо́рилась с ___ {N} из-за забо́ра.",
      fr: "Elle s'est disputée avec le mauvais voisin à cause de la clôture.",
      why: "« сосед » est masculin singulier : à l'instrumental, l'adjectif prend -им. Après х, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "novogo-brata-podarok",
      adjective: "novyy",
      noun: "brat",
      case: "genitive",
      ru: "Э́то пода́рок для моего́ ___ {N}.",
      fr: "C'est un cadeau pour mon nouveau frère.",
      why: "« брат » est masculin singulier : au génitif, l'adjectif prend -ого.",
    },
    {
      id: "molodomu-vrachu-pismo",
      adjective: "molodoy",
      noun: "vrach",
      case: "dative",
      ru: "Я написа́л письмо́ э́тому ___ {N}.",
      fr: "J'ai écrit une lettre à ce jeune médecin.",
      why: "« врач » est masculin singulier : au datif, l'adjectif prend -ому.",
    },
    {
      id: "interesnym-gostem-razgovor",
      adjective: "interesnyy",
      noun: "gost",
      case: "instrumental",
      ru: "Мы до́лго говори́ли с э́тим ___ {N}.",
      fr: "Nous avons longtemps parlé avec cet invité intéressant.",
      why: "« гость » est masculin singulier : à l'instrumental, l'adjectif prend -ым.",
    },
    {
      id: "tyoplom-more-otdykh",
      adjective: "tyoplyy",
      noun: "vino",
      case: "prepositional",
      ru: "Мы говори́ли о хоро́шем ___ {N}.",
      fr: "Nous avons parlé d'un bon vin.",
      why: "« вино » est neutre singulier : au prépositionnel, l'adjectif prend -ом.",
    },
    {
      id: "malenkogo-syna-igrushka",
      adjective: "malenkiy",
      noun: "rebyonok",
      case: "genitive",
      ru: "Э́то игру́шка моего́ ___ {N}.",
      fr: "C'est le jouet de mon petit enfant.",
      why: "« ребёнок » est masculin singulier : au génitif, l'adjectif prend -ого.",
    },
    {
      id: "dorogomu-druzhku-podarok",
      adjective: "dorogoy",
      noun: "drug",
      case: "dative",
      ru: "Он подари́л кольцо́ своему́ ___ {N}.",
      fr: "Il a offert une bague à son ami cher.",
      why: "« друг » est masculin singulier : au datif, l'adjectif prend -ому.",
    },
    {
      id: "siniy-chemodan-aeroport",
      adjective: "siniy",
      noun: "chemodan",
      case: "genitive",
      ru: "У ___ {N} слома́лась ру́чка.",
      fr: "La poignée de la valise bleue s'est cassée.",
      why: "« чемодан » est masculin singulier : au génitif, l'adjectif prend -его. Après н non accentué, о devient е : -ого s'écrit -его.",
    },
    {
      id: "khoroshiy-vrach-sovet",
      adjective: "khoroshiy",
      noun: "vrach",
      case: "dative",
      ru: "Мы позвони́ли ___ {N} за сове́том.",
      fr: "Nous avons appelé le bon médecin pour un conseil.",
      why: "« врач » est masculin singulier : au datif, l'adjectif prend -ему. Après ш non accentué, о devient е : -ому s'écrit -ему.",
    },
    {
      id: "dorogoy-restoran-uzhin",
      adjective: "dorogoy",
      noun: "restoran",
      case: "prepositional",
      ru: "Мы у́жинали в ___ {N}.",
      fr: "Nous avons dîné dans le restaurant cher.",
      why: "« ресторан » est masculin singulier : au prépositionnel, l'adjectif prend -ом.",
    },
    {
      id: "molodoy-pisatel-interview",
      adjective: "molodoy",
      noun: "pisatel",
      case: "genitive",
      ru: "Мы жда́ли кни́гу от ___ {N}.",
      fr: "Nous attendions un livre du jeune écrivain.",
      why: "« писатель » est masculin singulier : au génitif, l'adjectif prend -ого.",
    },
    {
      id: "umnyy-student-zadacha",
      adjective: "umnyy",
      noun: "student",
      case: "dative",
      ru: "Учи́тель дал зада́чу ___ {N}.",
      fr: "Le professeur a donné un problème à l'étudiant intelligent.",
      why: "« студент » est masculin singulier : au datif, l'adjectif prend -ому.",
    },
    {
      id: "bolshoy-nozh-myaso",
      adjective: "bolshoy",
      noun: "nozh",
      case: "instrumental",
      ru: "Она́ ре́зала мя́со ___ {N}.",
      fr: "Elle coupait la viande avec le grand couteau.",
      why: "« нож » est masculin singulier : à l'instrumental, l'adjectif prend -им. Après ш, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "russkiy-korol-vremya",
      adjective: "russkiy",
      noun: "korol",
      case: "dative",
      ru: "Письмо́ отпра́вили ___ {N}.",
      fr: "On a envoyé une lettre au roi russe.",
      why: "« король » est masculin singulier : au datif, l'adjectif prend -ому.",
    },
  ],
  plural: [
    {
      id: "novyye-studenty-nom",
      adjective: "novyy",
      noun: "student",
      case: "nominative",
      plural: true,
      ru: "___ {N} пришли́ на ле́кцию.",
      fr: "Les nouveaux étudiants sont arrivés au cours.",
      why: "« студент » est au pluriel, où le genre disparaît : au nominatif, l'adjectif prend -ые.",
    },
    {
      id: "vkusnyye-blyuda-prep",
      adjective: "vkusnyy",
      noun: "blyudo",
      case: "prepositional",
      plural: true,
      ru: "Мы говори́ли о ___ {N} э́того рестора́на.",
      fr: "Nous avons parlé des plats délicieux de ce restaurant.",
      why: "« блюдо » est au pluriel, où le genre disparaît : au prépositionnel, l'adjectif prend -ых.",
    },
    {
      id: "dorogiye-podarki-prep",
      adjective: "dorogoy",
      noun: "podarok",
      case: "prepositional",
      plural: true,
      ru: "Она́ рассказа́ла о ___ {N} на сва́дьбе.",
      fr: "Elle a parlé des cadeaux précieux offerts au mariage.",
      why: "« подарок » est au pluriel, où le genre disparaît : au prépositionnel, l'adjectif prend -их. Après г, la règle des 7 lettres interdit ы : -ых s'écrit -их.",
    },
    {
      id: "staryye-doma-gen",
      adjective: "staryy",
      noun: "dom",
      case: "genitive",
      plural: true,
      ru: "На э́той у́лице мно́го ___ {N}.",
      fr: "Dans cette rue il y a beaucoup de vieilles maisons.",
      why: "« дом » est au pluriel, où le genre disparaît : au génitif, l'adjectif prend -ых.",
    },
    {
      id: "krasivyye-kartiny-acc",
      adjective: "krasivyy",
      noun: "kartina",
      case: "accusative",
      plural: true,
      ru: "Мы купи́ли ___ {N} для гости́ной.",
      fr: "Nous avons acheté de beaux tableaux pour le salon.",
      why: "« картина » est au pluriel, où le genre disparaît : à l'accusatif, l'adjectif prend -ые.",
    },
    {
      id: "vkusnyye-pirogi-instr",
      adjective: "vkusnyy",
      noun: "pirog",
      case: "instrumental",
      plural: true,
      ru: "Ба́бушка угости́ла нас ___ {N}.",
      fr: "Grand-mère nous a régalés de délicieuses tartes.",
      why: "« пирог » est au pluriel, où le genre disparaît : à l'instrumental, l'adjectif prend -ыми.",
    },
    {
      id: "bolshiye-goroda-nom",
      adjective: "bolshoy",
      noun: "gorod",
      case: "nominative",
      plural: true,
      ru: "___ {N} расту́т о́чень бы́стро.",
      fr: "Les grandes villes grandissent très vite.",
      why: "« город » est au pluriel, où le genre disparaît : au nominatif, l'adjectif prend -ие. Après ш, la règle des 7 lettres interdit ы : -ые s'écrit -ие.",
    },
    {
      id: "molodyye-uchitelya-gen",
      adjective: "molodoy",
      noun: "uchitel",
      case: "genitive",
      plural: true,
      ru: "В шко́ле не хвата́ет ___ {N}.",
      fr: "L'école manque de jeunes professeurs.",
      why: "« учитель » est au pluriel, où le genre disparaît : au génitif, l'adjectif prend -ых.",
    },
    {
      id: "russkiye-pesni-instr",
      adjective: "russkiy",
      noun: "pisatel",
      case: "instrumental",
      plural: true,
      ru: "Студе́нты интересу́ются ___ {N}.",
      fr: "Les étudiants s'intéressent aux écrivains russes.",
      why: "« писатель » est au pluriel, où le genre disparaît : à l'instrumental, l'adjectif prend -ими. Après к, la règle des 7 lettres interdit ы : -ыми s'écrit -ими.",
    },
    {
      id: "staryye-fotografii-gen",
      adjective: "staryy",
      noun: "fotografiya",
      case: "genitive",
      plural: true,
      ru: "У ба́бушки мно́го ___ {N}.",
      fr: "Grand-mère a beaucoup de vieilles photos.",
      why: "« фотография » est au pluriel, où le genre disparaît : au génitif, l'adjectif prend -ых.",
    },
    {
      id: "khoroshiye-vrachi-dat",
      adjective: "khoroshiy",
      noun: "vrach",
      case: "dative",
      plural: true,
      ru: "Пацие́нты доверя́ют э́тим ___ {N}.",
      fr: "Les patients font confiance à ces bons médecins.",
      why: "« врач » est au pluriel, où le genre disparaît : au datif, l'adjectif prend -им. Après ш, la règle des 7 lettres interdit ы : -ым s'écrit -им.",
    },
    {
      id: "bolshiye-sobaki-instr",
      adjective: "bolshoy",
      noun: "sobaka",
      case: "instrumental",
      plural: true,
      ru: "Охо́тник гуля́л с двумя́ ___ {N}.",
      fr: "Le chasseur se promenait avec deux grands chiens.",
      why: "« собака » est au pluriel, où le genre disparaît : à l'instrumental, l'adjectif prend -ими. Après ш, la règle des 7 lettres interdit ы : -ыми s'écrit -ими.",
    },
    {
      id: "vkusnyye-suply-nom",
      adjective: "vkusnyy",
      noun: "sup",
      case: "nominative",
      plural: true,
      ru: "На обе́д всегда́ ___ {N}.",
      fr: "Au déjeuner, il y a toujours de délicieuses soupes.",
      why: "« суп » est au pluriel, où le genre disparaît : au nominatif, l'adjectif prend -ые.",
    },
    {
      id: "molodyye-uchitelya-dat",
      adjective: "molodoy",
      noun: "uchitel",
      case: "dative",
      plural: true,
      ru: "Дире́ктор дал сове́т ___ {N}.",
      fr: "Le directeur a donné un conseil aux jeunes professeurs.",
      why: "« учитель » est au pluriel, où le genre disparaît : au datif, l'adjectif prend -ым.",
    },
    {
      id: "dorogiye-kolca-instr",
      adjective: "dorogoy",
      noun: "koltso",
      case: "instrumental",
      plural: true,
      ru: "Неве́ста хва́сталась свои́ми ___ {N}.",
      fr: "La fiancée se vantait de ses bagues précieuses.",
      why: "« кольцо » est au pluriel, où le genre disparaît : à l'instrumental, l'adjectif prend -ими. Après г, la règle des 7 lettres interdit ы : -ыми s'écrit -ими.",
    },
  ],
};
